// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.0
// - protoc             v4.23.4
// source: dummy/v1/dummy.proto

package dummy_v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationDummyCreateDummy = "/api.dummy.v1.Dummy/CreateDummy"

type DummyHTTPServer interface {
	CreateDummy(context.Context, *DummyRequest) (*DummyReply, error)
}

func RegisterDummyHTTPServer(s *http.Server, srv DummyHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/dummy", _Dummy_CreateDummy0_HTTP_Handler(srv))
}

func _Dummy_CreateDummy0_HTTP_Handler(srv DummyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DummyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDummyCreateDummy)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateDummy(ctx, req.(*DummyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DummyReply)
		return ctx.Result(200, reply)
	}
}

type DummyHTTPClient interface {
	CreateDummy(ctx context.Context, req *DummyRequest, opts ...http.CallOption) (rsp *DummyReply, err error)
}

type DummyHTTPClientImpl struct {
	cc *http.Client
}

func NewDummyHTTPClient(client *http.Client) DummyHTTPClient {
	return &DummyHTTPClientImpl{client}
}

func (c *DummyHTTPClientImpl) CreateDummy(ctx context.Context, in *DummyRequest, opts ...http.CallOption) (*DummyReply, error) {
	var out DummyReply
	pattern := "/v1/dummy"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDummyCreateDummy))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
