version: '3.5'

services:
  service:
    image: ${REGISTRY_IMAGE}
    container_name: ${SERVICE_NAME}_service
    networks:
      - backend
    restart: unless-stopped
    environment:
      - SERVICE_NAME=${SERVICE_NAME}
      - CONSUL_ADDRESS=${CONSUL_ADDRESS}
      - VAULT_ADDRESS=${VAULT_ADDRESS}
      - VAULT_ROLE_ID=${VAULT_ROLE_ID}
      - VAULT_SECRET_ID_PATH=/run/secrets/vault_secret_id
      - OTLP_GRPC_ADDRESS=${OTLP_GRPC_ADDRESS}
    secrets:
      - vault_secret_id
    command: ["./app"]

networks:
  backend:
    name: ${NETWORK}
    driver: bridge
    external: true

secrets:
  vault_secret_id:
    environment: 'VAULT_SECRET_ID'
