// Code generated by ent, DO NOT EDIT.

package subscriptionstatus

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"gitlab.calendaria.team/services/finance/invoices/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldLTE(FieldID, id))
}

// InvoiceID applies equality check predicate on the "invoice_id" field. It's identical to InvoiceIDEQ.
func InvoiceID(v int64) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldEQ(FieldInvoiceID, v))
}

// ItemID applies equality check predicate on the "item_id" field. It's identical to ItemIDEQ.
func ItemID(v int64) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldEQ(FieldItemID, v))
}

// ActiveTill applies equality check predicate on the "active_till" field. It's identical to ActiveTillEQ.
func ActiveTill(v time.Time) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldEQ(FieldActiveTill, v))
}

// StartFrom applies equality check predicate on the "start_from" field. It's identical to StartFromEQ.
func StartFrom(v time.Time) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldEQ(FieldStartFrom, v))
}

// InvoiceIDEQ applies the EQ predicate on the "invoice_id" field.
func InvoiceIDEQ(v int64) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldEQ(FieldInvoiceID, v))
}

// InvoiceIDNEQ applies the NEQ predicate on the "invoice_id" field.
func InvoiceIDNEQ(v int64) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldNEQ(FieldInvoiceID, v))
}

// InvoiceIDIn applies the In predicate on the "invoice_id" field.
func InvoiceIDIn(vs ...int64) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldIn(FieldInvoiceID, vs...))
}

// InvoiceIDNotIn applies the NotIn predicate on the "invoice_id" field.
func InvoiceIDNotIn(vs ...int64) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldNotIn(FieldInvoiceID, vs...))
}

// ItemIDEQ applies the EQ predicate on the "item_id" field.
func ItemIDEQ(v int64) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldEQ(FieldItemID, v))
}

// ItemIDNEQ applies the NEQ predicate on the "item_id" field.
func ItemIDNEQ(v int64) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldNEQ(FieldItemID, v))
}

// ItemIDIn applies the In predicate on the "item_id" field.
func ItemIDIn(vs ...int64) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldIn(FieldItemID, vs...))
}

// ItemIDNotIn applies the NotIn predicate on the "item_id" field.
func ItemIDNotIn(vs ...int64) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldNotIn(FieldItemID, vs...))
}

// ActiveTillEQ applies the EQ predicate on the "active_till" field.
func ActiveTillEQ(v time.Time) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldEQ(FieldActiveTill, v))
}

// ActiveTillNEQ applies the NEQ predicate on the "active_till" field.
func ActiveTillNEQ(v time.Time) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldNEQ(FieldActiveTill, v))
}

// ActiveTillIn applies the In predicate on the "active_till" field.
func ActiveTillIn(vs ...time.Time) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldIn(FieldActiveTill, vs...))
}

// ActiveTillNotIn applies the NotIn predicate on the "active_till" field.
func ActiveTillNotIn(vs ...time.Time) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldNotIn(FieldActiveTill, vs...))
}

// ActiveTillGT applies the GT predicate on the "active_till" field.
func ActiveTillGT(v time.Time) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldGT(FieldActiveTill, v))
}

// ActiveTillGTE applies the GTE predicate on the "active_till" field.
func ActiveTillGTE(v time.Time) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldGTE(FieldActiveTill, v))
}

// ActiveTillLT applies the LT predicate on the "active_till" field.
func ActiveTillLT(v time.Time) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldLT(FieldActiveTill, v))
}

// ActiveTillLTE applies the LTE predicate on the "active_till" field.
func ActiveTillLTE(v time.Time) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldLTE(FieldActiveTill, v))
}

// ActiveTillIsNil applies the IsNil predicate on the "active_till" field.
func ActiveTillIsNil() predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldIsNull(FieldActiveTill))
}

// ActiveTillNotNil applies the NotNil predicate on the "active_till" field.
func ActiveTillNotNil() predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldNotNull(FieldActiveTill))
}

// StartFromEQ applies the EQ predicate on the "start_from" field.
func StartFromEQ(v time.Time) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldEQ(FieldStartFrom, v))
}

// StartFromNEQ applies the NEQ predicate on the "start_from" field.
func StartFromNEQ(v time.Time) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldNEQ(FieldStartFrom, v))
}

// StartFromIn applies the In predicate on the "start_from" field.
func StartFromIn(vs ...time.Time) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldIn(FieldStartFrom, vs...))
}

// StartFromNotIn applies the NotIn predicate on the "start_from" field.
func StartFromNotIn(vs ...time.Time) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldNotIn(FieldStartFrom, vs...))
}

// StartFromGT applies the GT predicate on the "start_from" field.
func StartFromGT(v time.Time) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldGT(FieldStartFrom, v))
}

// StartFromGTE applies the GTE predicate on the "start_from" field.
func StartFromGTE(v time.Time) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldGTE(FieldStartFrom, v))
}

// StartFromLT applies the LT predicate on the "start_from" field.
func StartFromLT(v time.Time) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldLT(FieldStartFrom, v))
}

// StartFromLTE applies the LTE predicate on the "start_from" field.
func StartFromLTE(v time.Time) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldLTE(FieldStartFrom, v))
}

// StartFromIsNil applies the IsNil predicate on the "start_from" field.
func StartFromIsNil() predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldIsNull(FieldStartFrom))
}

// StartFromNotNil applies the NotNil predicate on the "start_from" field.
func StartFromNotNil() predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.FieldNotNull(FieldStartFrom))
}

// HasInvoice applies the HasEdge predicate on the "invoice" edge.
func HasInvoice() predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InvoiceTable, InvoiceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInvoiceWith applies the HasEdge predicate on the "invoice" edge with a given conditions (other predicates).
func HasInvoiceWith(preds ...predicate.Invoice) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(func(s *sql.Selector) {
		step := newInvoiceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasItem applies the HasEdge predicate on the "item" edge.
func HasItem() predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ItemTable, ItemColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemWith applies the HasEdge predicate on the "item" edge with a given conditions (other predicates).
func HasItemWith(preds ...predicate.Item) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(func(s *sql.Selector) {
		step := newItemStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubscriptionStatus) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubscriptionStatus) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubscriptionStatus) predicate.SubscriptionStatus {
	return predicate.SubscriptionStatus(sql.NotPredicates(p))
}
