// Code generated by MockGen. DO NOT EDIT.
// Source: internal/data/invoices.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	ent "gitlab.calendaria.team/services/finance/billing/ent"
	data "gitlab.calendaria.team/services/finance/billing/internal/data"
	utils_v1 "gitlab.calendaria.team/services/utils/api/utils/v1"
)

// MockInvoicesRepo is a mock of InvoicesRepo interface.
type MockInvoicesRepo struct {
	ctrl     *gomock.Controller
	recorder *MockInvoicesRepoMockRecorder
}

// MockInvoicesRepoMockRecorder is the mock recorder for MockInvoicesRepo.
type MockInvoicesRepoMockRecorder struct {
	mock *MockInvoicesRepo
}

// NewMockInvoicesRepo creates a new mock instance.
func NewMockInvoicesRepo(ctrl *gomock.Controller) *MockInvoicesRepo {
	mock := &MockInvoicesRepo{ctrl: ctrl}
	mock.recorder = &MockInvoicesRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvoicesRepo) EXPECT() *MockInvoicesRepoMockRecorder {
	return m.recorder
}

// CountInvoices mocks base method.
func (m *MockInvoicesRepo) CountInvoices(ctx context.Context, filter data.InvoiceFilter) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountInvoices", ctx, filter)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountInvoices indicates an expected call of CountInvoices.
func (mr *MockInvoicesRepoMockRecorder) CountInvoices(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountInvoices", reflect.TypeOf((*MockInvoicesRepo)(nil).CountInvoices), ctx, filter)
}

// CreateInvoice mocks base method.
func (m *MockInvoicesRepo) CreateInvoice(ctx context.Context, dto data.InvoiceDto) (*ent.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvoice", ctx, dto)
	ret0, _ := ret[0].(*ent.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvoice indicates an expected call of CreateInvoice.
func (mr *MockInvoicesRepoMockRecorder) CreateInvoice(ctx, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvoice", reflect.TypeOf((*MockInvoicesRepo)(nil).CreateInvoice), ctx, dto)
}

// DeleteInvoice mocks base method.
func (m *MockInvoicesRepo) DeleteInvoice(ctx context.Context, invoiceID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInvoice", ctx, invoiceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInvoice indicates an expected call of DeleteInvoice.
func (mr *MockInvoicesRepoMockRecorder) DeleteInvoice(ctx, invoiceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInvoice", reflect.TypeOf((*MockInvoicesRepo)(nil).DeleteInvoice), ctx, invoiceID)
}

// GetInvoice mocks base method.
func (m *MockInvoicesRepo) GetInvoice(ctx context.Context, actorID, tenantID int64, appID string, invoiceID int64) (*ent.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvoice", ctx, actorID, tenantID, appID, invoiceID)
	ret0, _ := ret[0].(*ent.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvoice indicates an expected call of GetInvoice.
func (mr *MockInvoicesRepoMockRecorder) GetInvoice(ctx, actorID, tenantID, appID, invoiceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoice", reflect.TypeOf((*MockInvoicesRepo)(nil).GetInvoice), ctx, actorID, tenantID, appID, invoiceID)
}

// GetInvoiceByID mocks base method.
func (m *MockInvoicesRepo) GetInvoiceByID(ctx context.Context, id int64) (*ent.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvoiceByID", ctx, id)
	ret0, _ := ret[0].(*ent.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvoiceByID indicates an expected call of GetInvoiceByID.
func (mr *MockInvoicesRepoMockRecorder) GetInvoiceByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoiceByID", reflect.TypeOf((*MockInvoicesRepo)(nil).GetInvoiceByID), ctx, id)
}

// GetInvoicesToExpire mocks base method.
func (m *MockInvoicesRepo) GetInvoicesToExpire(ctx context.Context, paidTill *time.Time) ([]*ent.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvoicesToExpire", ctx, paidTill)
	ret0, _ := ret[0].([]*ent.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvoicesToExpire indicates an expected call of GetInvoicesToExpire.
func (mr *MockInvoicesRepoMockRecorder) GetInvoicesToExpire(ctx, paidTill interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoicesToExpire", reflect.TypeOf((*MockInvoicesRepo)(nil).GetInvoicesToExpire), ctx, paidTill)
}

// GetInvoicesToRevoke mocks base method.
func (m *MockInvoicesRepo) GetInvoicesToRevoke(ctx context.Context, paidTill *time.Time) ([]*ent.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvoicesToRevoke", ctx, paidTill)
	ret0, _ := ret[0].([]*ent.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvoicesToRevoke indicates an expected call of GetInvoicesToRevoke.
func (mr *MockInvoicesRepoMockRecorder) GetInvoicesToRevoke(ctx, paidTill interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoicesToRevoke", reflect.TypeOf((*MockInvoicesRepo)(nil).GetInvoicesToRevoke), ctx, paidTill)
}

// GetUserAndTenantIDByOriginalTransactionID mocks base method.
func (m *MockInvoicesRepo) GetUserAndTenantIDByOriginalTransactionID(ctx context.Context, originalTransactionID string) (int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAndTenantIDByOriginalTransactionID", ctx, originalTransactionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserAndTenantIDByOriginalTransactionID indicates an expected call of GetUserAndTenantIDByOriginalTransactionID.
func (mr *MockInvoicesRepoMockRecorder) GetUserAndTenantIDByOriginalTransactionID(ctx, originalTransactionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAndTenantIDByOriginalTransactionID", reflect.TypeOf((*MockInvoicesRepo)(nil).GetUserAndTenantIDByOriginalTransactionID), ctx, originalTransactionID)
}

// ListInvoices mocks base method.
func (m *MockInvoicesRepo) ListInvoices(ctx context.Context, filter data.InvoiceFilter, paginate *utils_v1.PaginateRequest) ([]*ent.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInvoices", ctx, filter, paginate)
	ret0, _ := ret[0].([]*ent.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInvoices indicates an expected call of ListInvoices.
func (mr *MockInvoicesRepoMockRecorder) ListInvoices(ctx, filter, paginate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInvoices", reflect.TypeOf((*MockInvoicesRepo)(nil).ListInvoices), ctx, filter, paginate)
}

// UpdateInvoice mocks base method.
func (m *MockInvoicesRepo) UpdateInvoice(ctx context.Context, invoiceData *ent.Invoice, dto data.InvoiceDto) (*ent.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInvoice", ctx, invoiceData, dto)
	ret0, _ := ret[0].(*ent.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateInvoice indicates an expected call of UpdateInvoice.
func (mr *MockInvoicesRepoMockRecorder) UpdateInvoice(ctx, invoiceData, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInvoice", reflect.TypeOf((*MockInvoicesRepo)(nil).UpdateInvoice), ctx, invoiceData, dto)
}
