// Code generated by MockGen. DO NOT EDIT.
// Source: internal/data/subscription.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	ent "gitlab.calendaria.team/services/finance/billing/ent"
	data "gitlab.calendaria.team/services/finance/billing/internal/data"
	utils_v1 "gitlab.calendaria.team/services/utils/api/utils/v1"
)

// MockSubscriptionsRepo is a mock of SubscriptionsRepo interface.
type MockSubscriptionsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionsRepoMockRecorder
}

// MockSubscriptionsRepoMockRecorder is the mock recorder for MockSubscriptionsRepo.
type MockSubscriptionsRepoMockRecorder struct {
	mock *MockSubscriptionsRepo
}

// NewMockSubscriptionsRepo creates a new mock instance.
func NewMockSubscriptionsRepo(ctrl *gomock.Controller) *MockSubscriptionsRepo {
	mock := &MockSubscriptionsRepo{ctrl: ctrl}
	mock.recorder = &MockSubscriptionsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionsRepo) EXPECT() *MockSubscriptionsRepoMockRecorder {
	return m.recorder
}

// CountSubscriptions mocks base method.
func (m *MockSubscriptionsRepo) CountSubscriptions(ctx context.Context, actorID int64) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSubscriptions", ctx, actorID)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSubscriptions indicates an expected call of CountSubscriptions.
func (mr *MockSubscriptionsRepoMockRecorder) CountSubscriptions(ctx, actorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSubscriptions", reflect.TypeOf((*MockSubscriptionsRepo)(nil).CountSubscriptions), ctx, actorID)
}

// CreateSubscription mocks base method.
func (m *MockSubscriptionsRepo) CreateSubscription(ctx context.Context, actorID, tenantID int64, appID string, dto data.SubscriptionDto) (*ent.Subscriptions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscription", ctx, actorID, tenantID, appID, dto)
	ret0, _ := ret[0].(*ent.Subscriptions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubscription indicates an expected call of CreateSubscription.
func (mr *MockSubscriptionsRepoMockRecorder) CreateSubscription(ctx, actorID, tenantID, appID, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscription", reflect.TypeOf((*MockSubscriptionsRepo)(nil).CreateSubscription), ctx, actorID, tenantID, appID, dto)
}

// DeleteSubscription mocks base method.
func (m *MockSubscriptionsRepo) DeleteSubscription(ctx context.Context, actorID, subscriptionID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubscription", ctx, actorID, subscriptionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubscription indicates an expected call of DeleteSubscription.
func (mr *MockSubscriptionsRepoMockRecorder) DeleteSubscription(ctx, actorID, subscriptionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubscription", reflect.TypeOf((*MockSubscriptionsRepo)(nil).DeleteSubscription), ctx, actorID, subscriptionID)
}

// GetActiveAppleSubscriptions mocks base method.
func (m *MockSubscriptionsRepo) GetActiveAppleSubscriptions(ctx context.Context) ([]*ent.Subscriptions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveAppleSubscriptions", ctx)
	ret0, _ := ret[0].([]*ent.Subscriptions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveAppleSubscriptions indicates an expected call of GetActiveAppleSubscriptions.
func (mr *MockSubscriptionsRepoMockRecorder) GetActiveAppleSubscriptions(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveAppleSubscriptions", reflect.TypeOf((*MockSubscriptionsRepo)(nil).GetActiveAppleSubscriptions), ctx)
}

// GetSubscription mocks base method.
func (m *MockSubscriptionsRepo) GetSubscription(ctx context.Context, actorID, tenantID int64, appID string, subscriptionID int64, withInvoices bool) (*ent.Subscriptions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscription", ctx, actorID, tenantID, appID, subscriptionID, withInvoices)
	ret0, _ := ret[0].(*ent.Subscriptions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscription indicates an expected call of GetSubscription.
func (mr *MockSubscriptionsRepoMockRecorder) GetSubscription(ctx, actorID, tenantID, appID, subscriptionID, withInvoices interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscription", reflect.TypeOf((*MockSubscriptionsRepo)(nil).GetSubscription), ctx, actorID, tenantID, appID, subscriptionID, withInvoices)
}

// GetSubscriptionByOriginalAppleTransactionID mocks base method.
func (m *MockSubscriptionsRepo) GetSubscriptionByOriginalAppleTransactionID(ctx context.Context, originalTransactionID string, withInvoices bool) (*ent.Subscriptions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionByOriginalAppleTransactionID", ctx, originalTransactionID, withInvoices)
	ret0, _ := ret[0].(*ent.Subscriptions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionByOriginalAppleTransactionID indicates an expected call of GetSubscriptionByOriginalAppleTransactionID.
func (mr *MockSubscriptionsRepoMockRecorder) GetSubscriptionByOriginalAppleTransactionID(ctx, originalTransactionID, withInvoices interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionByOriginalAppleTransactionID", reflect.TypeOf((*MockSubscriptionsRepo)(nil).GetSubscriptionByOriginalAppleTransactionID), ctx, originalTransactionID, withInvoices)
}

// ListSubscriptions mocks base method.
func (m *MockSubscriptionsRepo) ListSubscriptions(ctx context.Context, actorID int64, withInvoices bool, paginate *utils_v1.PaginateRequest) ([]*ent.Subscriptions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubscriptions", ctx, actorID, withInvoices, paginate)
	ret0, _ := ret[0].([]*ent.Subscriptions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubscriptions indicates an expected call of ListSubscriptions.
func (mr *MockSubscriptionsRepoMockRecorder) ListSubscriptions(ctx, actorID, withInvoices, paginate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubscriptions", reflect.TypeOf((*MockSubscriptionsRepo)(nil).ListSubscriptions), ctx, actorID, withInvoices, paginate)
}

// RevokeActiveSubscription mocks base method.
func (m *MockSubscriptionsRepo) RevokeActiveSubscription(ctx context.Context, subscriptionID int64, revokedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeActiveSubscription", ctx, subscriptionID, revokedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeActiveSubscription indicates an expected call of RevokeActiveSubscription.
func (mr *MockSubscriptionsRepoMockRecorder) RevokeActiveSubscription(ctx, subscriptionID, revokedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeActiveSubscription", reflect.TypeOf((*MockSubscriptionsRepo)(nil).RevokeActiveSubscription), ctx, subscriptionID, revokedAt)
}
