// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.0
// - protoc             v5.28.1
// source: api/invoices/v1/apple_store.proto

package invoices_v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	v1 "gitlab.calendaria.team/services/utils/api/utils/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAppleStoreProcessServerMessage = "/invoices.v1.AppleStore/ProcessServerMessage"

type AppleStoreHTTPServer interface {
	ProcessServerMessage(context.Context, *ProcessServerMessageRequest) (*v1.EmptyReply, error)
}

func RegisterAppleStoreHTTPServer(s *http.Server, srv AppleStoreHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/apple_store", _AppleStore_ProcessServerMessage0_HTTP_Handler(srv))
}

func _AppleStore_ProcessServerMessage0_HTTP_Handler(srv AppleStoreHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ProcessServerMessageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAppleStoreProcessServerMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ProcessServerMessage(ctx, req.(*ProcessServerMessageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.EmptyReply)
		return ctx.Result(200, reply)
	}
}

type AppleStoreHTTPClient interface {
	ProcessServerMessage(ctx context.Context, req *ProcessServerMessageRequest, opts ...http.CallOption) (rsp *v1.EmptyReply, err error)
}

type AppleStoreHTTPClientImpl struct {
	cc *http.Client
}

func NewAppleStoreHTTPClient(client *http.Client) AppleStoreHTTPClient {
	return &AppleStoreHTTPClientImpl{client}
}

func (c *AppleStoreHTTPClientImpl) ProcessServerMessage(ctx context.Context, in *ProcessServerMessageRequest, opts ...http.CallOption) (*v1.EmptyReply, error) {
	var out v1.EmptyReply
	pattern := "/v1/apple_store"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAppleStoreProcessServerMessage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
