// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: api/billing/v1/apple_store.proto

package billing_v1

import (
	context "context"
	v1 "gitlab.calendaria.team/services/utils/api/utils/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AppleStore_ProcessServerNotification_FullMethodName = "/billing.v1.AppleStore/ProcessServerNotification"
)

// AppleStoreClient is the client API for AppleStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppleStoreClient interface {
	ProcessServerNotification(ctx context.Context, in *ProcessServerNotificationRequest, opts ...grpc.CallOption) (*v1.EmptyReply, error)
}

type appleStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewAppleStoreClient(cc grpc.ClientConnInterface) AppleStoreClient {
	return &appleStoreClient{cc}
}

func (c *appleStoreClient) ProcessServerNotification(ctx context.Context, in *ProcessServerNotificationRequest, opts ...grpc.CallOption) (*v1.EmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.EmptyReply)
	err := c.cc.Invoke(ctx, AppleStore_ProcessServerNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppleStoreServer is the server API for AppleStore service.
// All implementations must embed UnimplementedAppleStoreServer
// for forward compatibility.
type AppleStoreServer interface {
	ProcessServerNotification(context.Context, *ProcessServerNotificationRequest) (*v1.EmptyReply, error)
	mustEmbedUnimplementedAppleStoreServer()
}

// UnimplementedAppleStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAppleStoreServer struct{}

func (UnimplementedAppleStoreServer) ProcessServerNotification(context.Context, *ProcessServerNotificationRequest) (*v1.EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessServerNotification not implemented")
}
func (UnimplementedAppleStoreServer) mustEmbedUnimplementedAppleStoreServer() {}
func (UnimplementedAppleStoreServer) testEmbeddedByValue()                    {}

// UnsafeAppleStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppleStoreServer will
// result in compilation errors.
type UnsafeAppleStoreServer interface {
	mustEmbedUnimplementedAppleStoreServer()
}

func RegisterAppleStoreServer(s grpc.ServiceRegistrar, srv AppleStoreServer) {
	// If the following call pancis, it indicates UnimplementedAppleStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AppleStore_ServiceDesc, srv)
}

func _AppleStore_ProcessServerNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessServerNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppleStoreServer).ProcessServerNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppleStore_ProcessServerNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppleStoreServer).ProcessServerNotification(ctx, req.(*ProcessServerNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AppleStore_ServiceDesc is the grpc.ServiceDesc for AppleStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppleStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "billing.v1.AppleStore",
	HandlerType: (*AppleStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessServerNotification",
			Handler:    _AppleStore_ProcessServerNotification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/billing/v1/apple_store.proto",
}
