// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"gitlab.calendaria.team/services/finance/billing/internal/biz"
	"gitlab.calendaria.team/services/finance/billing/internal/conf"
	"gitlab.calendaria.team/services/finance/billing/internal/data"
	"gitlab.calendaria.team/services/finance/billing/internal/server"
	"gitlab.calendaria.team/services/finance/billing/internal/service"
	"gitlab.calendaria.team/services/utils/v1/config"
	"gitlab.calendaria.team/services/utils/v1/nats"
	"gitlab.calendaria.team/services/utils/v2/jwt"
	"gitlab.calendaria.team/services/utils/v2/tracing"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	iJwtProcessor, err := jwt.NewJwtProcessor(configConfig)
	if err != nil {
		return nil, nil, err
	}
	tracer := tracing.NewTracer(configConfig)
	dataData, cleanup, err := data.NewData(bootstrap, configConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	itemsRepo := data.NewItemsRepo(dataData)
	itemUseCase := biz.NewItemsUsecase(itemsRepo)
	itemService := service.NewItemService(itemUseCase)
	productRepo := data.NewProductsRepo(dataData)
	productUseCase := biz.NewProductUseCase(productRepo)
	productService := service.NewProductService(productUseCase)
	invoicesRepo := data.NewInvoicesRepo(dataData)
	encodedConn, cleanup2, err := data.NewNatsClient(bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	iQueueManager := nats.NewQueueManager(configConfig, encodedConn, logger)
	invoicesUseCase := biz.NewInvoicesUseCase(logger, invoicesRepo, itemsRepo, productRepo, iQueueManager)
	invoiceService := service.NewInvoiceService(invoicesUseCase)
	subscriptionsRepo := data.NewSubscriptionsRepo(dataData)
	subscriptionsUseCase := biz.NewSubscriptionUsecase(subscriptionsRepo)
	subscriptionService := service.NewSubscriptionService(subscriptionsUseCase)
	appleStoreUsecase := biz.NewAppleStoreUsecase(invoicesRepo)
	appleStoreService := service.NewAppleStoreService(appleStoreUsecase)
	grpcServer := server.NewGRPCServer(bootstrap, iJwtProcessor, tracer, itemService, productService, invoiceService, subscriptionService, appleStoreService)
	httpServer := server.NewHTTPServer(bootstrap, iJwtProcessor)
	cronServer := server.NewCronServer(logger, invoicesUseCase)
	app := newApp(logger, configConfig, grpcServer, httpServer, cronServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
