// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"gitlab.calendaria.team/services/finance/billing/internal/biz"
	"gitlab.calendaria.team/services/finance/billing/internal/conf"
	"gitlab.calendaria.team/services/finance/billing/internal/data"
	"gitlab.calendaria.team/services/finance/billing/internal/server"
	"gitlab.calendaria.team/services/finance/billing/internal/service"
	"gitlab.calendaria.team/services/utils/v4/config"
	"gitlab.calendaria.team/services/utils/v4/jwt"
	"gitlab.calendaria.team/services/utils/v4/nats"
	"gitlab.calendaria.team/services/utils/v4/tracing"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	iConfig, err := config.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	iJwtProcessor, err := jwt.NewJwtProcessor(iConfig)
	if err != nil {
		return nil, nil, err
	}
	iTracer := tracing.NewTracer(iConfig)
	dataData, cleanup, err := data.NewData(bootstrap, iConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	itemsRepo := data.NewItemsRepo(dataData)
	itemUseCase := biz.NewItemsUsecase(itemsRepo)
	itemService := service.NewItemService(itemUseCase)
	productRepo := data.NewProductsRepo(dataData)
	productUseCase := biz.NewProductUseCase(productRepo)
	productService := service.NewProductService(productUseCase)
	productReservationRepo := data.NewProductReservationRepo(dataData)
	invoicesRepo := data.NewInvoicesRepo(dataData)
	invoicesManager := biz.NewInvoicesManager(logger, productRepo, productReservationRepo, invoicesRepo)
	conn, cleanup2, err := data.NewNatsClient(bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	iQueueManager := nats.NewQueueManager(iConfig, conn, logger)
	invoicesUseCase := biz.NewInvoicesUseCase(logger, invoicesManager, invoicesRepo, itemsRepo, productRepo, productReservationRepo, iQueueManager)
	invoiceService := service.NewInvoiceService(invoicesUseCase)
	subscriptionsRepo := data.NewSubscriptionsRepo(dataData)
	subscriptionsUseCase := biz.NewSubscriptionUsecase(subscriptionsRepo)
	subscriptionService := service.NewSubscriptionService(subscriptionsUseCase)
	jwtParser := data.NewDefaultJWTParser()
	appleStoreClient, err := data.NewAppleStoreClient(iConfig, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	appleStoreUsecase := biz.NewAppleStoreUsecase(invoicesRepo, subscriptionsRepo, productRepo, jwtParser, appleStoreClient)
	appleStoreService := service.NewAppleStoreService(appleStoreUsecase)
	ovpClient := data.NewOvpClient(iConfig, logger)
	paymentProfileRepo := data.NewPaymentProfileRepo(dataData)
	paymentUseCase, err := biz.NewPaymentUsecase(logger, ovpClient, invoicesRepo, productRepo, subscriptionsRepo, paymentProfileRepo, productReservationRepo, invoicesManager)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	paymentsService := service.NewPaymentsService(paymentUseCase)
	grpcServer := server.NewGRPCServer(bootstrap, iJwtProcessor, iTracer, itemService, productService, invoiceService, subscriptionService, appleStoreService, paymentsService)
	httpServer := server.NewHTTPServer(bootstrap, iJwtProcessor)
	appleStoreReliabilityUseCase := biz.NewAppleStoreReliabilityUseCase(subscriptionsRepo, invoicesRepo, appleStoreClient, jwtParser, logger)
	cronServer := server.NewCronServer(logger, invoicesUseCase, paymentUseCase, appleStoreReliabilityUseCase)
	app := newApp(logger, iConfig, grpcServer, httpServer, cronServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
