// Code generated by ent, DO NOT EDIT.

package product

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/shopspring/decimal"
	"gitlab.calendaria.team/services/finance/invoices/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldID, id))
}

// AppID applies equality check predicate on the "app_id" field. It's identical to AppIDEQ.
func AppID(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldAppID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldDescription, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v decimal.Decimal) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldPrice, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldCurrency, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldIsActive, v))
}

// IsLimited applies equality check predicate on the "is_limited" field. It's identical to IsLimitedEQ.
func IsLimited(v bool) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldIsLimited, v))
}

// LimitedTill applies equality check predicate on the "limited_till" field. It's identical to LimitedTillEQ.
func LimitedTill(v time.Time) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldLimitedTill, v))
}

// Left applies equality check predicate on the "left" field. It's identical to LeftEQ.
func Left(v int64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldLeft, v))
}

// IsUnique applies equality check predicate on the "is_unique" field. It's identical to IsUniqueEQ.
func IsUnique(v bool) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldIsUnique, v))
}

// UniqueLimit applies equality check predicate on the "unique_limit" field. It's identical to UniqueLimitEQ.
func UniqueLimit(v int64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldUniqueLimit, v))
}

// IsExpiring applies equality check predicate on the "is_expiring" field. It's identical to IsExpiringEQ.
func IsExpiring(v bool) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldIsExpiring, v))
}

// RecurrenceRule applies equality check predicate on the "recurrence_rule" field. It's identical to RecurrenceRuleEQ.
func RecurrenceRule(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldRecurrenceRule, v))
}

// OfferInAppleStore applies equality check predicate on the "offer_in_apple_store" field. It's identical to OfferInAppleStoreEQ.
func OfferInAppleStore(v bool) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldOfferInAppleStore, v))
}

// AppIDEQ applies the EQ predicate on the "app_id" field.
func AppIDEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldAppID, v))
}

// AppIDNEQ applies the NEQ predicate on the "app_id" field.
func AppIDNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldAppID, v))
}

// AppIDIn applies the In predicate on the "app_id" field.
func AppIDIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldAppID, vs...))
}

// AppIDNotIn applies the NotIn predicate on the "app_id" field.
func AppIDNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldAppID, vs...))
}

// AppIDGT applies the GT predicate on the "app_id" field.
func AppIDGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldAppID, v))
}

// AppIDGTE applies the GTE predicate on the "app_id" field.
func AppIDGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldAppID, v))
}

// AppIDLT applies the LT predicate on the "app_id" field.
func AppIDLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldAppID, v))
}

// AppIDLTE applies the LTE predicate on the "app_id" field.
func AppIDLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldAppID, v))
}

// AppIDContains applies the Contains predicate on the "app_id" field.
func AppIDContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldAppID, v))
}

// AppIDHasPrefix applies the HasPrefix predicate on the "app_id" field.
func AppIDHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldAppID, v))
}

// AppIDHasSuffix applies the HasSuffix predicate on the "app_id" field.
func AppIDHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldAppID, v))
}

// AppIDEqualFold applies the EqualFold predicate on the "app_id" field.
func AppIDEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldAppID, v))
}

// AppIDContainsFold applies the ContainsFold predicate on the "app_id" field.
func AppIDContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldAppID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldDescription, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v decimal.Decimal) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v decimal.Decimal) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...decimal.Decimal) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...decimal.Decimal) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v decimal.Decimal) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v decimal.Decimal) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v decimal.Decimal) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v decimal.Decimal) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldPrice, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldCurrency, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldIsActive, v))
}

// IsLimitedEQ applies the EQ predicate on the "is_limited" field.
func IsLimitedEQ(v bool) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldIsLimited, v))
}

// IsLimitedNEQ applies the NEQ predicate on the "is_limited" field.
func IsLimitedNEQ(v bool) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldIsLimited, v))
}

// LimitedTillEQ applies the EQ predicate on the "limited_till" field.
func LimitedTillEQ(v time.Time) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldLimitedTill, v))
}

// LimitedTillNEQ applies the NEQ predicate on the "limited_till" field.
func LimitedTillNEQ(v time.Time) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldLimitedTill, v))
}

// LimitedTillIn applies the In predicate on the "limited_till" field.
func LimitedTillIn(vs ...time.Time) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldLimitedTill, vs...))
}

// LimitedTillNotIn applies the NotIn predicate on the "limited_till" field.
func LimitedTillNotIn(vs ...time.Time) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldLimitedTill, vs...))
}

// LimitedTillGT applies the GT predicate on the "limited_till" field.
func LimitedTillGT(v time.Time) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldLimitedTill, v))
}

// LimitedTillGTE applies the GTE predicate on the "limited_till" field.
func LimitedTillGTE(v time.Time) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldLimitedTill, v))
}

// LimitedTillLT applies the LT predicate on the "limited_till" field.
func LimitedTillLT(v time.Time) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldLimitedTill, v))
}

// LimitedTillLTE applies the LTE predicate on the "limited_till" field.
func LimitedTillLTE(v time.Time) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldLimitedTill, v))
}

// LimitedTillIsNil applies the IsNil predicate on the "limited_till" field.
func LimitedTillIsNil() predicate.Product {
	return predicate.Product(sql.FieldIsNull(FieldLimitedTill))
}

// LimitedTillNotNil applies the NotNil predicate on the "limited_till" field.
func LimitedTillNotNil() predicate.Product {
	return predicate.Product(sql.FieldNotNull(FieldLimitedTill))
}

// LeftEQ applies the EQ predicate on the "left" field.
func LeftEQ(v int64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldLeft, v))
}

// LeftNEQ applies the NEQ predicate on the "left" field.
func LeftNEQ(v int64) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldLeft, v))
}

// LeftIn applies the In predicate on the "left" field.
func LeftIn(vs ...int64) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldLeft, vs...))
}

// LeftNotIn applies the NotIn predicate on the "left" field.
func LeftNotIn(vs ...int64) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldLeft, vs...))
}

// LeftGT applies the GT predicate on the "left" field.
func LeftGT(v int64) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldLeft, v))
}

// LeftGTE applies the GTE predicate on the "left" field.
func LeftGTE(v int64) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldLeft, v))
}

// LeftLT applies the LT predicate on the "left" field.
func LeftLT(v int64) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldLeft, v))
}

// LeftLTE applies the LTE predicate on the "left" field.
func LeftLTE(v int64) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldLeft, v))
}

// IsUniqueEQ applies the EQ predicate on the "is_unique" field.
func IsUniqueEQ(v bool) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldIsUnique, v))
}

// IsUniqueNEQ applies the NEQ predicate on the "is_unique" field.
func IsUniqueNEQ(v bool) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldIsUnique, v))
}

// IsUniqueIsNil applies the IsNil predicate on the "is_unique" field.
func IsUniqueIsNil() predicate.Product {
	return predicate.Product(sql.FieldIsNull(FieldIsUnique))
}

// IsUniqueNotNil applies the NotNil predicate on the "is_unique" field.
func IsUniqueNotNil() predicate.Product {
	return predicate.Product(sql.FieldNotNull(FieldIsUnique))
}

// UniqueLimitEQ applies the EQ predicate on the "unique_limit" field.
func UniqueLimitEQ(v int64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldUniqueLimit, v))
}

// UniqueLimitNEQ applies the NEQ predicate on the "unique_limit" field.
func UniqueLimitNEQ(v int64) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldUniqueLimit, v))
}

// UniqueLimitIn applies the In predicate on the "unique_limit" field.
func UniqueLimitIn(vs ...int64) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldUniqueLimit, vs...))
}

// UniqueLimitNotIn applies the NotIn predicate on the "unique_limit" field.
func UniqueLimitNotIn(vs ...int64) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldUniqueLimit, vs...))
}

// UniqueLimitGT applies the GT predicate on the "unique_limit" field.
func UniqueLimitGT(v int64) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldUniqueLimit, v))
}

// UniqueLimitGTE applies the GTE predicate on the "unique_limit" field.
func UniqueLimitGTE(v int64) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldUniqueLimit, v))
}

// UniqueLimitLT applies the LT predicate on the "unique_limit" field.
func UniqueLimitLT(v int64) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldUniqueLimit, v))
}

// UniqueLimitLTE applies the LTE predicate on the "unique_limit" field.
func UniqueLimitLTE(v int64) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldUniqueLimit, v))
}

// IsExpiringEQ applies the EQ predicate on the "is_expiring" field.
func IsExpiringEQ(v bool) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldIsExpiring, v))
}

// IsExpiringNEQ applies the NEQ predicate on the "is_expiring" field.
func IsExpiringNEQ(v bool) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldIsExpiring, v))
}

// IsExpiringIsNil applies the IsNil predicate on the "is_expiring" field.
func IsExpiringIsNil() predicate.Product {
	return predicate.Product(sql.FieldIsNull(FieldIsExpiring))
}

// IsExpiringNotNil applies the NotNil predicate on the "is_expiring" field.
func IsExpiringNotNil() predicate.Product {
	return predicate.Product(sql.FieldNotNull(FieldIsExpiring))
}

// RecurrenceRuleEQ applies the EQ predicate on the "recurrence_rule" field.
func RecurrenceRuleEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldRecurrenceRule, v))
}

// RecurrenceRuleNEQ applies the NEQ predicate on the "recurrence_rule" field.
func RecurrenceRuleNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldRecurrenceRule, v))
}

// RecurrenceRuleIn applies the In predicate on the "recurrence_rule" field.
func RecurrenceRuleIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldRecurrenceRule, vs...))
}

// RecurrenceRuleNotIn applies the NotIn predicate on the "recurrence_rule" field.
func RecurrenceRuleNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldRecurrenceRule, vs...))
}

// RecurrenceRuleGT applies the GT predicate on the "recurrence_rule" field.
func RecurrenceRuleGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldRecurrenceRule, v))
}

// RecurrenceRuleGTE applies the GTE predicate on the "recurrence_rule" field.
func RecurrenceRuleGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldRecurrenceRule, v))
}

// RecurrenceRuleLT applies the LT predicate on the "recurrence_rule" field.
func RecurrenceRuleLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldRecurrenceRule, v))
}

// RecurrenceRuleLTE applies the LTE predicate on the "recurrence_rule" field.
func RecurrenceRuleLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldRecurrenceRule, v))
}

// RecurrenceRuleContains applies the Contains predicate on the "recurrence_rule" field.
func RecurrenceRuleContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldRecurrenceRule, v))
}

// RecurrenceRuleHasPrefix applies the HasPrefix predicate on the "recurrence_rule" field.
func RecurrenceRuleHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldRecurrenceRule, v))
}

// RecurrenceRuleHasSuffix applies the HasSuffix predicate on the "recurrence_rule" field.
func RecurrenceRuleHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldRecurrenceRule, v))
}

// RecurrenceRuleIsNil applies the IsNil predicate on the "recurrence_rule" field.
func RecurrenceRuleIsNil() predicate.Product {
	return predicate.Product(sql.FieldIsNull(FieldRecurrenceRule))
}

// RecurrenceRuleNotNil applies the NotNil predicate on the "recurrence_rule" field.
func RecurrenceRuleNotNil() predicate.Product {
	return predicate.Product(sql.FieldNotNull(FieldRecurrenceRule))
}

// RecurrenceRuleEqualFold applies the EqualFold predicate on the "recurrence_rule" field.
func RecurrenceRuleEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldRecurrenceRule, v))
}

// RecurrenceRuleContainsFold applies the ContainsFold predicate on the "recurrence_rule" field.
func RecurrenceRuleContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldRecurrenceRule, v))
}

// OfferInAppleStoreEQ applies the EQ predicate on the "offer_in_apple_store" field.
func OfferInAppleStoreEQ(v bool) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldOfferInAppleStore, v))
}

// OfferInAppleStoreNEQ applies the NEQ predicate on the "offer_in_apple_store" field.
func OfferInAppleStoreNEQ(v bool) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldOfferInAppleStore, v))
}

// HasInvoices applies the HasEdge predicate on the "invoices" edge.
func HasInvoices() predicate.Product {
	return predicate.Product(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, InvoicesTable, InvoicesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInvoicesWith applies the HasEdge predicate on the "invoices" edge with a given conditions (other predicates).
func HasInvoicesWith(preds ...predicate.Invoice) predicate.Product {
	return predicate.Product(func(s *sql.Selector) {
		step := newInvoicesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSubscriptions applies the HasEdge predicate on the "subscriptions" edge.
func HasSubscriptions() predicate.Product {
	return predicate.Product(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SubscriptionsTable, SubscriptionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubscriptionsWith applies the HasEdge predicate on the "subscriptions" edge with a given conditions (other predicates).
func HasSubscriptionsWith(preds ...predicate.Subscriptions) predicate.Product {
	return predicate.Product(func(s *sql.Selector) {
		step := newSubscriptionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBundles applies the HasEdge predicate on the "bundles" edge.
func HasBundles() predicate.Product {
	return predicate.Product(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BundlesTable, BundlesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBundlesWith applies the HasEdge predicate on the "bundles" edge with a given conditions (other predicates).
func HasBundlesWith(preds ...predicate.Bundle) predicate.Product {
	return predicate.Product(func(s *sql.Selector) {
		step := newBundlesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Product) predicate.Product {
	return predicate.Product(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Product) predicate.Product {
	return predicate.Product(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Product) predicate.Product {
	return predicate.Product(sql.NotPredicates(p))
}
