// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BundlesColumns holds the columns for the "bundles" table.
	BundlesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "amount", Type: field.TypeFloat64, Default: 1},
		{Name: "item_id", Type: field.TypeInt64},
		{Name: "product_id", Type: field.TypeInt64},
	}
	// BundlesTable holds the schema information for the "bundles" table.
	BundlesTable = &schema.Table{
		Name:       "bundles",
		Columns:    BundlesColumns,
		PrimaryKey: []*schema.Column{BundlesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "bundles_items_bundles",
				Columns:    []*schema.Column{BundlesColumns[5]},
				RefColumns: []*schema.Column{ItemsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "bundles_products_bundles",
				Columns:    []*schema.Column{BundlesColumns[6]},
				RefColumns: []*schema.Column{ProductsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ConsumedStatusColumns holds the columns for the "consumed_status" table.
	ConsumedStatusColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "tenant_id", Type: field.TypeInt64},
		{Name: "app_id", Type: field.TypeInt64},
		{Name: "consumed", Type: field.TypeFloat64, Nullable: true, Default: 0},
		{Name: "left", Type: field.TypeFloat64, Nullable: true, Default: 0},
		{Name: "active_till", Type: field.TypeTime, Nullable: true},
		{Name: "start_from", Type: field.TypeTime, Nullable: true},
		{Name: "invoice_consumed_statuses", Type: field.TypeInt64, Nullable: true},
		{Name: "item_id", Type: field.TypeInt64},
	}
	// ConsumedStatusTable holds the schema information for the "consumed_status" table.
	ConsumedStatusTable = &schema.Table{
		Name:       "consumed_status",
		Columns:    ConsumedStatusColumns,
		PrimaryKey: []*schema.Column{ConsumedStatusColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "consumed_status_invoices_consumed_statuses",
				Columns:    []*schema.Column{ConsumedStatusColumns[8]},
				RefColumns: []*schema.Column{InvoicesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "consumed_status_items_consumed_statuses",
				Columns:    []*schema.Column{ConsumedStatusColumns[9]},
				RefColumns: []*schema.Column{ItemsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "consumedstatus_user_id_app_id_item_id",
				Unique:  false,
				Columns: []*schema.Column{ConsumedStatusColumns[1], ConsumedStatusColumns[3], ConsumedStatusColumns[9]},
			},
		},
	}
	// InvoicesColumns holds the columns for the "invoices" table.
	InvoicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "app_id", Type: field.TypeString},
		{Name: "amount", Type: field.TypeInt64},
		{Name: "price", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "currency", Type: field.TypeString, Size: 3, Default: "KZT"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"CREATED", "PAID", "CANCELED_BY_USER", "CANCELED_BY_VENDOR", "FAILED", "REJECTED", "REFUNDED"}, Default: "CREATED"},
		{Name: "paid_at", Type: field.TypeTime, Nullable: true},
		{Name: "product_id", Type: field.TypeInt64},
	}
	// InvoicesTable holds the schema information for the "invoices" table.
	InvoicesTable = &schema.Table{
		Name:       "invoices",
		Columns:    InvoicesColumns,
		PrimaryKey: []*schema.Column{InvoicesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "invoices_products_invoices",
				Columns:    []*schema.Column{InvoicesColumns[8]},
				RefColumns: []*schema.Column{ProductsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ItemsColumns holds the columns for the "items" table.
	ItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
	}
	// ItemsTable holds the schema information for the "items" table.
	ItemsTable = &schema.Table{
		Name:       "items",
		Columns:    ItemsColumns,
		PrimaryKey: []*schema.Column{ItemsColumns[0]},
	}
	// ProductsColumns holds the columns for the "products" table.
	ProductsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "price", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "currency", Type: field.TypeString, Size: 3, Default: "KZT"},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "is_limited", Type: field.TypeBool, Default: false},
		{Name: "limited_till", Type: field.TypeTime, Nullable: true},
		{Name: "left", Type: field.TypeInt64, Default: 0},
		{Name: "is_unique", Type: field.TypeBool, Nullable: true, Default: false},
		{Name: "unique_limit", Type: field.TypeInt64, Default: 0},
	}
	// ProductsTable holds the schema information for the "products" table.
	ProductsTable = &schema.Table{
		Name:       "products",
		Columns:    ProductsColumns,
		PrimaryKey: []*schema.Column{ProductsColumns[0]},
	}
	// SubscriptionStatusColumns holds the columns for the "subscription_status" table.
	SubscriptionStatusColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "active_till", Type: field.TypeTime, Nullable: true},
		{Name: "start_from", Type: field.TypeTime, Nullable: true},
		{Name: "invoice_id", Type: field.TypeInt64},
		{Name: "item_id", Type: field.TypeInt64},
	}
	// SubscriptionStatusTable holds the schema information for the "subscription_status" table.
	SubscriptionStatusTable = &schema.Table{
		Name:       "subscription_status",
		Columns:    SubscriptionStatusColumns,
		PrimaryKey: []*schema.Column{SubscriptionStatusColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "subscription_status_invoices_subscription_statuses",
				Columns:    []*schema.Column{SubscriptionStatusColumns[3]},
				RefColumns: []*schema.Column{InvoicesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "subscription_status_items_subscription_statuses",
				Columns:    []*schema.Column{SubscriptionStatusColumns[4]},
				RefColumns: []*schema.Column{ItemsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BundlesTable,
		ConsumedStatusTable,
		InvoicesTable,
		ItemsTable,
		ProductsTable,
		SubscriptionStatusTable,
	}
)

func init() {
	BundlesTable.ForeignKeys[0].RefTable = ItemsTable
	BundlesTable.ForeignKeys[1].RefTable = ProductsTable
	ConsumedStatusTable.ForeignKeys[0].RefTable = InvoicesTable
	ConsumedStatusTable.ForeignKeys[1].RefTable = ItemsTable
	InvoicesTable.ForeignKeys[0].RefTable = ProductsTable
	SubscriptionStatusTable.ForeignKeys[0].RefTable = InvoicesTable
	SubscriptionStatusTable.ForeignKeys[1].RefTable = ItemsTable
}
