// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"gitlab.calendaria.team/services/finance/invoices/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"gitlab.calendaria.team/services/finance/invoices/ent/bundle"
	"gitlab.calendaria.team/services/finance/invoices/ent/consumedstatus"
	"gitlab.calendaria.team/services/finance/invoices/ent/invoice"
	"gitlab.calendaria.team/services/finance/invoices/ent/item"
	"gitlab.calendaria.team/services/finance/invoices/ent/product"
	"gitlab.calendaria.team/services/finance/invoices/ent/subscriptionstatus"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Bundle is the client for interacting with the Bundle builders.
	Bundle *BundleClient
	// ConsumedStatus is the client for interacting with the ConsumedStatus builders.
	ConsumedStatus *ConsumedStatusClient
	// Invoice is the client for interacting with the Invoice builders.
	Invoice *InvoiceClient
	// Item is the client for interacting with the Item builders.
	Item *ItemClient
	// Product is the client for interacting with the Product builders.
	Product *ProductClient
	// SubscriptionStatus is the client for interacting with the SubscriptionStatus builders.
	SubscriptionStatus *SubscriptionStatusClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Bundle = NewBundleClient(c.config)
	c.ConsumedStatus = NewConsumedStatusClient(c.config)
	c.Invoice = NewInvoiceClient(c.config)
	c.Item = NewItemClient(c.config)
	c.Product = NewProductClient(c.config)
	c.SubscriptionStatus = NewSubscriptionStatusClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		Bundle:             NewBundleClient(cfg),
		ConsumedStatus:     NewConsumedStatusClient(cfg),
		Invoice:            NewInvoiceClient(cfg),
		Item:               NewItemClient(cfg),
		Product:            NewProductClient(cfg),
		SubscriptionStatus: NewSubscriptionStatusClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		Bundle:             NewBundleClient(cfg),
		ConsumedStatus:     NewConsumedStatusClient(cfg),
		Invoice:            NewInvoiceClient(cfg),
		Item:               NewItemClient(cfg),
		Product:            NewProductClient(cfg),
		SubscriptionStatus: NewSubscriptionStatusClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Bundle.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Bundle, c.ConsumedStatus, c.Invoice, c.Item, c.Product, c.SubscriptionStatus,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Bundle, c.ConsumedStatus, c.Invoice, c.Item, c.Product, c.SubscriptionStatus,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *BundleMutation:
		return c.Bundle.mutate(ctx, m)
	case *ConsumedStatusMutation:
		return c.ConsumedStatus.mutate(ctx, m)
	case *InvoiceMutation:
		return c.Invoice.mutate(ctx, m)
	case *ItemMutation:
		return c.Item.mutate(ctx, m)
	case *ProductMutation:
		return c.Product.mutate(ctx, m)
	case *SubscriptionStatusMutation:
		return c.SubscriptionStatus.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// BundleClient is a client for the Bundle schema.
type BundleClient struct {
	config
}

// NewBundleClient returns a client for the Bundle from the given config.
func NewBundleClient(c config) *BundleClient {
	return &BundleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `bundle.Hooks(f(g(h())))`.
func (c *BundleClient) Use(hooks ...Hook) {
	c.hooks.Bundle = append(c.hooks.Bundle, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `bundle.Intercept(f(g(h())))`.
func (c *BundleClient) Intercept(interceptors ...Interceptor) {
	c.inters.Bundle = append(c.inters.Bundle, interceptors...)
}

// Create returns a builder for creating a Bundle entity.
func (c *BundleClient) Create() *BundleCreate {
	mutation := newBundleMutation(c.config, OpCreate)
	return &BundleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Bundle entities.
func (c *BundleClient) CreateBulk(builders ...*BundleCreate) *BundleCreateBulk {
	return &BundleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BundleClient) MapCreateBulk(slice any, setFunc func(*BundleCreate, int)) *BundleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BundleCreateBulk{err: fmt.Errorf("calling to BundleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BundleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BundleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Bundle.
func (c *BundleClient) Update() *BundleUpdate {
	mutation := newBundleMutation(c.config, OpUpdate)
	return &BundleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BundleClient) UpdateOne(b *Bundle) *BundleUpdateOne {
	mutation := newBundleMutation(c.config, OpUpdateOne, withBundle(b))
	return &BundleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BundleClient) UpdateOneID(id int64) *BundleUpdateOne {
	mutation := newBundleMutation(c.config, OpUpdateOne, withBundleID(id))
	return &BundleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Bundle.
func (c *BundleClient) Delete() *BundleDelete {
	mutation := newBundleMutation(c.config, OpDelete)
	return &BundleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BundleClient) DeleteOne(b *Bundle) *BundleDeleteOne {
	return c.DeleteOneID(b.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BundleClient) DeleteOneID(id int64) *BundleDeleteOne {
	builder := c.Delete().Where(bundle.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BundleDeleteOne{builder}
}

// Query returns a query builder for Bundle.
func (c *BundleClient) Query() *BundleQuery {
	return &BundleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBundle},
		inters: c.Interceptors(),
	}
}

// Get returns a Bundle entity by its id.
func (c *BundleClient) Get(ctx context.Context, id int64) (*Bundle, error) {
	return c.Query().Where(bundle.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BundleClient) GetX(ctx context.Context, id int64) *Bundle {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryProduct queries the product edge of a Bundle.
func (c *BundleClient) QueryProduct(b *Bundle) *ProductQuery {
	query := (&ProductClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := b.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(bundle.Table, bundle.FieldID, id),
			sqlgraph.To(product.Table, product.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, bundle.ProductTable, bundle.ProductColumn),
		)
		fromV = sqlgraph.Neighbors(b.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryItem queries the item edge of a Bundle.
func (c *BundleClient) QueryItem(b *Bundle) *ItemQuery {
	query := (&ItemClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := b.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(bundle.Table, bundle.FieldID, id),
			sqlgraph.To(item.Table, item.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, bundle.ItemTable, bundle.ItemColumn),
		)
		fromV = sqlgraph.Neighbors(b.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *BundleClient) Hooks() []Hook {
	hooks := c.hooks.Bundle
	return append(hooks[:len(hooks):len(hooks)], bundle.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *BundleClient) Interceptors() []Interceptor {
	inters := c.inters.Bundle
	return append(inters[:len(inters):len(inters)], bundle.Interceptors[:]...)
}

func (c *BundleClient) mutate(ctx context.Context, m *BundleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BundleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BundleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BundleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BundleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Bundle mutation op: %q", m.Op())
	}
}

// ConsumedStatusClient is a client for the ConsumedStatus schema.
type ConsumedStatusClient struct {
	config
}

// NewConsumedStatusClient returns a client for the ConsumedStatus from the given config.
func NewConsumedStatusClient(c config) *ConsumedStatusClient {
	return &ConsumedStatusClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `consumedstatus.Hooks(f(g(h())))`.
func (c *ConsumedStatusClient) Use(hooks ...Hook) {
	c.hooks.ConsumedStatus = append(c.hooks.ConsumedStatus, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `consumedstatus.Intercept(f(g(h())))`.
func (c *ConsumedStatusClient) Intercept(interceptors ...Interceptor) {
	c.inters.ConsumedStatus = append(c.inters.ConsumedStatus, interceptors...)
}

// Create returns a builder for creating a ConsumedStatus entity.
func (c *ConsumedStatusClient) Create() *ConsumedStatusCreate {
	mutation := newConsumedStatusMutation(c.config, OpCreate)
	return &ConsumedStatusCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ConsumedStatus entities.
func (c *ConsumedStatusClient) CreateBulk(builders ...*ConsumedStatusCreate) *ConsumedStatusCreateBulk {
	return &ConsumedStatusCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ConsumedStatusClient) MapCreateBulk(slice any, setFunc func(*ConsumedStatusCreate, int)) *ConsumedStatusCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ConsumedStatusCreateBulk{err: fmt.Errorf("calling to ConsumedStatusClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ConsumedStatusCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ConsumedStatusCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ConsumedStatus.
func (c *ConsumedStatusClient) Update() *ConsumedStatusUpdate {
	mutation := newConsumedStatusMutation(c.config, OpUpdate)
	return &ConsumedStatusUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ConsumedStatusClient) UpdateOne(cs *ConsumedStatus) *ConsumedStatusUpdateOne {
	mutation := newConsumedStatusMutation(c.config, OpUpdateOne, withConsumedStatus(cs))
	return &ConsumedStatusUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ConsumedStatusClient) UpdateOneID(id int64) *ConsumedStatusUpdateOne {
	mutation := newConsumedStatusMutation(c.config, OpUpdateOne, withConsumedStatusID(id))
	return &ConsumedStatusUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ConsumedStatus.
func (c *ConsumedStatusClient) Delete() *ConsumedStatusDelete {
	mutation := newConsumedStatusMutation(c.config, OpDelete)
	return &ConsumedStatusDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ConsumedStatusClient) DeleteOne(cs *ConsumedStatus) *ConsumedStatusDeleteOne {
	return c.DeleteOneID(cs.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ConsumedStatusClient) DeleteOneID(id int64) *ConsumedStatusDeleteOne {
	builder := c.Delete().Where(consumedstatus.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ConsumedStatusDeleteOne{builder}
}

// Query returns a query builder for ConsumedStatus.
func (c *ConsumedStatusClient) Query() *ConsumedStatusQuery {
	return &ConsumedStatusQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeConsumedStatus},
		inters: c.Interceptors(),
	}
}

// Get returns a ConsumedStatus entity by its id.
func (c *ConsumedStatusClient) Get(ctx context.Context, id int64) (*ConsumedStatus, error) {
	return c.Query().Where(consumedstatus.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ConsumedStatusClient) GetX(ctx context.Context, id int64) *ConsumedStatus {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryItem queries the item edge of a ConsumedStatus.
func (c *ConsumedStatusClient) QueryItem(cs *ConsumedStatus) *ItemQuery {
	query := (&ItemClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := cs.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(consumedstatus.Table, consumedstatus.FieldID, id),
			sqlgraph.To(item.Table, item.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, consumedstatus.ItemTable, consumedstatus.ItemColumn),
		)
		fromV = sqlgraph.Neighbors(cs.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ConsumedStatusClient) Hooks() []Hook {
	return c.hooks.ConsumedStatus
}

// Interceptors returns the client interceptors.
func (c *ConsumedStatusClient) Interceptors() []Interceptor {
	return c.inters.ConsumedStatus
}

func (c *ConsumedStatusClient) mutate(ctx context.Context, m *ConsumedStatusMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ConsumedStatusCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ConsumedStatusUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ConsumedStatusUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ConsumedStatusDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ConsumedStatus mutation op: %q", m.Op())
	}
}

// InvoiceClient is a client for the Invoice schema.
type InvoiceClient struct {
	config
}

// NewInvoiceClient returns a client for the Invoice from the given config.
func NewInvoiceClient(c config) *InvoiceClient {
	return &InvoiceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `invoice.Hooks(f(g(h())))`.
func (c *InvoiceClient) Use(hooks ...Hook) {
	c.hooks.Invoice = append(c.hooks.Invoice, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `invoice.Intercept(f(g(h())))`.
func (c *InvoiceClient) Intercept(interceptors ...Interceptor) {
	c.inters.Invoice = append(c.inters.Invoice, interceptors...)
}

// Create returns a builder for creating a Invoice entity.
func (c *InvoiceClient) Create() *InvoiceCreate {
	mutation := newInvoiceMutation(c.config, OpCreate)
	return &InvoiceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Invoice entities.
func (c *InvoiceClient) CreateBulk(builders ...*InvoiceCreate) *InvoiceCreateBulk {
	return &InvoiceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *InvoiceClient) MapCreateBulk(slice any, setFunc func(*InvoiceCreate, int)) *InvoiceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &InvoiceCreateBulk{err: fmt.Errorf("calling to InvoiceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*InvoiceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &InvoiceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Invoice.
func (c *InvoiceClient) Update() *InvoiceUpdate {
	mutation := newInvoiceMutation(c.config, OpUpdate)
	return &InvoiceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *InvoiceClient) UpdateOne(i *Invoice) *InvoiceUpdateOne {
	mutation := newInvoiceMutation(c.config, OpUpdateOne, withInvoice(i))
	return &InvoiceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *InvoiceClient) UpdateOneID(id int64) *InvoiceUpdateOne {
	mutation := newInvoiceMutation(c.config, OpUpdateOne, withInvoiceID(id))
	return &InvoiceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Invoice.
func (c *InvoiceClient) Delete() *InvoiceDelete {
	mutation := newInvoiceMutation(c.config, OpDelete)
	return &InvoiceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *InvoiceClient) DeleteOne(i *Invoice) *InvoiceDeleteOne {
	return c.DeleteOneID(i.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *InvoiceClient) DeleteOneID(id int64) *InvoiceDeleteOne {
	builder := c.Delete().Where(invoice.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &InvoiceDeleteOne{builder}
}

// Query returns a query builder for Invoice.
func (c *InvoiceClient) Query() *InvoiceQuery {
	return &InvoiceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeInvoice},
		inters: c.Interceptors(),
	}
}

// Get returns a Invoice entity by its id.
func (c *InvoiceClient) Get(ctx context.Context, id int64) (*Invoice, error) {
	return c.Query().Where(invoice.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *InvoiceClient) GetX(ctx context.Context, id int64) *Invoice {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryProduct queries the product edge of a Invoice.
func (c *InvoiceClient) QueryProduct(i *Invoice) *ProductQuery {
	query := (&ProductClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := i.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(invoice.Table, invoice.FieldID, id),
			sqlgraph.To(product.Table, product.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, invoice.ProductTable, invoice.ProductColumn),
		)
		fromV = sqlgraph.Neighbors(i.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryConsumedStatuses queries the consumed_statuses edge of a Invoice.
func (c *InvoiceClient) QueryConsumedStatuses(i *Invoice) *ConsumedStatusQuery {
	query := (&ConsumedStatusClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := i.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(invoice.Table, invoice.FieldID, id),
			sqlgraph.To(consumedstatus.Table, consumedstatus.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, invoice.ConsumedStatusesTable, invoice.ConsumedStatusesColumn),
		)
		fromV = sqlgraph.Neighbors(i.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySubscriptionStatuses queries the subscription_statuses edge of a Invoice.
func (c *InvoiceClient) QuerySubscriptionStatuses(i *Invoice) *SubscriptionStatusQuery {
	query := (&SubscriptionStatusClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := i.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(invoice.Table, invoice.FieldID, id),
			sqlgraph.To(subscriptionstatus.Table, subscriptionstatus.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, invoice.SubscriptionStatusesTable, invoice.SubscriptionStatusesColumn),
		)
		fromV = sqlgraph.Neighbors(i.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *InvoiceClient) Hooks() []Hook {
	return c.hooks.Invoice
}

// Interceptors returns the client interceptors.
func (c *InvoiceClient) Interceptors() []Interceptor {
	return c.inters.Invoice
}

func (c *InvoiceClient) mutate(ctx context.Context, m *InvoiceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&InvoiceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&InvoiceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&InvoiceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&InvoiceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Invoice mutation op: %q", m.Op())
	}
}

// ItemClient is a client for the Item schema.
type ItemClient struct {
	config
}

// NewItemClient returns a client for the Item from the given config.
func NewItemClient(c config) *ItemClient {
	return &ItemClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `item.Hooks(f(g(h())))`.
func (c *ItemClient) Use(hooks ...Hook) {
	c.hooks.Item = append(c.hooks.Item, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `item.Intercept(f(g(h())))`.
func (c *ItemClient) Intercept(interceptors ...Interceptor) {
	c.inters.Item = append(c.inters.Item, interceptors...)
}

// Create returns a builder for creating a Item entity.
func (c *ItemClient) Create() *ItemCreate {
	mutation := newItemMutation(c.config, OpCreate)
	return &ItemCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Item entities.
func (c *ItemClient) CreateBulk(builders ...*ItemCreate) *ItemCreateBulk {
	return &ItemCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ItemClient) MapCreateBulk(slice any, setFunc func(*ItemCreate, int)) *ItemCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ItemCreateBulk{err: fmt.Errorf("calling to ItemClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ItemCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ItemCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Item.
func (c *ItemClient) Update() *ItemUpdate {
	mutation := newItemMutation(c.config, OpUpdate)
	return &ItemUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ItemClient) UpdateOne(i *Item) *ItemUpdateOne {
	mutation := newItemMutation(c.config, OpUpdateOne, withItem(i))
	return &ItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ItemClient) UpdateOneID(id int64) *ItemUpdateOne {
	mutation := newItemMutation(c.config, OpUpdateOne, withItemID(id))
	return &ItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Item.
func (c *ItemClient) Delete() *ItemDelete {
	mutation := newItemMutation(c.config, OpDelete)
	return &ItemDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ItemClient) DeleteOne(i *Item) *ItemDeleteOne {
	return c.DeleteOneID(i.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ItemClient) DeleteOneID(id int64) *ItemDeleteOne {
	builder := c.Delete().Where(item.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ItemDeleteOne{builder}
}

// Query returns a query builder for Item.
func (c *ItemClient) Query() *ItemQuery {
	return &ItemQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeItem},
		inters: c.Interceptors(),
	}
}

// Get returns a Item entity by its id.
func (c *ItemClient) Get(ctx context.Context, id int64) (*Item, error) {
	return c.Query().Where(item.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ItemClient) GetX(ctx context.Context, id int64) *Item {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryBundles queries the bundles edge of a Item.
func (c *ItemClient) QueryBundles(i *Item) *BundleQuery {
	query := (&BundleClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := i.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(item.Table, item.FieldID, id),
			sqlgraph.To(bundle.Table, bundle.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, item.BundlesTable, item.BundlesColumn),
		)
		fromV = sqlgraph.Neighbors(i.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryConsumedStatuses queries the consumed_statuses edge of a Item.
func (c *ItemClient) QueryConsumedStatuses(i *Item) *ConsumedStatusQuery {
	query := (&ConsumedStatusClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := i.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(item.Table, item.FieldID, id),
			sqlgraph.To(consumedstatus.Table, consumedstatus.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, item.ConsumedStatusesTable, item.ConsumedStatusesColumn),
		)
		fromV = sqlgraph.Neighbors(i.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySubscriptionStatuses queries the subscription_statuses edge of a Item.
func (c *ItemClient) QuerySubscriptionStatuses(i *Item) *SubscriptionStatusQuery {
	query := (&SubscriptionStatusClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := i.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(item.Table, item.FieldID, id),
			sqlgraph.To(subscriptionstatus.Table, subscriptionstatus.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, item.SubscriptionStatusesTable, item.SubscriptionStatusesColumn),
		)
		fromV = sqlgraph.Neighbors(i.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ItemClient) Hooks() []Hook {
	hooks := c.hooks.Item
	return append(hooks[:len(hooks):len(hooks)], item.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *ItemClient) Interceptors() []Interceptor {
	inters := c.inters.Item
	return append(inters[:len(inters):len(inters)], item.Interceptors[:]...)
}

func (c *ItemClient) mutate(ctx context.Context, m *ItemMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ItemCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ItemUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ItemDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Item mutation op: %q", m.Op())
	}
}

// ProductClient is a client for the Product schema.
type ProductClient struct {
	config
}

// NewProductClient returns a client for the Product from the given config.
func NewProductClient(c config) *ProductClient {
	return &ProductClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `product.Hooks(f(g(h())))`.
func (c *ProductClient) Use(hooks ...Hook) {
	c.hooks.Product = append(c.hooks.Product, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `product.Intercept(f(g(h())))`.
func (c *ProductClient) Intercept(interceptors ...Interceptor) {
	c.inters.Product = append(c.inters.Product, interceptors...)
}

// Create returns a builder for creating a Product entity.
func (c *ProductClient) Create() *ProductCreate {
	mutation := newProductMutation(c.config, OpCreate)
	return &ProductCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Product entities.
func (c *ProductClient) CreateBulk(builders ...*ProductCreate) *ProductCreateBulk {
	return &ProductCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ProductClient) MapCreateBulk(slice any, setFunc func(*ProductCreate, int)) *ProductCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ProductCreateBulk{err: fmt.Errorf("calling to ProductClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ProductCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ProductCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Product.
func (c *ProductClient) Update() *ProductUpdate {
	mutation := newProductMutation(c.config, OpUpdate)
	return &ProductUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ProductClient) UpdateOne(pr *Product) *ProductUpdateOne {
	mutation := newProductMutation(c.config, OpUpdateOne, withProduct(pr))
	return &ProductUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ProductClient) UpdateOneID(id int64) *ProductUpdateOne {
	mutation := newProductMutation(c.config, OpUpdateOne, withProductID(id))
	return &ProductUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Product.
func (c *ProductClient) Delete() *ProductDelete {
	mutation := newProductMutation(c.config, OpDelete)
	return &ProductDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ProductClient) DeleteOne(pr *Product) *ProductDeleteOne {
	return c.DeleteOneID(pr.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ProductClient) DeleteOneID(id int64) *ProductDeleteOne {
	builder := c.Delete().Where(product.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ProductDeleteOne{builder}
}

// Query returns a query builder for Product.
func (c *ProductClient) Query() *ProductQuery {
	return &ProductQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeProduct},
		inters: c.Interceptors(),
	}
}

// Get returns a Product entity by its id.
func (c *ProductClient) Get(ctx context.Context, id int64) (*Product, error) {
	return c.Query().Where(product.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ProductClient) GetX(ctx context.Context, id int64) *Product {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryInvoices queries the invoices edge of a Product.
func (c *ProductClient) QueryInvoices(pr *Product) *InvoiceQuery {
	query := (&InvoiceClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := pr.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(product.Table, product.FieldID, id),
			sqlgraph.To(invoice.Table, invoice.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, product.InvoicesTable, product.InvoicesColumn),
		)
		fromV = sqlgraph.Neighbors(pr.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryBundles queries the bundles edge of a Product.
func (c *ProductClient) QueryBundles(pr *Product) *BundleQuery {
	query := (&BundleClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := pr.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(product.Table, product.FieldID, id),
			sqlgraph.To(bundle.Table, bundle.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, product.BundlesTable, product.BundlesColumn),
		)
		fromV = sqlgraph.Neighbors(pr.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ProductClient) Hooks() []Hook {
	return c.hooks.Product
}

// Interceptors returns the client interceptors.
func (c *ProductClient) Interceptors() []Interceptor {
	return c.inters.Product
}

func (c *ProductClient) mutate(ctx context.Context, m *ProductMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ProductCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ProductUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ProductUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ProductDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Product mutation op: %q", m.Op())
	}
}

// SubscriptionStatusClient is a client for the SubscriptionStatus schema.
type SubscriptionStatusClient struct {
	config
}

// NewSubscriptionStatusClient returns a client for the SubscriptionStatus from the given config.
func NewSubscriptionStatusClient(c config) *SubscriptionStatusClient {
	return &SubscriptionStatusClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `subscriptionstatus.Hooks(f(g(h())))`.
func (c *SubscriptionStatusClient) Use(hooks ...Hook) {
	c.hooks.SubscriptionStatus = append(c.hooks.SubscriptionStatus, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `subscriptionstatus.Intercept(f(g(h())))`.
func (c *SubscriptionStatusClient) Intercept(interceptors ...Interceptor) {
	c.inters.SubscriptionStatus = append(c.inters.SubscriptionStatus, interceptors...)
}

// Create returns a builder for creating a SubscriptionStatus entity.
func (c *SubscriptionStatusClient) Create() *SubscriptionStatusCreate {
	mutation := newSubscriptionStatusMutation(c.config, OpCreate)
	return &SubscriptionStatusCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SubscriptionStatus entities.
func (c *SubscriptionStatusClient) CreateBulk(builders ...*SubscriptionStatusCreate) *SubscriptionStatusCreateBulk {
	return &SubscriptionStatusCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SubscriptionStatusClient) MapCreateBulk(slice any, setFunc func(*SubscriptionStatusCreate, int)) *SubscriptionStatusCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SubscriptionStatusCreateBulk{err: fmt.Errorf("calling to SubscriptionStatusClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SubscriptionStatusCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SubscriptionStatusCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SubscriptionStatus.
func (c *SubscriptionStatusClient) Update() *SubscriptionStatusUpdate {
	mutation := newSubscriptionStatusMutation(c.config, OpUpdate)
	return &SubscriptionStatusUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SubscriptionStatusClient) UpdateOne(ss *SubscriptionStatus) *SubscriptionStatusUpdateOne {
	mutation := newSubscriptionStatusMutation(c.config, OpUpdateOne, withSubscriptionStatus(ss))
	return &SubscriptionStatusUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SubscriptionStatusClient) UpdateOneID(id int64) *SubscriptionStatusUpdateOne {
	mutation := newSubscriptionStatusMutation(c.config, OpUpdateOne, withSubscriptionStatusID(id))
	return &SubscriptionStatusUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SubscriptionStatus.
func (c *SubscriptionStatusClient) Delete() *SubscriptionStatusDelete {
	mutation := newSubscriptionStatusMutation(c.config, OpDelete)
	return &SubscriptionStatusDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SubscriptionStatusClient) DeleteOne(ss *SubscriptionStatus) *SubscriptionStatusDeleteOne {
	return c.DeleteOneID(ss.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SubscriptionStatusClient) DeleteOneID(id int64) *SubscriptionStatusDeleteOne {
	builder := c.Delete().Where(subscriptionstatus.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SubscriptionStatusDeleteOne{builder}
}

// Query returns a query builder for SubscriptionStatus.
func (c *SubscriptionStatusClient) Query() *SubscriptionStatusQuery {
	return &SubscriptionStatusQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSubscriptionStatus},
		inters: c.Interceptors(),
	}
}

// Get returns a SubscriptionStatus entity by its id.
func (c *SubscriptionStatusClient) Get(ctx context.Context, id int64) (*SubscriptionStatus, error) {
	return c.Query().Where(subscriptionstatus.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SubscriptionStatusClient) GetX(ctx context.Context, id int64) *SubscriptionStatus {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryInvoice queries the invoice edge of a SubscriptionStatus.
func (c *SubscriptionStatusClient) QueryInvoice(ss *SubscriptionStatus) *InvoiceQuery {
	query := (&InvoiceClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := ss.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(subscriptionstatus.Table, subscriptionstatus.FieldID, id),
			sqlgraph.To(invoice.Table, invoice.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, subscriptionstatus.InvoiceTable, subscriptionstatus.InvoiceColumn),
		)
		fromV = sqlgraph.Neighbors(ss.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryItem queries the item edge of a SubscriptionStatus.
func (c *SubscriptionStatusClient) QueryItem(ss *SubscriptionStatus) *ItemQuery {
	query := (&ItemClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := ss.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(subscriptionstatus.Table, subscriptionstatus.FieldID, id),
			sqlgraph.To(item.Table, item.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, subscriptionstatus.ItemTable, subscriptionstatus.ItemColumn),
		)
		fromV = sqlgraph.Neighbors(ss.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SubscriptionStatusClient) Hooks() []Hook {
	return c.hooks.SubscriptionStatus
}

// Interceptors returns the client interceptors.
func (c *SubscriptionStatusClient) Interceptors() []Interceptor {
	return c.inters.SubscriptionStatus
}

func (c *SubscriptionStatusClient) mutate(ctx context.Context, m *SubscriptionStatusMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SubscriptionStatusCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SubscriptionStatusUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SubscriptionStatusUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SubscriptionStatusDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SubscriptionStatus mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Bundle, ConsumedStatus, Invoice, Item, Product, SubscriptionStatus []ent.Hook
	}
	inters struct {
		Bundle, ConsumedStatus, Invoice, Item, Product,
		SubscriptionStatus []ent.Interceptor
	}
)
