// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/finance/invoices/ent/consumedstatus"
	"gitlab.calendaria.team/services/finance/invoices/ent/predicate"
)

// ConsumedStatusUpdate is the builder for updating ConsumedStatus entities.
type ConsumedStatusUpdate struct {
	config
	hooks     []Hook
	mutation  *ConsumedStatusMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ConsumedStatusUpdate builder.
func (csu *ConsumedStatusUpdate) Where(ps ...predicate.ConsumedStatus) *ConsumedStatusUpdate {
	csu.mutation.Where(ps...)
	return csu
}

// SetConsumed sets the "consumed" field.
func (csu *ConsumedStatusUpdate) SetConsumed(f float64) *ConsumedStatusUpdate {
	csu.mutation.ResetConsumed()
	csu.mutation.SetConsumed(f)
	return csu
}

// SetNillableConsumed sets the "consumed" field if the given value is not nil.
func (csu *ConsumedStatusUpdate) SetNillableConsumed(f *float64) *ConsumedStatusUpdate {
	if f != nil {
		csu.SetConsumed(*f)
	}
	return csu
}

// AddConsumed adds f to the "consumed" field.
func (csu *ConsumedStatusUpdate) AddConsumed(f float64) *ConsumedStatusUpdate {
	csu.mutation.AddConsumed(f)
	return csu
}

// ClearConsumed clears the value of the "consumed" field.
func (csu *ConsumedStatusUpdate) ClearConsumed() *ConsumedStatusUpdate {
	csu.mutation.ClearConsumed()
	return csu
}

// SetLeft sets the "left" field.
func (csu *ConsumedStatusUpdate) SetLeft(f float64) *ConsumedStatusUpdate {
	csu.mutation.ResetLeft()
	csu.mutation.SetLeft(f)
	return csu
}

// SetNillableLeft sets the "left" field if the given value is not nil.
func (csu *ConsumedStatusUpdate) SetNillableLeft(f *float64) *ConsumedStatusUpdate {
	if f != nil {
		csu.SetLeft(*f)
	}
	return csu
}

// AddLeft adds f to the "left" field.
func (csu *ConsumedStatusUpdate) AddLeft(f float64) *ConsumedStatusUpdate {
	csu.mutation.AddLeft(f)
	return csu
}

// ClearLeft clears the value of the "left" field.
func (csu *ConsumedStatusUpdate) ClearLeft() *ConsumedStatusUpdate {
	csu.mutation.ClearLeft()
	return csu
}

// SetActiveTill sets the "active_till" field.
func (csu *ConsumedStatusUpdate) SetActiveTill(t time.Time) *ConsumedStatusUpdate {
	csu.mutation.SetActiveTill(t)
	return csu
}

// SetNillableActiveTill sets the "active_till" field if the given value is not nil.
func (csu *ConsumedStatusUpdate) SetNillableActiveTill(t *time.Time) *ConsumedStatusUpdate {
	if t != nil {
		csu.SetActiveTill(*t)
	}
	return csu
}

// ClearActiveTill clears the value of the "active_till" field.
func (csu *ConsumedStatusUpdate) ClearActiveTill() *ConsumedStatusUpdate {
	csu.mutation.ClearActiveTill()
	return csu
}

// SetStartFrom sets the "start_from" field.
func (csu *ConsumedStatusUpdate) SetStartFrom(t time.Time) *ConsumedStatusUpdate {
	csu.mutation.SetStartFrom(t)
	return csu
}

// SetNillableStartFrom sets the "start_from" field if the given value is not nil.
func (csu *ConsumedStatusUpdate) SetNillableStartFrom(t *time.Time) *ConsumedStatusUpdate {
	if t != nil {
		csu.SetStartFrom(*t)
	}
	return csu
}

// ClearStartFrom clears the value of the "start_from" field.
func (csu *ConsumedStatusUpdate) ClearStartFrom() *ConsumedStatusUpdate {
	csu.mutation.ClearStartFrom()
	return csu
}

// Mutation returns the ConsumedStatusMutation object of the builder.
func (csu *ConsumedStatusUpdate) Mutation() *ConsumedStatusMutation {
	return csu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (csu *ConsumedStatusUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, csu.sqlSave, csu.mutation, csu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (csu *ConsumedStatusUpdate) SaveX(ctx context.Context) int {
	affected, err := csu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (csu *ConsumedStatusUpdate) Exec(ctx context.Context) error {
	_, err := csu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (csu *ConsumedStatusUpdate) ExecX(ctx context.Context) {
	if err := csu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (csu *ConsumedStatusUpdate) check() error {
	if csu.mutation.ItemCleared() && len(csu.mutation.ItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ConsumedStatus.item"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (csu *ConsumedStatusUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ConsumedStatusUpdate {
	csu.modifiers = append(csu.modifiers, modifiers...)
	return csu
}

func (csu *ConsumedStatusUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := csu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(consumedstatus.Table, consumedstatus.Columns, sqlgraph.NewFieldSpec(consumedstatus.FieldID, field.TypeInt64))
	if ps := csu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := csu.mutation.Consumed(); ok {
		_spec.SetField(consumedstatus.FieldConsumed, field.TypeFloat64, value)
	}
	if value, ok := csu.mutation.AddedConsumed(); ok {
		_spec.AddField(consumedstatus.FieldConsumed, field.TypeFloat64, value)
	}
	if csu.mutation.ConsumedCleared() {
		_spec.ClearField(consumedstatus.FieldConsumed, field.TypeFloat64)
	}
	if value, ok := csu.mutation.Left(); ok {
		_spec.SetField(consumedstatus.FieldLeft, field.TypeFloat64, value)
	}
	if value, ok := csu.mutation.AddedLeft(); ok {
		_spec.AddField(consumedstatus.FieldLeft, field.TypeFloat64, value)
	}
	if csu.mutation.LeftCleared() {
		_spec.ClearField(consumedstatus.FieldLeft, field.TypeFloat64)
	}
	if value, ok := csu.mutation.ActiveTill(); ok {
		_spec.SetField(consumedstatus.FieldActiveTill, field.TypeTime, value)
	}
	if csu.mutation.ActiveTillCleared() {
		_spec.ClearField(consumedstatus.FieldActiveTill, field.TypeTime)
	}
	if value, ok := csu.mutation.StartFrom(); ok {
		_spec.SetField(consumedstatus.FieldStartFrom, field.TypeTime, value)
	}
	if csu.mutation.StartFromCleared() {
		_spec.ClearField(consumedstatus.FieldStartFrom, field.TypeTime)
	}
	_spec.AddModifiers(csu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, csu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{consumedstatus.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	csu.mutation.done = true
	return n, nil
}

// ConsumedStatusUpdateOne is the builder for updating a single ConsumedStatus entity.
type ConsumedStatusUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ConsumedStatusMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetConsumed sets the "consumed" field.
func (csuo *ConsumedStatusUpdateOne) SetConsumed(f float64) *ConsumedStatusUpdateOne {
	csuo.mutation.ResetConsumed()
	csuo.mutation.SetConsumed(f)
	return csuo
}

// SetNillableConsumed sets the "consumed" field if the given value is not nil.
func (csuo *ConsumedStatusUpdateOne) SetNillableConsumed(f *float64) *ConsumedStatusUpdateOne {
	if f != nil {
		csuo.SetConsumed(*f)
	}
	return csuo
}

// AddConsumed adds f to the "consumed" field.
func (csuo *ConsumedStatusUpdateOne) AddConsumed(f float64) *ConsumedStatusUpdateOne {
	csuo.mutation.AddConsumed(f)
	return csuo
}

// ClearConsumed clears the value of the "consumed" field.
func (csuo *ConsumedStatusUpdateOne) ClearConsumed() *ConsumedStatusUpdateOne {
	csuo.mutation.ClearConsumed()
	return csuo
}

// SetLeft sets the "left" field.
func (csuo *ConsumedStatusUpdateOne) SetLeft(f float64) *ConsumedStatusUpdateOne {
	csuo.mutation.ResetLeft()
	csuo.mutation.SetLeft(f)
	return csuo
}

// SetNillableLeft sets the "left" field if the given value is not nil.
func (csuo *ConsumedStatusUpdateOne) SetNillableLeft(f *float64) *ConsumedStatusUpdateOne {
	if f != nil {
		csuo.SetLeft(*f)
	}
	return csuo
}

// AddLeft adds f to the "left" field.
func (csuo *ConsumedStatusUpdateOne) AddLeft(f float64) *ConsumedStatusUpdateOne {
	csuo.mutation.AddLeft(f)
	return csuo
}

// ClearLeft clears the value of the "left" field.
func (csuo *ConsumedStatusUpdateOne) ClearLeft() *ConsumedStatusUpdateOne {
	csuo.mutation.ClearLeft()
	return csuo
}

// SetActiveTill sets the "active_till" field.
func (csuo *ConsumedStatusUpdateOne) SetActiveTill(t time.Time) *ConsumedStatusUpdateOne {
	csuo.mutation.SetActiveTill(t)
	return csuo
}

// SetNillableActiveTill sets the "active_till" field if the given value is not nil.
func (csuo *ConsumedStatusUpdateOne) SetNillableActiveTill(t *time.Time) *ConsumedStatusUpdateOne {
	if t != nil {
		csuo.SetActiveTill(*t)
	}
	return csuo
}

// ClearActiveTill clears the value of the "active_till" field.
func (csuo *ConsumedStatusUpdateOne) ClearActiveTill() *ConsumedStatusUpdateOne {
	csuo.mutation.ClearActiveTill()
	return csuo
}

// SetStartFrom sets the "start_from" field.
func (csuo *ConsumedStatusUpdateOne) SetStartFrom(t time.Time) *ConsumedStatusUpdateOne {
	csuo.mutation.SetStartFrom(t)
	return csuo
}

// SetNillableStartFrom sets the "start_from" field if the given value is not nil.
func (csuo *ConsumedStatusUpdateOne) SetNillableStartFrom(t *time.Time) *ConsumedStatusUpdateOne {
	if t != nil {
		csuo.SetStartFrom(*t)
	}
	return csuo
}

// ClearStartFrom clears the value of the "start_from" field.
func (csuo *ConsumedStatusUpdateOne) ClearStartFrom() *ConsumedStatusUpdateOne {
	csuo.mutation.ClearStartFrom()
	return csuo
}

// Mutation returns the ConsumedStatusMutation object of the builder.
func (csuo *ConsumedStatusUpdateOne) Mutation() *ConsumedStatusMutation {
	return csuo.mutation
}

// Where appends a list predicates to the ConsumedStatusUpdate builder.
func (csuo *ConsumedStatusUpdateOne) Where(ps ...predicate.ConsumedStatus) *ConsumedStatusUpdateOne {
	csuo.mutation.Where(ps...)
	return csuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (csuo *ConsumedStatusUpdateOne) Select(field string, fields ...string) *ConsumedStatusUpdateOne {
	csuo.fields = append([]string{field}, fields...)
	return csuo
}

// Save executes the query and returns the updated ConsumedStatus entity.
func (csuo *ConsumedStatusUpdateOne) Save(ctx context.Context) (*ConsumedStatus, error) {
	return withHooks(ctx, csuo.sqlSave, csuo.mutation, csuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (csuo *ConsumedStatusUpdateOne) SaveX(ctx context.Context) *ConsumedStatus {
	node, err := csuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (csuo *ConsumedStatusUpdateOne) Exec(ctx context.Context) error {
	_, err := csuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (csuo *ConsumedStatusUpdateOne) ExecX(ctx context.Context) {
	if err := csuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (csuo *ConsumedStatusUpdateOne) check() error {
	if csuo.mutation.ItemCleared() && len(csuo.mutation.ItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ConsumedStatus.item"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (csuo *ConsumedStatusUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ConsumedStatusUpdateOne {
	csuo.modifiers = append(csuo.modifiers, modifiers...)
	return csuo
}

func (csuo *ConsumedStatusUpdateOne) sqlSave(ctx context.Context) (_node *ConsumedStatus, err error) {
	if err := csuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(consumedstatus.Table, consumedstatus.Columns, sqlgraph.NewFieldSpec(consumedstatus.FieldID, field.TypeInt64))
	id, ok := csuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ConsumedStatus.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := csuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, consumedstatus.FieldID)
		for _, f := range fields {
			if !consumedstatus.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != consumedstatus.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := csuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := csuo.mutation.Consumed(); ok {
		_spec.SetField(consumedstatus.FieldConsumed, field.TypeFloat64, value)
	}
	if value, ok := csuo.mutation.AddedConsumed(); ok {
		_spec.AddField(consumedstatus.FieldConsumed, field.TypeFloat64, value)
	}
	if csuo.mutation.ConsumedCleared() {
		_spec.ClearField(consumedstatus.FieldConsumed, field.TypeFloat64)
	}
	if value, ok := csuo.mutation.Left(); ok {
		_spec.SetField(consumedstatus.FieldLeft, field.TypeFloat64, value)
	}
	if value, ok := csuo.mutation.AddedLeft(); ok {
		_spec.AddField(consumedstatus.FieldLeft, field.TypeFloat64, value)
	}
	if csuo.mutation.LeftCleared() {
		_spec.ClearField(consumedstatus.FieldLeft, field.TypeFloat64)
	}
	if value, ok := csuo.mutation.ActiveTill(); ok {
		_spec.SetField(consumedstatus.FieldActiveTill, field.TypeTime, value)
	}
	if csuo.mutation.ActiveTillCleared() {
		_spec.ClearField(consumedstatus.FieldActiveTill, field.TypeTime)
	}
	if value, ok := csuo.mutation.StartFrom(); ok {
		_spec.SetField(consumedstatus.FieldStartFrom, field.TypeTime, value)
	}
	if csuo.mutation.StartFromCleared() {
		_spec.ClearField(consumedstatus.FieldStartFrom, field.TypeTime)
	}
	_spec.AddModifiers(csuo.modifiers...)
	_node = &ConsumedStatus{config: csuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, csuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{consumedstatus.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	csuo.mutation.done = true
	return _node, nil
}
