// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/finance/invoices/ent/consumedstatus"
	"gitlab.calendaria.team/services/finance/invoices/ent/item"
)

// ConsumedStatusCreate is the builder for creating a ConsumedStatus entity.
type ConsumedStatusCreate struct {
	config
	mutation *ConsumedStatusMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (csc *ConsumedStatusCreate) SetUserID(i int64) *ConsumedStatusCreate {
	csc.mutation.SetUserID(i)
	return csc
}

// SetTenantID sets the "tenant_id" field.
func (csc *ConsumedStatusCreate) SetTenantID(i int64) *ConsumedStatusCreate {
	csc.mutation.SetTenantID(i)
	return csc
}

// SetAppID sets the "app_id" field.
func (csc *ConsumedStatusCreate) SetAppID(i int64) *ConsumedStatusCreate {
	csc.mutation.SetAppID(i)
	return csc
}

// SetItemID sets the "item_id" field.
func (csc *ConsumedStatusCreate) SetItemID(i int64) *ConsumedStatusCreate {
	csc.mutation.SetItemID(i)
	return csc
}

// SetConsumed sets the "consumed" field.
func (csc *ConsumedStatusCreate) SetConsumed(f float64) *ConsumedStatusCreate {
	csc.mutation.SetConsumed(f)
	return csc
}

// SetNillableConsumed sets the "consumed" field if the given value is not nil.
func (csc *ConsumedStatusCreate) SetNillableConsumed(f *float64) *ConsumedStatusCreate {
	if f != nil {
		csc.SetConsumed(*f)
	}
	return csc
}

// SetLeft sets the "left" field.
func (csc *ConsumedStatusCreate) SetLeft(f float64) *ConsumedStatusCreate {
	csc.mutation.SetLeft(f)
	return csc
}

// SetNillableLeft sets the "left" field if the given value is not nil.
func (csc *ConsumedStatusCreate) SetNillableLeft(f *float64) *ConsumedStatusCreate {
	if f != nil {
		csc.SetLeft(*f)
	}
	return csc
}

// SetActiveTill sets the "active_till" field.
func (csc *ConsumedStatusCreate) SetActiveTill(t time.Time) *ConsumedStatusCreate {
	csc.mutation.SetActiveTill(t)
	return csc
}

// SetNillableActiveTill sets the "active_till" field if the given value is not nil.
func (csc *ConsumedStatusCreate) SetNillableActiveTill(t *time.Time) *ConsumedStatusCreate {
	if t != nil {
		csc.SetActiveTill(*t)
	}
	return csc
}

// SetStartFrom sets the "start_from" field.
func (csc *ConsumedStatusCreate) SetStartFrom(t time.Time) *ConsumedStatusCreate {
	csc.mutation.SetStartFrom(t)
	return csc
}

// SetNillableStartFrom sets the "start_from" field if the given value is not nil.
func (csc *ConsumedStatusCreate) SetNillableStartFrom(t *time.Time) *ConsumedStatusCreate {
	if t != nil {
		csc.SetStartFrom(*t)
	}
	return csc
}

// SetID sets the "id" field.
func (csc *ConsumedStatusCreate) SetID(i int64) *ConsumedStatusCreate {
	csc.mutation.SetID(i)
	return csc
}

// SetItem sets the "item" edge to the Item entity.
func (csc *ConsumedStatusCreate) SetItem(i *Item) *ConsumedStatusCreate {
	return csc.SetItemID(i.ID)
}

// Mutation returns the ConsumedStatusMutation object of the builder.
func (csc *ConsumedStatusCreate) Mutation() *ConsumedStatusMutation {
	return csc.mutation
}

// Save creates the ConsumedStatus in the database.
func (csc *ConsumedStatusCreate) Save(ctx context.Context) (*ConsumedStatus, error) {
	csc.defaults()
	return withHooks(ctx, csc.sqlSave, csc.mutation, csc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (csc *ConsumedStatusCreate) SaveX(ctx context.Context) *ConsumedStatus {
	v, err := csc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (csc *ConsumedStatusCreate) Exec(ctx context.Context) error {
	_, err := csc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (csc *ConsumedStatusCreate) ExecX(ctx context.Context) {
	if err := csc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (csc *ConsumedStatusCreate) defaults() {
	if _, ok := csc.mutation.Consumed(); !ok {
		v := consumedstatus.DefaultConsumed
		csc.mutation.SetConsumed(v)
	}
	if _, ok := csc.mutation.Left(); !ok {
		v := consumedstatus.DefaultLeft
		csc.mutation.SetLeft(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (csc *ConsumedStatusCreate) check() error {
	if _, ok := csc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ConsumedStatus.user_id"`)}
	}
	if _, ok := csc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "ConsumedStatus.tenant_id"`)}
	}
	if _, ok := csc.mutation.AppID(); !ok {
		return &ValidationError{Name: "app_id", err: errors.New(`ent: missing required field "ConsumedStatus.app_id"`)}
	}
	if _, ok := csc.mutation.ItemID(); !ok {
		return &ValidationError{Name: "item_id", err: errors.New(`ent: missing required field "ConsumedStatus.item_id"`)}
	}
	if len(csc.mutation.ItemIDs()) == 0 {
		return &ValidationError{Name: "item", err: errors.New(`ent: missing required edge "ConsumedStatus.item"`)}
	}
	return nil
}

func (csc *ConsumedStatusCreate) sqlSave(ctx context.Context) (*ConsumedStatus, error) {
	if err := csc.check(); err != nil {
		return nil, err
	}
	_node, _spec := csc.createSpec()
	if err := sqlgraph.CreateNode(ctx, csc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	csc.mutation.id = &_node.ID
	csc.mutation.done = true
	return _node, nil
}

func (csc *ConsumedStatusCreate) createSpec() (*ConsumedStatus, *sqlgraph.CreateSpec) {
	var (
		_node = &ConsumedStatus{config: csc.config}
		_spec = sqlgraph.NewCreateSpec(consumedstatus.Table, sqlgraph.NewFieldSpec(consumedstatus.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = csc.conflict
	if id, ok := csc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := csc.mutation.UserID(); ok {
		_spec.SetField(consumedstatus.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := csc.mutation.TenantID(); ok {
		_spec.SetField(consumedstatus.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := csc.mutation.AppID(); ok {
		_spec.SetField(consumedstatus.FieldAppID, field.TypeInt64, value)
		_node.AppID = value
	}
	if value, ok := csc.mutation.Consumed(); ok {
		_spec.SetField(consumedstatus.FieldConsumed, field.TypeFloat64, value)
		_node.Consumed = value
	}
	if value, ok := csc.mutation.Left(); ok {
		_spec.SetField(consumedstatus.FieldLeft, field.TypeFloat64, value)
		_node.Left = value
	}
	if value, ok := csc.mutation.ActiveTill(); ok {
		_spec.SetField(consumedstatus.FieldActiveTill, field.TypeTime, value)
		_node.ActiveTill = value
	}
	if value, ok := csc.mutation.StartFrom(); ok {
		_spec.SetField(consumedstatus.FieldStartFrom, field.TypeTime, value)
		_node.StartFrom = value
	}
	if nodes := csc.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   consumedstatus.ItemTable,
			Columns: []string{consumedstatus.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ItemID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ConsumedStatus.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ConsumedStatusUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (csc *ConsumedStatusCreate) OnConflict(opts ...sql.ConflictOption) *ConsumedStatusUpsertOne {
	csc.conflict = opts
	return &ConsumedStatusUpsertOne{
		create: csc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ConsumedStatus.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (csc *ConsumedStatusCreate) OnConflictColumns(columns ...string) *ConsumedStatusUpsertOne {
	csc.conflict = append(csc.conflict, sql.ConflictColumns(columns...))
	return &ConsumedStatusUpsertOne{
		create: csc,
	}
}

type (
	// ConsumedStatusUpsertOne is the builder for "upsert"-ing
	//  one ConsumedStatus node.
	ConsumedStatusUpsertOne struct {
		create *ConsumedStatusCreate
	}

	// ConsumedStatusUpsert is the "OnConflict" setter.
	ConsumedStatusUpsert struct {
		*sql.UpdateSet
	}
)

// SetConsumed sets the "consumed" field.
func (u *ConsumedStatusUpsert) SetConsumed(v float64) *ConsumedStatusUpsert {
	u.Set(consumedstatus.FieldConsumed, v)
	return u
}

// UpdateConsumed sets the "consumed" field to the value that was provided on create.
func (u *ConsumedStatusUpsert) UpdateConsumed() *ConsumedStatusUpsert {
	u.SetExcluded(consumedstatus.FieldConsumed)
	return u
}

// AddConsumed adds v to the "consumed" field.
func (u *ConsumedStatusUpsert) AddConsumed(v float64) *ConsumedStatusUpsert {
	u.Add(consumedstatus.FieldConsumed, v)
	return u
}

// ClearConsumed clears the value of the "consumed" field.
func (u *ConsumedStatusUpsert) ClearConsumed() *ConsumedStatusUpsert {
	u.SetNull(consumedstatus.FieldConsumed)
	return u
}

// SetLeft sets the "left" field.
func (u *ConsumedStatusUpsert) SetLeft(v float64) *ConsumedStatusUpsert {
	u.Set(consumedstatus.FieldLeft, v)
	return u
}

// UpdateLeft sets the "left" field to the value that was provided on create.
func (u *ConsumedStatusUpsert) UpdateLeft() *ConsumedStatusUpsert {
	u.SetExcluded(consumedstatus.FieldLeft)
	return u
}

// AddLeft adds v to the "left" field.
func (u *ConsumedStatusUpsert) AddLeft(v float64) *ConsumedStatusUpsert {
	u.Add(consumedstatus.FieldLeft, v)
	return u
}

// ClearLeft clears the value of the "left" field.
func (u *ConsumedStatusUpsert) ClearLeft() *ConsumedStatusUpsert {
	u.SetNull(consumedstatus.FieldLeft)
	return u
}

// SetActiveTill sets the "active_till" field.
func (u *ConsumedStatusUpsert) SetActiveTill(v time.Time) *ConsumedStatusUpsert {
	u.Set(consumedstatus.FieldActiveTill, v)
	return u
}

// UpdateActiveTill sets the "active_till" field to the value that was provided on create.
func (u *ConsumedStatusUpsert) UpdateActiveTill() *ConsumedStatusUpsert {
	u.SetExcluded(consumedstatus.FieldActiveTill)
	return u
}

// ClearActiveTill clears the value of the "active_till" field.
func (u *ConsumedStatusUpsert) ClearActiveTill() *ConsumedStatusUpsert {
	u.SetNull(consumedstatus.FieldActiveTill)
	return u
}

// SetStartFrom sets the "start_from" field.
func (u *ConsumedStatusUpsert) SetStartFrom(v time.Time) *ConsumedStatusUpsert {
	u.Set(consumedstatus.FieldStartFrom, v)
	return u
}

// UpdateStartFrom sets the "start_from" field to the value that was provided on create.
func (u *ConsumedStatusUpsert) UpdateStartFrom() *ConsumedStatusUpsert {
	u.SetExcluded(consumedstatus.FieldStartFrom)
	return u
}

// ClearStartFrom clears the value of the "start_from" field.
func (u *ConsumedStatusUpsert) ClearStartFrom() *ConsumedStatusUpsert {
	u.SetNull(consumedstatus.FieldStartFrom)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ConsumedStatus.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(consumedstatus.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ConsumedStatusUpsertOne) UpdateNewValues() *ConsumedStatusUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(consumedstatus.FieldID)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(consumedstatus.FieldUserID)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(consumedstatus.FieldTenantID)
		}
		if _, exists := u.create.mutation.AppID(); exists {
			s.SetIgnore(consumedstatus.FieldAppID)
		}
		if _, exists := u.create.mutation.ItemID(); exists {
			s.SetIgnore(consumedstatus.FieldItemID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ConsumedStatus.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ConsumedStatusUpsertOne) Ignore() *ConsumedStatusUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ConsumedStatusUpsertOne) DoNothing() *ConsumedStatusUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ConsumedStatusCreate.OnConflict
// documentation for more info.
func (u *ConsumedStatusUpsertOne) Update(set func(*ConsumedStatusUpsert)) *ConsumedStatusUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ConsumedStatusUpsert{UpdateSet: update})
	}))
	return u
}

// SetConsumed sets the "consumed" field.
func (u *ConsumedStatusUpsertOne) SetConsumed(v float64) *ConsumedStatusUpsertOne {
	return u.Update(func(s *ConsumedStatusUpsert) {
		s.SetConsumed(v)
	})
}

// AddConsumed adds v to the "consumed" field.
func (u *ConsumedStatusUpsertOne) AddConsumed(v float64) *ConsumedStatusUpsertOne {
	return u.Update(func(s *ConsumedStatusUpsert) {
		s.AddConsumed(v)
	})
}

// UpdateConsumed sets the "consumed" field to the value that was provided on create.
func (u *ConsumedStatusUpsertOne) UpdateConsumed() *ConsumedStatusUpsertOne {
	return u.Update(func(s *ConsumedStatusUpsert) {
		s.UpdateConsumed()
	})
}

// ClearConsumed clears the value of the "consumed" field.
func (u *ConsumedStatusUpsertOne) ClearConsumed() *ConsumedStatusUpsertOne {
	return u.Update(func(s *ConsumedStatusUpsert) {
		s.ClearConsumed()
	})
}

// SetLeft sets the "left" field.
func (u *ConsumedStatusUpsertOne) SetLeft(v float64) *ConsumedStatusUpsertOne {
	return u.Update(func(s *ConsumedStatusUpsert) {
		s.SetLeft(v)
	})
}

// AddLeft adds v to the "left" field.
func (u *ConsumedStatusUpsertOne) AddLeft(v float64) *ConsumedStatusUpsertOne {
	return u.Update(func(s *ConsumedStatusUpsert) {
		s.AddLeft(v)
	})
}

// UpdateLeft sets the "left" field to the value that was provided on create.
func (u *ConsumedStatusUpsertOne) UpdateLeft() *ConsumedStatusUpsertOne {
	return u.Update(func(s *ConsumedStatusUpsert) {
		s.UpdateLeft()
	})
}

// ClearLeft clears the value of the "left" field.
func (u *ConsumedStatusUpsertOne) ClearLeft() *ConsumedStatusUpsertOne {
	return u.Update(func(s *ConsumedStatusUpsert) {
		s.ClearLeft()
	})
}

// SetActiveTill sets the "active_till" field.
func (u *ConsumedStatusUpsertOne) SetActiveTill(v time.Time) *ConsumedStatusUpsertOne {
	return u.Update(func(s *ConsumedStatusUpsert) {
		s.SetActiveTill(v)
	})
}

// UpdateActiveTill sets the "active_till" field to the value that was provided on create.
func (u *ConsumedStatusUpsertOne) UpdateActiveTill() *ConsumedStatusUpsertOne {
	return u.Update(func(s *ConsumedStatusUpsert) {
		s.UpdateActiveTill()
	})
}

// ClearActiveTill clears the value of the "active_till" field.
func (u *ConsumedStatusUpsertOne) ClearActiveTill() *ConsumedStatusUpsertOne {
	return u.Update(func(s *ConsumedStatusUpsert) {
		s.ClearActiveTill()
	})
}

// SetStartFrom sets the "start_from" field.
func (u *ConsumedStatusUpsertOne) SetStartFrom(v time.Time) *ConsumedStatusUpsertOne {
	return u.Update(func(s *ConsumedStatusUpsert) {
		s.SetStartFrom(v)
	})
}

// UpdateStartFrom sets the "start_from" field to the value that was provided on create.
func (u *ConsumedStatusUpsertOne) UpdateStartFrom() *ConsumedStatusUpsertOne {
	return u.Update(func(s *ConsumedStatusUpsert) {
		s.UpdateStartFrom()
	})
}

// ClearStartFrom clears the value of the "start_from" field.
func (u *ConsumedStatusUpsertOne) ClearStartFrom() *ConsumedStatusUpsertOne {
	return u.Update(func(s *ConsumedStatusUpsert) {
		s.ClearStartFrom()
	})
}

// Exec executes the query.
func (u *ConsumedStatusUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ConsumedStatusCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ConsumedStatusUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ConsumedStatusUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ConsumedStatusUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ConsumedStatusCreateBulk is the builder for creating many ConsumedStatus entities in bulk.
type ConsumedStatusCreateBulk struct {
	config
	err      error
	builders []*ConsumedStatusCreate
	conflict []sql.ConflictOption
}

// Save creates the ConsumedStatus entities in the database.
func (cscb *ConsumedStatusCreateBulk) Save(ctx context.Context) ([]*ConsumedStatus, error) {
	if cscb.err != nil {
		return nil, cscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(cscb.builders))
	nodes := make([]*ConsumedStatus, len(cscb.builders))
	mutators := make([]Mutator, len(cscb.builders))
	for i := range cscb.builders {
		func(i int, root context.Context) {
			builder := cscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConsumedStatusMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = cscb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cscb *ConsumedStatusCreateBulk) SaveX(ctx context.Context) []*ConsumedStatus {
	v, err := cscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cscb *ConsumedStatusCreateBulk) Exec(ctx context.Context) error {
	_, err := cscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cscb *ConsumedStatusCreateBulk) ExecX(ctx context.Context) {
	if err := cscb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ConsumedStatus.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ConsumedStatusUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (cscb *ConsumedStatusCreateBulk) OnConflict(opts ...sql.ConflictOption) *ConsumedStatusUpsertBulk {
	cscb.conflict = opts
	return &ConsumedStatusUpsertBulk{
		create: cscb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ConsumedStatus.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (cscb *ConsumedStatusCreateBulk) OnConflictColumns(columns ...string) *ConsumedStatusUpsertBulk {
	cscb.conflict = append(cscb.conflict, sql.ConflictColumns(columns...))
	return &ConsumedStatusUpsertBulk{
		create: cscb,
	}
}

// ConsumedStatusUpsertBulk is the builder for "upsert"-ing
// a bulk of ConsumedStatus nodes.
type ConsumedStatusUpsertBulk struct {
	create *ConsumedStatusCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ConsumedStatus.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(consumedstatus.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ConsumedStatusUpsertBulk) UpdateNewValues() *ConsumedStatusUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(consumedstatus.FieldID)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(consumedstatus.FieldUserID)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(consumedstatus.FieldTenantID)
			}
			if _, exists := b.mutation.AppID(); exists {
				s.SetIgnore(consumedstatus.FieldAppID)
			}
			if _, exists := b.mutation.ItemID(); exists {
				s.SetIgnore(consumedstatus.FieldItemID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ConsumedStatus.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ConsumedStatusUpsertBulk) Ignore() *ConsumedStatusUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ConsumedStatusUpsertBulk) DoNothing() *ConsumedStatusUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ConsumedStatusCreateBulk.OnConflict
// documentation for more info.
func (u *ConsumedStatusUpsertBulk) Update(set func(*ConsumedStatusUpsert)) *ConsumedStatusUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ConsumedStatusUpsert{UpdateSet: update})
	}))
	return u
}

// SetConsumed sets the "consumed" field.
func (u *ConsumedStatusUpsertBulk) SetConsumed(v float64) *ConsumedStatusUpsertBulk {
	return u.Update(func(s *ConsumedStatusUpsert) {
		s.SetConsumed(v)
	})
}

// AddConsumed adds v to the "consumed" field.
func (u *ConsumedStatusUpsertBulk) AddConsumed(v float64) *ConsumedStatusUpsertBulk {
	return u.Update(func(s *ConsumedStatusUpsert) {
		s.AddConsumed(v)
	})
}

// UpdateConsumed sets the "consumed" field to the value that was provided on create.
func (u *ConsumedStatusUpsertBulk) UpdateConsumed() *ConsumedStatusUpsertBulk {
	return u.Update(func(s *ConsumedStatusUpsert) {
		s.UpdateConsumed()
	})
}

// ClearConsumed clears the value of the "consumed" field.
func (u *ConsumedStatusUpsertBulk) ClearConsumed() *ConsumedStatusUpsertBulk {
	return u.Update(func(s *ConsumedStatusUpsert) {
		s.ClearConsumed()
	})
}

// SetLeft sets the "left" field.
func (u *ConsumedStatusUpsertBulk) SetLeft(v float64) *ConsumedStatusUpsertBulk {
	return u.Update(func(s *ConsumedStatusUpsert) {
		s.SetLeft(v)
	})
}

// AddLeft adds v to the "left" field.
func (u *ConsumedStatusUpsertBulk) AddLeft(v float64) *ConsumedStatusUpsertBulk {
	return u.Update(func(s *ConsumedStatusUpsert) {
		s.AddLeft(v)
	})
}

// UpdateLeft sets the "left" field to the value that was provided on create.
func (u *ConsumedStatusUpsertBulk) UpdateLeft() *ConsumedStatusUpsertBulk {
	return u.Update(func(s *ConsumedStatusUpsert) {
		s.UpdateLeft()
	})
}

// ClearLeft clears the value of the "left" field.
func (u *ConsumedStatusUpsertBulk) ClearLeft() *ConsumedStatusUpsertBulk {
	return u.Update(func(s *ConsumedStatusUpsert) {
		s.ClearLeft()
	})
}

// SetActiveTill sets the "active_till" field.
func (u *ConsumedStatusUpsertBulk) SetActiveTill(v time.Time) *ConsumedStatusUpsertBulk {
	return u.Update(func(s *ConsumedStatusUpsert) {
		s.SetActiveTill(v)
	})
}

// UpdateActiveTill sets the "active_till" field to the value that was provided on create.
func (u *ConsumedStatusUpsertBulk) UpdateActiveTill() *ConsumedStatusUpsertBulk {
	return u.Update(func(s *ConsumedStatusUpsert) {
		s.UpdateActiveTill()
	})
}

// ClearActiveTill clears the value of the "active_till" field.
func (u *ConsumedStatusUpsertBulk) ClearActiveTill() *ConsumedStatusUpsertBulk {
	return u.Update(func(s *ConsumedStatusUpsert) {
		s.ClearActiveTill()
	})
}

// SetStartFrom sets the "start_from" field.
func (u *ConsumedStatusUpsertBulk) SetStartFrom(v time.Time) *ConsumedStatusUpsertBulk {
	return u.Update(func(s *ConsumedStatusUpsert) {
		s.SetStartFrom(v)
	})
}

// UpdateStartFrom sets the "start_from" field to the value that was provided on create.
func (u *ConsumedStatusUpsertBulk) UpdateStartFrom() *ConsumedStatusUpsertBulk {
	return u.Update(func(s *ConsumedStatusUpsert) {
		s.UpdateStartFrom()
	})
}

// ClearStartFrom clears the value of the "start_from" field.
func (u *ConsumedStatusUpsertBulk) ClearStartFrom() *ConsumedStatusUpsertBulk {
	return u.Update(func(s *ConsumedStatusUpsert) {
		s.ClearStartFrom()
	})
}

// Exec executes the query.
func (u *ConsumedStatusUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ConsumedStatusCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ConsumedStatusCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ConsumedStatusUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
