// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"gitlab.calendaria.team/services/finance/invoices/ent/consumedstatus"
	"gitlab.calendaria.team/services/finance/invoices/ent/item"
)

// ConsumedStatus is the model entity for the ConsumedStatus schema.
type ConsumedStatus struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID int64 `json:"tenant_id,omitempty"`
	// AppID holds the value of the "app_id" field.
	AppID int64 `json:"app_id,omitempty"`
	// ItemID holds the value of the "item_id" field.
	ItemID int64 `json:"item_id,omitempty"`
	// Consumed holds the value of the "consumed" field.
	Consumed float64 `json:"consumed,omitempty"`
	// Left holds the value of the "left" field.
	Left float64 `json:"left,omitempty"`
	// ActiveTill holds the value of the "active_till" field.
	ActiveTill time.Time `json:"active_till,omitempty"`
	// StartFrom holds the value of the "start_from" field.
	StartFrom time.Time `json:"start_from,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ConsumedStatusQuery when eager-loading is set.
	Edges                     ConsumedStatusEdges `json:"edges"`
	invoice_consumed_statuses *int64
	selectValues              sql.SelectValues
}

// ConsumedStatusEdges holds the relations/edges for other nodes in the graph.
type ConsumedStatusEdges struct {
	// Item holds the value of the item edge.
	Item *Item `json:"item,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ItemOrErr returns the Item value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ConsumedStatusEdges) ItemOrErr() (*Item, error) {
	if e.Item != nil {
		return e.Item, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: item.Label}
	}
	return nil, &NotLoadedError{edge: "item"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ConsumedStatus) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case consumedstatus.FieldConsumed, consumedstatus.FieldLeft:
			values[i] = new(sql.NullFloat64)
		case consumedstatus.FieldID, consumedstatus.FieldUserID, consumedstatus.FieldTenantID, consumedstatus.FieldAppID, consumedstatus.FieldItemID:
			values[i] = new(sql.NullInt64)
		case consumedstatus.FieldActiveTill, consumedstatus.FieldStartFrom:
			values[i] = new(sql.NullTime)
		case consumedstatus.ForeignKeys[0]: // invoice_consumed_statuses
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ConsumedStatus fields.
func (cs *ConsumedStatus) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case consumedstatus.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			cs.ID = int64(value.Int64)
		case consumedstatus.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				cs.UserID = value.Int64
			}
		case consumedstatus.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				cs.TenantID = value.Int64
			}
		case consumedstatus.FieldAppID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field app_id", values[i])
			} else if value.Valid {
				cs.AppID = value.Int64
			}
		case consumedstatus.FieldItemID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field item_id", values[i])
			} else if value.Valid {
				cs.ItemID = value.Int64
			}
		case consumedstatus.FieldConsumed:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field consumed", values[i])
			} else if value.Valid {
				cs.Consumed = value.Float64
			}
		case consumedstatus.FieldLeft:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field left", values[i])
			} else if value.Valid {
				cs.Left = value.Float64
			}
		case consumedstatus.FieldActiveTill:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field active_till", values[i])
			} else if value.Valid {
				cs.ActiveTill = value.Time
			}
		case consumedstatus.FieldStartFrom:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_from", values[i])
			} else if value.Valid {
				cs.StartFrom = value.Time
			}
		case consumedstatus.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field invoice_consumed_statuses", value)
			} else if value.Valid {
				cs.invoice_consumed_statuses = new(int64)
				*cs.invoice_consumed_statuses = int64(value.Int64)
			}
		default:
			cs.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ConsumedStatus.
// This includes values selected through modifiers, order, etc.
func (cs *ConsumedStatus) Value(name string) (ent.Value, error) {
	return cs.selectValues.Get(name)
}

// QueryItem queries the "item" edge of the ConsumedStatus entity.
func (cs *ConsumedStatus) QueryItem() *ItemQuery {
	return NewConsumedStatusClient(cs.config).QueryItem(cs)
}

// Update returns a builder for updating this ConsumedStatus.
// Note that you need to call ConsumedStatus.Unwrap() before calling this method if this ConsumedStatus
// was returned from a transaction, and the transaction was committed or rolled back.
func (cs *ConsumedStatus) Update() *ConsumedStatusUpdateOne {
	return NewConsumedStatusClient(cs.config).UpdateOne(cs)
}

// Unwrap unwraps the ConsumedStatus entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cs *ConsumedStatus) Unwrap() *ConsumedStatus {
	_tx, ok := cs.config.driver.(*txDriver)
	if !ok {
		panic("ent: ConsumedStatus is not a transactional entity")
	}
	cs.config.driver = _tx.drv
	return cs
}

// String implements the fmt.Stringer.
func (cs *ConsumedStatus) String() string {
	var builder strings.Builder
	builder.WriteString("ConsumedStatus(")
	builder.WriteString(fmt.Sprintf("id=%v, ", cs.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", cs.UserID))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", cs.TenantID))
	builder.WriteString(", ")
	builder.WriteString("app_id=")
	builder.WriteString(fmt.Sprintf("%v", cs.AppID))
	builder.WriteString(", ")
	builder.WriteString("item_id=")
	builder.WriteString(fmt.Sprintf("%v", cs.ItemID))
	builder.WriteString(", ")
	builder.WriteString("consumed=")
	builder.WriteString(fmt.Sprintf("%v", cs.Consumed))
	builder.WriteString(", ")
	builder.WriteString("left=")
	builder.WriteString(fmt.Sprintf("%v", cs.Left))
	builder.WriteString(", ")
	builder.WriteString("active_till=")
	builder.WriteString(cs.ActiveTill.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("start_from=")
	builder.WriteString(cs.StartFrom.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ConsumedStatusSlice is a parsable slice of ConsumedStatus.
type ConsumedStatusSlice []*ConsumedStatus
