// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"dummy/ent/dummy"
	"dummy/ent/predicate"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DummyUpdate is the builder for updating Dummy entities.
type DummyUpdate struct {
	config
	hooks    []Hook
	mutation *DummyMutation
}

// Where appends a list predicates to the DummyUpdate builder.
func (du *DummyUpdate) Where(ps ...predicate.Dummy) *DummyUpdate {
	du.mutation.Where(ps...)
	return du
}

// SetUserID sets the "user_id" field.
func (du *DummyUpdate) SetUserID(i int64) *DummyUpdate {
	du.mutation.ResetUserID()
	du.mutation.SetUserID(i)
	return du
}

// AddUserID adds i to the "user_id" field.
func (du *DummyUpdate) AddUserID(i int64) *DummyUpdate {
	du.mutation.AddUserID(i)
	return du
}

// SetName sets the "name" field.
func (du *DummyUpdate) SetName(s string) *DummyUpdate {
	du.mutation.SetName(s)
	return du
}

// SetNillableName sets the "name" field if the given value is not nil.
func (du *DummyUpdate) SetNillableName(s *string) *DummyUpdate {
	if s != nil {
		du.SetName(*s)
	}
	return du
}

// SetCreatedAt sets the "created_at" field.
func (du *DummyUpdate) SetCreatedAt(t time.Time) *DummyUpdate {
	du.mutation.SetCreatedAt(t)
	return du
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (du *DummyUpdate) SetNillableCreatedAt(t *time.Time) *DummyUpdate {
	if t != nil {
		du.SetCreatedAt(*t)
	}
	return du
}

// SetUpdatedAt sets the "updated_at" field.
func (du *DummyUpdate) SetUpdatedAt(t time.Time) *DummyUpdate {
	du.mutation.SetUpdatedAt(t)
	return du
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (du *DummyUpdate) SetNillableUpdatedAt(t *time.Time) *DummyUpdate {
	if t != nil {
		du.SetUpdatedAt(*t)
	}
	return du
}

// Mutation returns the DummyMutation object of the builder.
func (du *DummyUpdate) Mutation() *DummyMutation {
	return du.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (du *DummyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, du.sqlSave, du.mutation, du.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (du *DummyUpdate) SaveX(ctx context.Context) int {
	affected, err := du.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (du *DummyUpdate) Exec(ctx context.Context) error {
	_, err := du.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (du *DummyUpdate) ExecX(ctx context.Context) {
	if err := du.Exec(ctx); err != nil {
		panic(err)
	}
}

func (du *DummyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(dummy.Table, dummy.Columns, sqlgraph.NewFieldSpec(dummy.FieldID, field.TypeInt))
	if ps := du.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := du.mutation.UserID(); ok {
		_spec.SetField(dummy.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := du.mutation.AddedUserID(); ok {
		_spec.AddField(dummy.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := du.mutation.Name(); ok {
		_spec.SetField(dummy.FieldName, field.TypeString, value)
	}
	if value, ok := du.mutation.CreatedAt(); ok {
		_spec.SetField(dummy.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := du.mutation.UpdatedAt(); ok {
		_spec.SetField(dummy.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, du.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dummy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	du.mutation.done = true
	return n, nil
}

// DummyUpdateOne is the builder for updating a single Dummy entity.
type DummyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DummyMutation
}

// SetUserID sets the "user_id" field.
func (duo *DummyUpdateOne) SetUserID(i int64) *DummyUpdateOne {
	duo.mutation.ResetUserID()
	duo.mutation.SetUserID(i)
	return duo
}

// AddUserID adds i to the "user_id" field.
func (duo *DummyUpdateOne) AddUserID(i int64) *DummyUpdateOne {
	duo.mutation.AddUserID(i)
	return duo
}

// SetName sets the "name" field.
func (duo *DummyUpdateOne) SetName(s string) *DummyUpdateOne {
	duo.mutation.SetName(s)
	return duo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (duo *DummyUpdateOne) SetNillableName(s *string) *DummyUpdateOne {
	if s != nil {
		duo.SetName(*s)
	}
	return duo
}

// SetCreatedAt sets the "created_at" field.
func (duo *DummyUpdateOne) SetCreatedAt(t time.Time) *DummyUpdateOne {
	duo.mutation.SetCreatedAt(t)
	return duo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (duo *DummyUpdateOne) SetNillableCreatedAt(t *time.Time) *DummyUpdateOne {
	if t != nil {
		duo.SetCreatedAt(*t)
	}
	return duo
}

// SetUpdatedAt sets the "updated_at" field.
func (duo *DummyUpdateOne) SetUpdatedAt(t time.Time) *DummyUpdateOne {
	duo.mutation.SetUpdatedAt(t)
	return duo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (duo *DummyUpdateOne) SetNillableUpdatedAt(t *time.Time) *DummyUpdateOne {
	if t != nil {
		duo.SetUpdatedAt(*t)
	}
	return duo
}

// Mutation returns the DummyMutation object of the builder.
func (duo *DummyUpdateOne) Mutation() *DummyMutation {
	return duo.mutation
}

// Where appends a list predicates to the DummyUpdate builder.
func (duo *DummyUpdateOne) Where(ps ...predicate.Dummy) *DummyUpdateOne {
	duo.mutation.Where(ps...)
	return duo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (duo *DummyUpdateOne) Select(field string, fields ...string) *DummyUpdateOne {
	duo.fields = append([]string{field}, fields...)
	return duo
}

// Save executes the query and returns the updated Dummy entity.
func (duo *DummyUpdateOne) Save(ctx context.Context) (*Dummy, error) {
	return withHooks(ctx, duo.sqlSave, duo.mutation, duo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (duo *DummyUpdateOne) SaveX(ctx context.Context) *Dummy {
	node, err := duo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (duo *DummyUpdateOne) Exec(ctx context.Context) error {
	_, err := duo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (duo *DummyUpdateOne) ExecX(ctx context.Context) {
	if err := duo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (duo *DummyUpdateOne) sqlSave(ctx context.Context) (_node *Dummy, err error) {
	_spec := sqlgraph.NewUpdateSpec(dummy.Table, dummy.Columns, sqlgraph.NewFieldSpec(dummy.FieldID, field.TypeInt))
	id, ok := duo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Dummy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := duo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dummy.FieldID)
		for _, f := range fields {
			if !dummy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dummy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := duo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := duo.mutation.UserID(); ok {
		_spec.SetField(dummy.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := duo.mutation.AddedUserID(); ok {
		_spec.AddField(dummy.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := duo.mutation.Name(); ok {
		_spec.SetField(dummy.FieldName, field.TypeString, value)
	}
	if value, ok := duo.mutation.CreatedAt(); ok {
		_spec.SetField(dummy.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := duo.mutation.UpdatedAt(); ok {
		_spec.SetField(dummy.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Dummy{config: duo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, duo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dummy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	duo.mutation.done = true
	return _node, nil
}
