// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"dummy/ent/dummy"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DummyCreate is the builder for creating a Dummy entity.
type DummyCreate struct {
	config
	mutation *DummyMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (dc *DummyCreate) SetUserID(i int64) *DummyCreate {
	dc.mutation.SetUserID(i)
	return dc
}

// SetName sets the "name" field.
func (dc *DummyCreate) SetName(s string) *DummyCreate {
	dc.mutation.SetName(s)
	return dc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (dc *DummyCreate) SetNillableName(s *string) *DummyCreate {
	if s != nil {
		dc.SetName(*s)
	}
	return dc
}

// SetCreatedAt sets the "created_at" field.
func (dc *DummyCreate) SetCreatedAt(t time.Time) *DummyCreate {
	dc.mutation.SetCreatedAt(t)
	return dc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (dc *DummyCreate) SetNillableCreatedAt(t *time.Time) *DummyCreate {
	if t != nil {
		dc.SetCreatedAt(*t)
	}
	return dc
}

// SetUpdatedAt sets the "updated_at" field.
func (dc *DummyCreate) SetUpdatedAt(t time.Time) *DummyCreate {
	dc.mutation.SetUpdatedAt(t)
	return dc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (dc *DummyCreate) SetNillableUpdatedAt(t *time.Time) *DummyCreate {
	if t != nil {
		dc.SetUpdatedAt(*t)
	}
	return dc
}

// Mutation returns the DummyMutation object of the builder.
func (dc *DummyCreate) Mutation() *DummyMutation {
	return dc.mutation
}

// Save creates the Dummy in the database.
func (dc *DummyCreate) Save(ctx context.Context) (*Dummy, error) {
	dc.defaults()
	return withHooks(ctx, dc.sqlSave, dc.mutation, dc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dc *DummyCreate) SaveX(ctx context.Context) *Dummy {
	v, err := dc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dc *DummyCreate) Exec(ctx context.Context) error {
	_, err := dc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dc *DummyCreate) ExecX(ctx context.Context) {
	if err := dc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dc *DummyCreate) defaults() {
	if _, ok := dc.mutation.Name(); !ok {
		v := dummy.DefaultName
		dc.mutation.SetName(v)
	}
	if _, ok := dc.mutation.CreatedAt(); !ok {
		v := dummy.DefaultCreatedAt()
		dc.mutation.SetCreatedAt(v)
	}
	if _, ok := dc.mutation.UpdatedAt(); !ok {
		v := dummy.DefaultUpdatedAt()
		dc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dc *DummyCreate) check() error {
	if _, ok := dc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Dummy.user_id"`)}
	}
	if _, ok := dc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Dummy.name"`)}
	}
	if _, ok := dc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Dummy.created_at"`)}
	}
	if _, ok := dc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Dummy.updated_at"`)}
	}
	return nil
}

func (dc *DummyCreate) sqlSave(ctx context.Context) (*Dummy, error) {
	if err := dc.check(); err != nil {
		return nil, err
	}
	_node, _spec := dc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	dc.mutation.id = &_node.ID
	dc.mutation.done = true
	return _node, nil
}

func (dc *DummyCreate) createSpec() (*Dummy, *sqlgraph.CreateSpec) {
	var (
		_node = &Dummy{config: dc.config}
		_spec = sqlgraph.NewCreateSpec(dummy.Table, sqlgraph.NewFieldSpec(dummy.FieldID, field.TypeInt))
	)
	if value, ok := dc.mutation.UserID(); ok {
		_spec.SetField(dummy.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := dc.mutation.Name(); ok {
		_spec.SetField(dummy.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := dc.mutation.CreatedAt(); ok {
		_spec.SetField(dummy.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := dc.mutation.UpdatedAt(); ok {
		_spec.SetField(dummy.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// DummyCreateBulk is the builder for creating many Dummy entities in bulk.
type DummyCreateBulk struct {
	config
	builders []*DummyCreate
}

// Save creates the Dummy entities in the database.
func (dcb *DummyCreateBulk) Save(ctx context.Context) ([]*Dummy, error) {
	specs := make([]*sqlgraph.CreateSpec, len(dcb.builders))
	nodes := make([]*Dummy, len(dcb.builders))
	mutators := make([]Mutator, len(dcb.builders))
	for i := range dcb.builders {
		func(i int, root context.Context) {
			builder := dcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DummyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dcb *DummyCreateBulk) SaveX(ctx context.Context) []*Dummy {
	v, err := dcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dcb *DummyCreateBulk) Exec(ctx context.Context) error {
	_, err := dcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dcb *DummyCreateBulk) ExecX(ctx context.Context) {
	if err := dcb.Exec(ctx); err != nil {
		panic(err)
	}
}
