// Code generated by ent, DO NOT EDIT.

package ent

import (
	"gitlab.calendaria.team/services/finance/invoices/ent/bundle"
	"gitlab.calendaria.team/services/finance/invoices/ent/consumedstatus"
	"gitlab.calendaria.team/services/finance/invoices/ent/invoice"
	"gitlab.calendaria.team/services/finance/invoices/ent/item"
	"gitlab.calendaria.team/services/finance/invoices/ent/predicate"
	"gitlab.calendaria.team/services/finance/invoices/ent/product"
	"gitlab.calendaria.team/services/finance/invoices/ent/subscriptionstatus"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entql"
	"entgo.io/ent/schema/field"
)

// schemaGraph holds a representation of ent/schema at runtime.
var schemaGraph = func() *sqlgraph.Schema {
	graph := &sqlgraph.Schema{Nodes: make([]*sqlgraph.Node, 6)}
	graph.Nodes[0] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   bundle.Table,
			Columns: bundle.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: bundle.FieldID,
			},
		},
		Type: "Bundle",
		Fields: map[string]*sqlgraph.FieldSpec{
			bundle.FieldDeletedAt: {Type: field.TypeTime, Column: bundle.FieldDeletedAt},
			bundle.FieldCreatedAt: {Type: field.TypeTime, Column: bundle.FieldCreatedAt},
			bundle.FieldUpdatedAt: {Type: field.TypeTime, Column: bundle.FieldUpdatedAt},
			bundle.FieldProductID: {Type: field.TypeInt64, Column: bundle.FieldProductID},
			bundle.FieldItemID:    {Type: field.TypeInt64, Column: bundle.FieldItemID},
			bundle.FieldAmount:    {Type: field.TypeFloat64, Column: bundle.FieldAmount},
		},
	}
	graph.Nodes[1] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   consumedstatus.Table,
			Columns: consumedstatus.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: consumedstatus.FieldID,
			},
		},
		Type: "ConsumedStatus",
		Fields: map[string]*sqlgraph.FieldSpec{
			consumedstatus.FieldUserID:     {Type: field.TypeInt64, Column: consumedstatus.FieldUserID},
			consumedstatus.FieldTenantID:   {Type: field.TypeInt64, Column: consumedstatus.FieldTenantID},
			consumedstatus.FieldAppID:      {Type: field.TypeInt64, Column: consumedstatus.FieldAppID},
			consumedstatus.FieldItemID:     {Type: field.TypeInt64, Column: consumedstatus.FieldItemID},
			consumedstatus.FieldConsumed:   {Type: field.TypeFloat64, Column: consumedstatus.FieldConsumed},
			consumedstatus.FieldLeft:       {Type: field.TypeFloat64, Column: consumedstatus.FieldLeft},
			consumedstatus.FieldActiveTill: {Type: field.TypeTime, Column: consumedstatus.FieldActiveTill},
			consumedstatus.FieldStartFrom:  {Type: field.TypeTime, Column: consumedstatus.FieldStartFrom},
		},
	}
	graph.Nodes[2] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   invoice.Table,
			Columns: invoice.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: invoice.FieldID,
			},
		},
		Type: "Invoice",
		Fields: map[string]*sqlgraph.FieldSpec{
			invoice.FieldUserID:    {Type: field.TypeInt64, Column: invoice.FieldUserID},
			invoice.FieldAppID:     {Type: field.TypeString, Column: invoice.FieldAppID},
			invoice.FieldProductID: {Type: field.TypeInt64, Column: invoice.FieldProductID},
			invoice.FieldAmount:    {Type: field.TypeInt64, Column: invoice.FieldAmount},
			invoice.FieldPrice:     {Type: field.TypeFloat64, Column: invoice.FieldPrice},
			invoice.FieldCurrency:  {Type: field.TypeString, Column: invoice.FieldCurrency},
			invoice.FieldStatus:    {Type: field.TypeEnum, Column: invoice.FieldStatus},
			invoice.FieldPaidAt:    {Type: field.TypeTime, Column: invoice.FieldPaidAt},
		},
	}
	graph.Nodes[3] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   item.Table,
			Columns: item.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: item.FieldID,
			},
		},
		Type: "Item",
		Fields: map[string]*sqlgraph.FieldSpec{
			item.FieldCreatedAt:   {Type: field.TypeTime, Column: item.FieldCreatedAt},
			item.FieldUpdatedAt:   {Type: field.TypeTime, Column: item.FieldUpdatedAt},
			item.FieldDeletedAt:   {Type: field.TypeTime, Column: item.FieldDeletedAt},
			item.FieldName:        {Type: field.TypeString, Column: item.FieldName},
			item.FieldDescription: {Type: field.TypeString, Column: item.FieldDescription},
		},
	}
	graph.Nodes[4] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   product.Table,
			Columns: product.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: product.FieldID,
			},
		},
		Type: "Product",
		Fields: map[string]*sqlgraph.FieldSpec{
			product.FieldName:        {Type: field.TypeString, Column: product.FieldName},
			product.FieldDescription: {Type: field.TypeString, Column: product.FieldDescription},
			product.FieldPrice:       {Type: field.TypeFloat64, Column: product.FieldPrice},
			product.FieldCurrency:    {Type: field.TypeString, Column: product.FieldCurrency},
			product.FieldIsActive:    {Type: field.TypeBool, Column: product.FieldIsActive},
			product.FieldIsLimited:   {Type: field.TypeBool, Column: product.FieldIsLimited},
			product.FieldLimitedTill: {Type: field.TypeTime, Column: product.FieldLimitedTill},
			product.FieldLeft:        {Type: field.TypeInt64, Column: product.FieldLeft},
			product.FieldIsUnique:    {Type: field.TypeBool, Column: product.FieldIsUnique},
			product.FieldUniqueLimit: {Type: field.TypeInt64, Column: product.FieldUniqueLimit},
		},
	}
	graph.Nodes[5] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   subscriptionstatus.Table,
			Columns: subscriptionstatus.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: subscriptionstatus.FieldID,
			},
		},
		Type: "SubscriptionStatus",
		Fields: map[string]*sqlgraph.FieldSpec{
			subscriptionstatus.FieldInvoiceID:  {Type: field.TypeInt64, Column: subscriptionstatus.FieldInvoiceID},
			subscriptionstatus.FieldItemID:     {Type: field.TypeInt64, Column: subscriptionstatus.FieldItemID},
			subscriptionstatus.FieldActiveTill: {Type: field.TypeTime, Column: subscriptionstatus.FieldActiveTill},
			subscriptionstatus.FieldStartFrom:  {Type: field.TypeTime, Column: subscriptionstatus.FieldStartFrom},
		},
	}
	graph.MustAddE(
		"product",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundle.ProductTable,
			Columns: []string{bundle.ProductColumn},
			Bidi:    false,
		},
		"Bundle",
		"Product",
	)
	graph.MustAddE(
		"item",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundle.ItemTable,
			Columns: []string{bundle.ItemColumn},
			Bidi:    false,
		},
		"Bundle",
		"Item",
	)
	graph.MustAddE(
		"item",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   consumedstatus.ItemTable,
			Columns: []string{consumedstatus.ItemColumn},
			Bidi:    false,
		},
		"ConsumedStatus",
		"Item",
	)
	graph.MustAddE(
		"product",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoice.ProductTable,
			Columns: []string{invoice.ProductColumn},
			Bidi:    false,
		},
		"Invoice",
		"Product",
	)
	graph.MustAddE(
		"consumed_statuses",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoice.ConsumedStatusesTable,
			Columns: []string{invoice.ConsumedStatusesColumn},
			Bidi:    false,
		},
		"Invoice",
		"ConsumedStatus",
	)
	graph.MustAddE(
		"subscription_statuses",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoice.SubscriptionStatusesTable,
			Columns: []string{invoice.SubscriptionStatusesColumn},
			Bidi:    false,
		},
		"Invoice",
		"SubscriptionStatus",
	)
	graph.MustAddE(
		"bundles",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.BundlesTable,
			Columns: []string{item.BundlesColumn},
			Bidi:    false,
		},
		"Item",
		"Bundle",
	)
	graph.MustAddE(
		"consumed_statuses",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.ConsumedStatusesTable,
			Columns: []string{item.ConsumedStatusesColumn},
			Bidi:    false,
		},
		"Item",
		"ConsumedStatus",
	)
	graph.MustAddE(
		"subscription_statuses",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.SubscriptionStatusesTable,
			Columns: []string{item.SubscriptionStatusesColumn},
			Bidi:    false,
		},
		"Item",
		"SubscriptionStatus",
	)
	graph.MustAddE(
		"invoices",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.InvoicesTable,
			Columns: []string{product.InvoicesColumn},
			Bidi:    false,
		},
		"Product",
		"Invoice",
	)
	graph.MustAddE(
		"bundles",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.BundlesTable,
			Columns: []string{product.BundlesColumn},
			Bidi:    false,
		},
		"Product",
		"Bundle",
	)
	graph.MustAddE(
		"invoice",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionstatus.InvoiceTable,
			Columns: []string{subscriptionstatus.InvoiceColumn},
			Bidi:    false,
		},
		"SubscriptionStatus",
		"Invoice",
	)
	graph.MustAddE(
		"item",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionstatus.ItemTable,
			Columns: []string{subscriptionstatus.ItemColumn},
			Bidi:    false,
		},
		"SubscriptionStatus",
		"Item",
	)
	return graph
}()

// predicateAdder wraps the addPredicate method.
// All update, update-one and query builders implement this interface.
type predicateAdder interface {
	addPredicate(func(s *sql.Selector))
}

// addPredicate implements the predicateAdder interface.
func (bq *BundleQuery) addPredicate(pred func(s *sql.Selector)) {
	bq.predicates = append(bq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the BundleQuery builder.
func (bq *BundleQuery) Filter() *BundleFilter {
	return &BundleFilter{config: bq.config, predicateAdder: bq}
}

// addPredicate implements the predicateAdder interface.
func (m *BundleMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the BundleMutation builder.
func (m *BundleMutation) Filter() *BundleFilter {
	return &BundleFilter{config: m.config, predicateAdder: m}
}

// BundleFilter provides a generic filtering capability at runtime for BundleQuery.
type BundleFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *BundleFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[0].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int64 predicate on the id field.
func (f *BundleFilter) WhereID(p entql.Int64P) {
	f.Where(p.Field(bundle.FieldID))
}

// WhereDeletedAt applies the entql time.Time predicate on the deleted_at field.
func (f *BundleFilter) WhereDeletedAt(p entql.TimeP) {
	f.Where(p.Field(bundle.FieldDeletedAt))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *BundleFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(bundle.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *BundleFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(bundle.FieldUpdatedAt))
}

// WhereProductID applies the entql int64 predicate on the product_id field.
func (f *BundleFilter) WhereProductID(p entql.Int64P) {
	f.Where(p.Field(bundle.FieldProductID))
}

// WhereItemID applies the entql int64 predicate on the item_id field.
func (f *BundleFilter) WhereItemID(p entql.Int64P) {
	f.Where(p.Field(bundle.FieldItemID))
}

// WhereAmount applies the entql float64 predicate on the amount field.
func (f *BundleFilter) WhereAmount(p entql.Float64P) {
	f.Where(p.Field(bundle.FieldAmount))
}

// WhereHasProduct applies a predicate to check if query has an edge product.
func (f *BundleFilter) WhereHasProduct() {
	f.Where(entql.HasEdge("product"))
}

// WhereHasProductWith applies a predicate to check if query has an edge product with a given conditions (other predicates).
func (f *BundleFilter) WhereHasProductWith(preds ...predicate.Product) {
	f.Where(entql.HasEdgeWith("product", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// WhereHasItem applies a predicate to check if query has an edge item.
func (f *BundleFilter) WhereHasItem() {
	f.Where(entql.HasEdge("item"))
}

// WhereHasItemWith applies a predicate to check if query has an edge item with a given conditions (other predicates).
func (f *BundleFilter) WhereHasItemWith(preds ...predicate.Item) {
	f.Where(entql.HasEdgeWith("item", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (csq *ConsumedStatusQuery) addPredicate(pred func(s *sql.Selector)) {
	csq.predicates = append(csq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the ConsumedStatusQuery builder.
func (csq *ConsumedStatusQuery) Filter() *ConsumedStatusFilter {
	return &ConsumedStatusFilter{config: csq.config, predicateAdder: csq}
}

// addPredicate implements the predicateAdder interface.
func (m *ConsumedStatusMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the ConsumedStatusMutation builder.
func (m *ConsumedStatusMutation) Filter() *ConsumedStatusFilter {
	return &ConsumedStatusFilter{config: m.config, predicateAdder: m}
}

// ConsumedStatusFilter provides a generic filtering capability at runtime for ConsumedStatusQuery.
type ConsumedStatusFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *ConsumedStatusFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[1].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int64 predicate on the id field.
func (f *ConsumedStatusFilter) WhereID(p entql.Int64P) {
	f.Where(p.Field(consumedstatus.FieldID))
}

// WhereUserID applies the entql int64 predicate on the user_id field.
func (f *ConsumedStatusFilter) WhereUserID(p entql.Int64P) {
	f.Where(p.Field(consumedstatus.FieldUserID))
}

// WhereTenantID applies the entql int64 predicate on the tenant_id field.
func (f *ConsumedStatusFilter) WhereTenantID(p entql.Int64P) {
	f.Where(p.Field(consumedstatus.FieldTenantID))
}

// WhereAppID applies the entql int64 predicate on the app_id field.
func (f *ConsumedStatusFilter) WhereAppID(p entql.Int64P) {
	f.Where(p.Field(consumedstatus.FieldAppID))
}

// WhereItemID applies the entql int64 predicate on the item_id field.
func (f *ConsumedStatusFilter) WhereItemID(p entql.Int64P) {
	f.Where(p.Field(consumedstatus.FieldItemID))
}

// WhereConsumed applies the entql float64 predicate on the consumed field.
func (f *ConsumedStatusFilter) WhereConsumed(p entql.Float64P) {
	f.Where(p.Field(consumedstatus.FieldConsumed))
}

// WhereLeft applies the entql float64 predicate on the left field.
func (f *ConsumedStatusFilter) WhereLeft(p entql.Float64P) {
	f.Where(p.Field(consumedstatus.FieldLeft))
}

// WhereActiveTill applies the entql time.Time predicate on the active_till field.
func (f *ConsumedStatusFilter) WhereActiveTill(p entql.TimeP) {
	f.Where(p.Field(consumedstatus.FieldActiveTill))
}

// WhereStartFrom applies the entql time.Time predicate on the start_from field.
func (f *ConsumedStatusFilter) WhereStartFrom(p entql.TimeP) {
	f.Where(p.Field(consumedstatus.FieldStartFrom))
}

// WhereHasItem applies a predicate to check if query has an edge item.
func (f *ConsumedStatusFilter) WhereHasItem() {
	f.Where(entql.HasEdge("item"))
}

// WhereHasItemWith applies a predicate to check if query has an edge item with a given conditions (other predicates).
func (f *ConsumedStatusFilter) WhereHasItemWith(preds ...predicate.Item) {
	f.Where(entql.HasEdgeWith("item", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (iq *InvoiceQuery) addPredicate(pred func(s *sql.Selector)) {
	iq.predicates = append(iq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the InvoiceQuery builder.
func (iq *InvoiceQuery) Filter() *InvoiceFilter {
	return &InvoiceFilter{config: iq.config, predicateAdder: iq}
}

// addPredicate implements the predicateAdder interface.
func (m *InvoiceMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the InvoiceMutation builder.
func (m *InvoiceMutation) Filter() *InvoiceFilter {
	return &InvoiceFilter{config: m.config, predicateAdder: m}
}

// InvoiceFilter provides a generic filtering capability at runtime for InvoiceQuery.
type InvoiceFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *InvoiceFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[2].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int64 predicate on the id field.
func (f *InvoiceFilter) WhereID(p entql.Int64P) {
	f.Where(p.Field(invoice.FieldID))
}

// WhereUserID applies the entql int64 predicate on the user_id field.
func (f *InvoiceFilter) WhereUserID(p entql.Int64P) {
	f.Where(p.Field(invoice.FieldUserID))
}

// WhereAppID applies the entql string predicate on the app_id field.
func (f *InvoiceFilter) WhereAppID(p entql.StringP) {
	f.Where(p.Field(invoice.FieldAppID))
}

// WhereProductID applies the entql int64 predicate on the product_id field.
func (f *InvoiceFilter) WhereProductID(p entql.Int64P) {
	f.Where(p.Field(invoice.FieldProductID))
}

// WhereAmount applies the entql int64 predicate on the amount field.
func (f *InvoiceFilter) WhereAmount(p entql.Int64P) {
	f.Where(p.Field(invoice.FieldAmount))
}

// WherePrice applies the entql float64 predicate on the price field.
func (f *InvoiceFilter) WherePrice(p entql.Float64P) {
	f.Where(p.Field(invoice.FieldPrice))
}

// WhereCurrency applies the entql string predicate on the currency field.
func (f *InvoiceFilter) WhereCurrency(p entql.StringP) {
	f.Where(p.Field(invoice.FieldCurrency))
}

// WhereStatus applies the entql string predicate on the status field.
func (f *InvoiceFilter) WhereStatus(p entql.StringP) {
	f.Where(p.Field(invoice.FieldStatus))
}

// WherePaidAt applies the entql time.Time predicate on the paid_at field.
func (f *InvoiceFilter) WherePaidAt(p entql.TimeP) {
	f.Where(p.Field(invoice.FieldPaidAt))
}

// WhereHasProduct applies a predicate to check if query has an edge product.
func (f *InvoiceFilter) WhereHasProduct() {
	f.Where(entql.HasEdge("product"))
}

// WhereHasProductWith applies a predicate to check if query has an edge product with a given conditions (other predicates).
func (f *InvoiceFilter) WhereHasProductWith(preds ...predicate.Product) {
	f.Where(entql.HasEdgeWith("product", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// WhereHasConsumedStatuses applies a predicate to check if query has an edge consumed_statuses.
func (f *InvoiceFilter) WhereHasConsumedStatuses() {
	f.Where(entql.HasEdge("consumed_statuses"))
}

// WhereHasConsumedStatusesWith applies a predicate to check if query has an edge consumed_statuses with a given conditions (other predicates).
func (f *InvoiceFilter) WhereHasConsumedStatusesWith(preds ...predicate.ConsumedStatus) {
	f.Where(entql.HasEdgeWith("consumed_statuses", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// WhereHasSubscriptionStatuses applies a predicate to check if query has an edge subscription_statuses.
func (f *InvoiceFilter) WhereHasSubscriptionStatuses() {
	f.Where(entql.HasEdge("subscription_statuses"))
}

// WhereHasSubscriptionStatusesWith applies a predicate to check if query has an edge subscription_statuses with a given conditions (other predicates).
func (f *InvoiceFilter) WhereHasSubscriptionStatusesWith(preds ...predicate.SubscriptionStatus) {
	f.Where(entql.HasEdgeWith("subscription_statuses", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (iq *ItemQuery) addPredicate(pred func(s *sql.Selector)) {
	iq.predicates = append(iq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the ItemQuery builder.
func (iq *ItemQuery) Filter() *ItemFilter {
	return &ItemFilter{config: iq.config, predicateAdder: iq}
}

// addPredicate implements the predicateAdder interface.
func (m *ItemMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the ItemMutation builder.
func (m *ItemMutation) Filter() *ItemFilter {
	return &ItemFilter{config: m.config, predicateAdder: m}
}

// ItemFilter provides a generic filtering capability at runtime for ItemQuery.
type ItemFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *ItemFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[3].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int64 predicate on the id field.
func (f *ItemFilter) WhereID(p entql.Int64P) {
	f.Where(p.Field(item.FieldID))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *ItemFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(item.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *ItemFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(item.FieldUpdatedAt))
}

// WhereDeletedAt applies the entql time.Time predicate on the deleted_at field.
func (f *ItemFilter) WhereDeletedAt(p entql.TimeP) {
	f.Where(p.Field(item.FieldDeletedAt))
}

// WhereName applies the entql string predicate on the name field.
func (f *ItemFilter) WhereName(p entql.StringP) {
	f.Where(p.Field(item.FieldName))
}

// WhereDescription applies the entql string predicate on the description field.
func (f *ItemFilter) WhereDescription(p entql.StringP) {
	f.Where(p.Field(item.FieldDescription))
}

// WhereHasBundles applies a predicate to check if query has an edge bundles.
func (f *ItemFilter) WhereHasBundles() {
	f.Where(entql.HasEdge("bundles"))
}

// WhereHasBundlesWith applies a predicate to check if query has an edge bundles with a given conditions (other predicates).
func (f *ItemFilter) WhereHasBundlesWith(preds ...predicate.Bundle) {
	f.Where(entql.HasEdgeWith("bundles", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// WhereHasConsumedStatuses applies a predicate to check if query has an edge consumed_statuses.
func (f *ItemFilter) WhereHasConsumedStatuses() {
	f.Where(entql.HasEdge("consumed_statuses"))
}

// WhereHasConsumedStatusesWith applies a predicate to check if query has an edge consumed_statuses with a given conditions (other predicates).
func (f *ItemFilter) WhereHasConsumedStatusesWith(preds ...predicate.ConsumedStatus) {
	f.Where(entql.HasEdgeWith("consumed_statuses", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// WhereHasSubscriptionStatuses applies a predicate to check if query has an edge subscription_statuses.
func (f *ItemFilter) WhereHasSubscriptionStatuses() {
	f.Where(entql.HasEdge("subscription_statuses"))
}

// WhereHasSubscriptionStatusesWith applies a predicate to check if query has an edge subscription_statuses with a given conditions (other predicates).
func (f *ItemFilter) WhereHasSubscriptionStatusesWith(preds ...predicate.SubscriptionStatus) {
	f.Where(entql.HasEdgeWith("subscription_statuses", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (pq *ProductQuery) addPredicate(pred func(s *sql.Selector)) {
	pq.predicates = append(pq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the ProductQuery builder.
func (pq *ProductQuery) Filter() *ProductFilter {
	return &ProductFilter{config: pq.config, predicateAdder: pq}
}

// addPredicate implements the predicateAdder interface.
func (m *ProductMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the ProductMutation builder.
func (m *ProductMutation) Filter() *ProductFilter {
	return &ProductFilter{config: m.config, predicateAdder: m}
}

// ProductFilter provides a generic filtering capability at runtime for ProductQuery.
type ProductFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *ProductFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[4].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int64 predicate on the id field.
func (f *ProductFilter) WhereID(p entql.Int64P) {
	f.Where(p.Field(product.FieldID))
}

// WhereName applies the entql string predicate on the name field.
func (f *ProductFilter) WhereName(p entql.StringP) {
	f.Where(p.Field(product.FieldName))
}

// WhereDescription applies the entql string predicate on the description field.
func (f *ProductFilter) WhereDescription(p entql.StringP) {
	f.Where(p.Field(product.FieldDescription))
}

// WherePrice applies the entql float64 predicate on the price field.
func (f *ProductFilter) WherePrice(p entql.Float64P) {
	f.Where(p.Field(product.FieldPrice))
}

// WhereCurrency applies the entql string predicate on the currency field.
func (f *ProductFilter) WhereCurrency(p entql.StringP) {
	f.Where(p.Field(product.FieldCurrency))
}

// WhereIsActive applies the entql bool predicate on the is_active field.
func (f *ProductFilter) WhereIsActive(p entql.BoolP) {
	f.Where(p.Field(product.FieldIsActive))
}

// WhereIsLimited applies the entql bool predicate on the is_limited field.
func (f *ProductFilter) WhereIsLimited(p entql.BoolP) {
	f.Where(p.Field(product.FieldIsLimited))
}

// WhereLimitedTill applies the entql time.Time predicate on the limited_till field.
func (f *ProductFilter) WhereLimitedTill(p entql.TimeP) {
	f.Where(p.Field(product.FieldLimitedTill))
}

// WhereLeft applies the entql int64 predicate on the left field.
func (f *ProductFilter) WhereLeft(p entql.Int64P) {
	f.Where(p.Field(product.FieldLeft))
}

// WhereIsUnique applies the entql bool predicate on the is_unique field.
func (f *ProductFilter) WhereIsUnique(p entql.BoolP) {
	f.Where(p.Field(product.FieldIsUnique))
}

// WhereUniqueLimit applies the entql int64 predicate on the unique_limit field.
func (f *ProductFilter) WhereUniqueLimit(p entql.Int64P) {
	f.Where(p.Field(product.FieldUniqueLimit))
}

// WhereHasInvoices applies a predicate to check if query has an edge invoices.
func (f *ProductFilter) WhereHasInvoices() {
	f.Where(entql.HasEdge("invoices"))
}

// WhereHasInvoicesWith applies a predicate to check if query has an edge invoices with a given conditions (other predicates).
func (f *ProductFilter) WhereHasInvoicesWith(preds ...predicate.Invoice) {
	f.Where(entql.HasEdgeWith("invoices", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// WhereHasBundles applies a predicate to check if query has an edge bundles.
func (f *ProductFilter) WhereHasBundles() {
	f.Where(entql.HasEdge("bundles"))
}

// WhereHasBundlesWith applies a predicate to check if query has an edge bundles with a given conditions (other predicates).
func (f *ProductFilter) WhereHasBundlesWith(preds ...predicate.Bundle) {
	f.Where(entql.HasEdgeWith("bundles", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (ssq *SubscriptionStatusQuery) addPredicate(pred func(s *sql.Selector)) {
	ssq.predicates = append(ssq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the SubscriptionStatusQuery builder.
func (ssq *SubscriptionStatusQuery) Filter() *SubscriptionStatusFilter {
	return &SubscriptionStatusFilter{config: ssq.config, predicateAdder: ssq}
}

// addPredicate implements the predicateAdder interface.
func (m *SubscriptionStatusMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the SubscriptionStatusMutation builder.
func (m *SubscriptionStatusMutation) Filter() *SubscriptionStatusFilter {
	return &SubscriptionStatusFilter{config: m.config, predicateAdder: m}
}

// SubscriptionStatusFilter provides a generic filtering capability at runtime for SubscriptionStatusQuery.
type SubscriptionStatusFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *SubscriptionStatusFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[5].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int64 predicate on the id field.
func (f *SubscriptionStatusFilter) WhereID(p entql.Int64P) {
	f.Where(p.Field(subscriptionstatus.FieldID))
}

// WhereInvoiceID applies the entql int64 predicate on the invoice_id field.
func (f *SubscriptionStatusFilter) WhereInvoiceID(p entql.Int64P) {
	f.Where(p.Field(subscriptionstatus.FieldInvoiceID))
}

// WhereItemID applies the entql int64 predicate on the item_id field.
func (f *SubscriptionStatusFilter) WhereItemID(p entql.Int64P) {
	f.Where(p.Field(subscriptionstatus.FieldItemID))
}

// WhereActiveTill applies the entql time.Time predicate on the active_till field.
func (f *SubscriptionStatusFilter) WhereActiveTill(p entql.TimeP) {
	f.Where(p.Field(subscriptionstatus.FieldActiveTill))
}

// WhereStartFrom applies the entql time.Time predicate on the start_from field.
func (f *SubscriptionStatusFilter) WhereStartFrom(p entql.TimeP) {
	f.Where(p.Field(subscriptionstatus.FieldStartFrom))
}

// WhereHasInvoice applies a predicate to check if query has an edge invoice.
func (f *SubscriptionStatusFilter) WhereHasInvoice() {
	f.Where(entql.HasEdge("invoice"))
}

// WhereHasInvoiceWith applies a predicate to check if query has an edge invoice with a given conditions (other predicates).
func (f *SubscriptionStatusFilter) WhereHasInvoiceWith(preds ...predicate.Invoice) {
	f.Where(entql.HasEdgeWith("invoice", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// WhereHasItem applies a predicate to check if query has an edge item.
func (f *SubscriptionStatusFilter) WhereHasItem() {
	f.Where(entql.HasEdge("item"))
}

// WhereHasItemWith applies a predicate to check if query has an edge item with a given conditions (other predicates).
func (f *SubscriptionStatusFilter) WhereHasItemWith(preds ...predicate.Item) {
	f.Where(entql.HasEdgeWith("item", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}
