// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/finance/invoices/ent/bundle"
	"gitlab.calendaria.team/services/finance/invoices/ent/consumedstatus"
	"gitlab.calendaria.team/services/finance/invoices/ent/item"
	"gitlab.calendaria.team/services/finance/invoices/ent/predicate"
	"gitlab.calendaria.team/services/finance/invoices/ent/subscriptionstatus"
)

// ItemUpdate is the builder for updating Item entities.
type ItemUpdate struct {
	config
	hooks     []Hook
	mutation  *ItemMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ItemUpdate builder.
func (iu *ItemUpdate) Where(ps ...predicate.Item) *ItemUpdate {
	iu.mutation.Where(ps...)
	return iu
}

// SetUpdatedAt sets the "updated_at" field.
func (iu *ItemUpdate) SetUpdatedAt(t time.Time) *ItemUpdate {
	iu.mutation.SetUpdatedAt(t)
	return iu
}

// SetDeletedAt sets the "deleted_at" field.
func (iu *ItemUpdate) SetDeletedAt(t time.Time) *ItemUpdate {
	iu.mutation.SetDeletedAt(t)
	return iu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (iu *ItemUpdate) SetNillableDeletedAt(t *time.Time) *ItemUpdate {
	if t != nil {
		iu.SetDeletedAt(*t)
	}
	return iu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (iu *ItemUpdate) ClearDeletedAt() *ItemUpdate {
	iu.mutation.ClearDeletedAt()
	return iu
}

// SetName sets the "name" field.
func (iu *ItemUpdate) SetName(s string) *ItemUpdate {
	iu.mutation.SetName(s)
	return iu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (iu *ItemUpdate) SetNillableName(s *string) *ItemUpdate {
	if s != nil {
		iu.SetName(*s)
	}
	return iu
}

// SetDescription sets the "description" field.
func (iu *ItemUpdate) SetDescription(s string) *ItemUpdate {
	iu.mutation.SetDescription(s)
	return iu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (iu *ItemUpdate) SetNillableDescription(s *string) *ItemUpdate {
	if s != nil {
		iu.SetDescription(*s)
	}
	return iu
}

// AddBundleIDs adds the "bundles" edge to the Bundle entity by IDs.
func (iu *ItemUpdate) AddBundleIDs(ids ...int64) *ItemUpdate {
	iu.mutation.AddBundleIDs(ids...)
	return iu
}

// AddBundles adds the "bundles" edges to the Bundle entity.
func (iu *ItemUpdate) AddBundles(b ...*Bundle) *ItemUpdate {
	ids := make([]int64, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return iu.AddBundleIDs(ids...)
}

// AddConsumedStatusIDs adds the "consumed_statuses" edge to the ConsumedStatus entity by IDs.
func (iu *ItemUpdate) AddConsumedStatusIDs(ids ...int64) *ItemUpdate {
	iu.mutation.AddConsumedStatusIDs(ids...)
	return iu
}

// AddConsumedStatuses adds the "consumed_statuses" edges to the ConsumedStatus entity.
func (iu *ItemUpdate) AddConsumedStatuses(c ...*ConsumedStatus) *ItemUpdate {
	ids := make([]int64, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return iu.AddConsumedStatusIDs(ids...)
}

// AddSubscriptionStatusIDs adds the "subscription_statuses" edge to the SubscriptionStatus entity by IDs.
func (iu *ItemUpdate) AddSubscriptionStatusIDs(ids ...int64) *ItemUpdate {
	iu.mutation.AddSubscriptionStatusIDs(ids...)
	return iu
}

// AddSubscriptionStatuses adds the "subscription_statuses" edges to the SubscriptionStatus entity.
func (iu *ItemUpdate) AddSubscriptionStatuses(s ...*SubscriptionStatus) *ItemUpdate {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return iu.AddSubscriptionStatusIDs(ids...)
}

// Mutation returns the ItemMutation object of the builder.
func (iu *ItemUpdate) Mutation() *ItemMutation {
	return iu.mutation
}

// ClearBundles clears all "bundles" edges to the Bundle entity.
func (iu *ItemUpdate) ClearBundles() *ItemUpdate {
	iu.mutation.ClearBundles()
	return iu
}

// RemoveBundleIDs removes the "bundles" edge to Bundle entities by IDs.
func (iu *ItemUpdate) RemoveBundleIDs(ids ...int64) *ItemUpdate {
	iu.mutation.RemoveBundleIDs(ids...)
	return iu
}

// RemoveBundles removes "bundles" edges to Bundle entities.
func (iu *ItemUpdate) RemoveBundles(b ...*Bundle) *ItemUpdate {
	ids := make([]int64, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return iu.RemoveBundleIDs(ids...)
}

// ClearConsumedStatuses clears all "consumed_statuses" edges to the ConsumedStatus entity.
func (iu *ItemUpdate) ClearConsumedStatuses() *ItemUpdate {
	iu.mutation.ClearConsumedStatuses()
	return iu
}

// RemoveConsumedStatusIDs removes the "consumed_statuses" edge to ConsumedStatus entities by IDs.
func (iu *ItemUpdate) RemoveConsumedStatusIDs(ids ...int64) *ItemUpdate {
	iu.mutation.RemoveConsumedStatusIDs(ids...)
	return iu
}

// RemoveConsumedStatuses removes "consumed_statuses" edges to ConsumedStatus entities.
func (iu *ItemUpdate) RemoveConsumedStatuses(c ...*ConsumedStatus) *ItemUpdate {
	ids := make([]int64, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return iu.RemoveConsumedStatusIDs(ids...)
}

// ClearSubscriptionStatuses clears all "subscription_statuses" edges to the SubscriptionStatus entity.
func (iu *ItemUpdate) ClearSubscriptionStatuses() *ItemUpdate {
	iu.mutation.ClearSubscriptionStatuses()
	return iu
}

// RemoveSubscriptionStatusIDs removes the "subscription_statuses" edge to SubscriptionStatus entities by IDs.
func (iu *ItemUpdate) RemoveSubscriptionStatusIDs(ids ...int64) *ItemUpdate {
	iu.mutation.RemoveSubscriptionStatusIDs(ids...)
	return iu
}

// RemoveSubscriptionStatuses removes "subscription_statuses" edges to SubscriptionStatus entities.
func (iu *ItemUpdate) RemoveSubscriptionStatuses(s ...*SubscriptionStatus) *ItemUpdate {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return iu.RemoveSubscriptionStatusIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (iu *ItemUpdate) Save(ctx context.Context) (int, error) {
	if err := iu.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, iu.sqlSave, iu.mutation, iu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iu *ItemUpdate) SaveX(ctx context.Context) int {
	affected, err := iu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (iu *ItemUpdate) Exec(ctx context.Context) error {
	_, err := iu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iu *ItemUpdate) ExecX(ctx context.Context) {
	if err := iu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (iu *ItemUpdate) defaults() error {
	if _, ok := iu.mutation.UpdatedAt(); !ok {
		if item.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized item.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := item.UpdateDefaultUpdatedAt()
		iu.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (iu *ItemUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ItemUpdate {
	iu.modifiers = append(iu.modifiers, modifiers...)
	return iu
}

func (iu *ItemUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(item.Table, item.Columns, sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt64))
	if ps := iu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iu.mutation.UpdatedAt(); ok {
		_spec.SetField(item.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := iu.mutation.DeletedAt(); ok {
		_spec.SetField(item.FieldDeletedAt, field.TypeTime, value)
	}
	if iu.mutation.DeletedAtCleared() {
		_spec.ClearField(item.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := iu.mutation.Name(); ok {
		_spec.SetField(item.FieldName, field.TypeString, value)
	}
	if value, ok := iu.mutation.Description(); ok {
		_spec.SetField(item.FieldDescription, field.TypeString, value)
	}
	if iu.mutation.BundlesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.BundlesTable,
			Columns: []string{item.BundlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundle.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iu.mutation.RemovedBundlesIDs(); len(nodes) > 0 && !iu.mutation.BundlesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.BundlesTable,
			Columns: []string{item.BundlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundle.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iu.mutation.BundlesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.BundlesTable,
			Columns: []string{item.BundlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundle.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if iu.mutation.ConsumedStatusesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.ConsumedStatusesTable,
			Columns: []string{item.ConsumedStatusesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(consumedstatus.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iu.mutation.RemovedConsumedStatusesIDs(); len(nodes) > 0 && !iu.mutation.ConsumedStatusesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.ConsumedStatusesTable,
			Columns: []string{item.ConsumedStatusesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(consumedstatus.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iu.mutation.ConsumedStatusesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.ConsumedStatusesTable,
			Columns: []string{item.ConsumedStatusesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(consumedstatus.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if iu.mutation.SubscriptionStatusesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.SubscriptionStatusesTable,
			Columns: []string{item.SubscriptionStatusesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionstatus.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iu.mutation.RemovedSubscriptionStatusesIDs(); len(nodes) > 0 && !iu.mutation.SubscriptionStatusesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.SubscriptionStatusesTable,
			Columns: []string{item.SubscriptionStatusesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionstatus.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iu.mutation.SubscriptionStatusesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.SubscriptionStatusesTable,
			Columns: []string{item.SubscriptionStatusesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionstatus.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(iu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, iu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{item.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	iu.mutation.done = true
	return n, nil
}

// ItemUpdateOne is the builder for updating a single Item entity.
type ItemUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ItemMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (iuo *ItemUpdateOne) SetUpdatedAt(t time.Time) *ItemUpdateOne {
	iuo.mutation.SetUpdatedAt(t)
	return iuo
}

// SetDeletedAt sets the "deleted_at" field.
func (iuo *ItemUpdateOne) SetDeletedAt(t time.Time) *ItemUpdateOne {
	iuo.mutation.SetDeletedAt(t)
	return iuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (iuo *ItemUpdateOne) SetNillableDeletedAt(t *time.Time) *ItemUpdateOne {
	if t != nil {
		iuo.SetDeletedAt(*t)
	}
	return iuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (iuo *ItemUpdateOne) ClearDeletedAt() *ItemUpdateOne {
	iuo.mutation.ClearDeletedAt()
	return iuo
}

// SetName sets the "name" field.
func (iuo *ItemUpdateOne) SetName(s string) *ItemUpdateOne {
	iuo.mutation.SetName(s)
	return iuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (iuo *ItemUpdateOne) SetNillableName(s *string) *ItemUpdateOne {
	if s != nil {
		iuo.SetName(*s)
	}
	return iuo
}

// SetDescription sets the "description" field.
func (iuo *ItemUpdateOne) SetDescription(s string) *ItemUpdateOne {
	iuo.mutation.SetDescription(s)
	return iuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (iuo *ItemUpdateOne) SetNillableDescription(s *string) *ItemUpdateOne {
	if s != nil {
		iuo.SetDescription(*s)
	}
	return iuo
}

// AddBundleIDs adds the "bundles" edge to the Bundle entity by IDs.
func (iuo *ItemUpdateOne) AddBundleIDs(ids ...int64) *ItemUpdateOne {
	iuo.mutation.AddBundleIDs(ids...)
	return iuo
}

// AddBundles adds the "bundles" edges to the Bundle entity.
func (iuo *ItemUpdateOne) AddBundles(b ...*Bundle) *ItemUpdateOne {
	ids := make([]int64, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return iuo.AddBundleIDs(ids...)
}

// AddConsumedStatusIDs adds the "consumed_statuses" edge to the ConsumedStatus entity by IDs.
func (iuo *ItemUpdateOne) AddConsumedStatusIDs(ids ...int64) *ItemUpdateOne {
	iuo.mutation.AddConsumedStatusIDs(ids...)
	return iuo
}

// AddConsumedStatuses adds the "consumed_statuses" edges to the ConsumedStatus entity.
func (iuo *ItemUpdateOne) AddConsumedStatuses(c ...*ConsumedStatus) *ItemUpdateOne {
	ids := make([]int64, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return iuo.AddConsumedStatusIDs(ids...)
}

// AddSubscriptionStatusIDs adds the "subscription_statuses" edge to the SubscriptionStatus entity by IDs.
func (iuo *ItemUpdateOne) AddSubscriptionStatusIDs(ids ...int64) *ItemUpdateOne {
	iuo.mutation.AddSubscriptionStatusIDs(ids...)
	return iuo
}

// AddSubscriptionStatuses adds the "subscription_statuses" edges to the SubscriptionStatus entity.
func (iuo *ItemUpdateOne) AddSubscriptionStatuses(s ...*SubscriptionStatus) *ItemUpdateOne {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return iuo.AddSubscriptionStatusIDs(ids...)
}

// Mutation returns the ItemMutation object of the builder.
func (iuo *ItemUpdateOne) Mutation() *ItemMutation {
	return iuo.mutation
}

// ClearBundles clears all "bundles" edges to the Bundle entity.
func (iuo *ItemUpdateOne) ClearBundles() *ItemUpdateOne {
	iuo.mutation.ClearBundles()
	return iuo
}

// RemoveBundleIDs removes the "bundles" edge to Bundle entities by IDs.
func (iuo *ItemUpdateOne) RemoveBundleIDs(ids ...int64) *ItemUpdateOne {
	iuo.mutation.RemoveBundleIDs(ids...)
	return iuo
}

// RemoveBundles removes "bundles" edges to Bundle entities.
func (iuo *ItemUpdateOne) RemoveBundles(b ...*Bundle) *ItemUpdateOne {
	ids := make([]int64, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return iuo.RemoveBundleIDs(ids...)
}

// ClearConsumedStatuses clears all "consumed_statuses" edges to the ConsumedStatus entity.
func (iuo *ItemUpdateOne) ClearConsumedStatuses() *ItemUpdateOne {
	iuo.mutation.ClearConsumedStatuses()
	return iuo
}

// RemoveConsumedStatusIDs removes the "consumed_statuses" edge to ConsumedStatus entities by IDs.
func (iuo *ItemUpdateOne) RemoveConsumedStatusIDs(ids ...int64) *ItemUpdateOne {
	iuo.mutation.RemoveConsumedStatusIDs(ids...)
	return iuo
}

// RemoveConsumedStatuses removes "consumed_statuses" edges to ConsumedStatus entities.
func (iuo *ItemUpdateOne) RemoveConsumedStatuses(c ...*ConsumedStatus) *ItemUpdateOne {
	ids := make([]int64, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return iuo.RemoveConsumedStatusIDs(ids...)
}

// ClearSubscriptionStatuses clears all "subscription_statuses" edges to the SubscriptionStatus entity.
func (iuo *ItemUpdateOne) ClearSubscriptionStatuses() *ItemUpdateOne {
	iuo.mutation.ClearSubscriptionStatuses()
	return iuo
}

// RemoveSubscriptionStatusIDs removes the "subscription_statuses" edge to SubscriptionStatus entities by IDs.
func (iuo *ItemUpdateOne) RemoveSubscriptionStatusIDs(ids ...int64) *ItemUpdateOne {
	iuo.mutation.RemoveSubscriptionStatusIDs(ids...)
	return iuo
}

// RemoveSubscriptionStatuses removes "subscription_statuses" edges to SubscriptionStatus entities.
func (iuo *ItemUpdateOne) RemoveSubscriptionStatuses(s ...*SubscriptionStatus) *ItemUpdateOne {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return iuo.RemoveSubscriptionStatusIDs(ids...)
}

// Where appends a list predicates to the ItemUpdate builder.
func (iuo *ItemUpdateOne) Where(ps ...predicate.Item) *ItemUpdateOne {
	iuo.mutation.Where(ps...)
	return iuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (iuo *ItemUpdateOne) Select(field string, fields ...string) *ItemUpdateOne {
	iuo.fields = append([]string{field}, fields...)
	return iuo
}

// Save executes the query and returns the updated Item entity.
func (iuo *ItemUpdateOne) Save(ctx context.Context) (*Item, error) {
	if err := iuo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, iuo.sqlSave, iuo.mutation, iuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iuo *ItemUpdateOne) SaveX(ctx context.Context) *Item {
	node, err := iuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (iuo *ItemUpdateOne) Exec(ctx context.Context) error {
	_, err := iuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iuo *ItemUpdateOne) ExecX(ctx context.Context) {
	if err := iuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (iuo *ItemUpdateOne) defaults() error {
	if _, ok := iuo.mutation.UpdatedAt(); !ok {
		if item.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized item.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := item.UpdateDefaultUpdatedAt()
		iuo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (iuo *ItemUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ItemUpdateOne {
	iuo.modifiers = append(iuo.modifiers, modifiers...)
	return iuo
}

func (iuo *ItemUpdateOne) sqlSave(ctx context.Context) (_node *Item, err error) {
	_spec := sqlgraph.NewUpdateSpec(item.Table, item.Columns, sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt64))
	id, ok := iuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Item.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := iuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, item.FieldID)
		for _, f := range fields {
			if !item.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != item.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := iuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iuo.mutation.UpdatedAt(); ok {
		_spec.SetField(item.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := iuo.mutation.DeletedAt(); ok {
		_spec.SetField(item.FieldDeletedAt, field.TypeTime, value)
	}
	if iuo.mutation.DeletedAtCleared() {
		_spec.ClearField(item.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := iuo.mutation.Name(); ok {
		_spec.SetField(item.FieldName, field.TypeString, value)
	}
	if value, ok := iuo.mutation.Description(); ok {
		_spec.SetField(item.FieldDescription, field.TypeString, value)
	}
	if iuo.mutation.BundlesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.BundlesTable,
			Columns: []string{item.BundlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundle.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iuo.mutation.RemovedBundlesIDs(); len(nodes) > 0 && !iuo.mutation.BundlesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.BundlesTable,
			Columns: []string{item.BundlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundle.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iuo.mutation.BundlesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.BundlesTable,
			Columns: []string{item.BundlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundle.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if iuo.mutation.ConsumedStatusesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.ConsumedStatusesTable,
			Columns: []string{item.ConsumedStatusesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(consumedstatus.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iuo.mutation.RemovedConsumedStatusesIDs(); len(nodes) > 0 && !iuo.mutation.ConsumedStatusesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.ConsumedStatusesTable,
			Columns: []string{item.ConsumedStatusesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(consumedstatus.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iuo.mutation.ConsumedStatusesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.ConsumedStatusesTable,
			Columns: []string{item.ConsumedStatusesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(consumedstatus.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if iuo.mutation.SubscriptionStatusesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.SubscriptionStatusesTable,
			Columns: []string{item.SubscriptionStatusesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionstatus.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iuo.mutation.RemovedSubscriptionStatusesIDs(); len(nodes) > 0 && !iuo.mutation.SubscriptionStatusesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.SubscriptionStatusesTable,
			Columns: []string{item.SubscriptionStatusesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionstatus.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iuo.mutation.SubscriptionStatusesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.SubscriptionStatusesTable,
			Columns: []string{item.SubscriptionStatusesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionstatus.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(iuo.modifiers...)
	_node = &Item{config: iuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, iuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{item.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	iuo.mutation.done = true
	return _node, nil
}
