// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/finance/billing/ent/invoice"
	"gitlab.calendaria.team/services/finance/billing/ent/paymentprofile"
	"gitlab.calendaria.team/services/finance/billing/ent/predicate"
)

// PaymentProfileUpdate is the builder for updating PaymentProfile entities.
type PaymentProfileUpdate struct {
	config
	hooks     []Hook
	mutation  *PaymentProfileMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the PaymentProfileUpdate builder.
func (ppu *PaymentProfileUpdate) Where(ps ...predicate.PaymentProfile) *PaymentProfileUpdate {
	ppu.mutation.Where(ps...)
	return ppu
}

// SetUpdatedAt sets the "updated_at" field.
func (ppu *PaymentProfileUpdate) SetUpdatedAt(t time.Time) *PaymentProfileUpdate {
	ppu.mutation.SetUpdatedAt(t)
	return ppu
}

// SetDeletedAt sets the "deleted_at" field.
func (ppu *PaymentProfileUpdate) SetDeletedAt(t time.Time) *PaymentProfileUpdate {
	ppu.mutation.SetDeletedAt(t)
	return ppu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ppu *PaymentProfileUpdate) SetNillableDeletedAt(t *time.Time) *PaymentProfileUpdate {
	if t != nil {
		ppu.SetDeletedAt(*t)
	}
	return ppu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (ppu *PaymentProfileUpdate) ClearDeletedAt() *PaymentProfileUpdate {
	ppu.mutation.ClearDeletedAt()
	return ppu
}

// SetEmail sets the "email" field.
func (ppu *PaymentProfileUpdate) SetEmail(s string) *PaymentProfileUpdate {
	ppu.mutation.SetEmail(s)
	return ppu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (ppu *PaymentProfileUpdate) SetNillableEmail(s *string) *PaymentProfileUpdate {
	if s != nil {
		ppu.SetEmail(*s)
	}
	return ppu
}

// ClearEmail clears the value of the "email" field.
func (ppu *PaymentProfileUpdate) ClearEmail() *PaymentProfileUpdate {
	ppu.mutation.ClearEmail()
	return ppu
}

// SetPhone sets the "phone" field.
func (ppu *PaymentProfileUpdate) SetPhone(s string) *PaymentProfileUpdate {
	ppu.mutation.SetPhone(s)
	return ppu
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (ppu *PaymentProfileUpdate) SetNillablePhone(s *string) *PaymentProfileUpdate {
	if s != nil {
		ppu.SetPhone(*s)
	}
	return ppu
}

// ClearPhone clears the value of the "phone" field.
func (ppu *PaymentProfileUpdate) ClearPhone() *PaymentProfileUpdate {
	ppu.mutation.ClearPhone()
	return ppu
}

// SetUserToken sets the "user_token" field.
func (ppu *PaymentProfileUpdate) SetUserToken(s string) *PaymentProfileUpdate {
	ppu.mutation.SetUserToken(s)
	return ppu
}

// SetNillableUserToken sets the "user_token" field if the given value is not nil.
func (ppu *PaymentProfileUpdate) SetNillableUserToken(s *string) *PaymentProfileUpdate {
	if s != nil {
		ppu.SetUserToken(*s)
	}
	return ppu
}

// ClearUserToken clears the value of the "user_token" field.
func (ppu *PaymentProfileUpdate) ClearUserToken() *PaymentProfileUpdate {
	ppu.mutation.ClearUserToken()
	return ppu
}

// SetRecurrentToken sets the "recurrent_token" field.
func (ppu *PaymentProfileUpdate) SetRecurrentToken(s string) *PaymentProfileUpdate {
	ppu.mutation.SetRecurrentToken(s)
	return ppu
}

// SetNillableRecurrentToken sets the "recurrent_token" field if the given value is not nil.
func (ppu *PaymentProfileUpdate) SetNillableRecurrentToken(s *string) *PaymentProfileUpdate {
	if s != nil {
		ppu.SetRecurrentToken(*s)
	}
	return ppu
}

// ClearRecurrentToken clears the value of the "recurrent_token" field.
func (ppu *PaymentProfileUpdate) ClearRecurrentToken() *PaymentProfileUpdate {
	ppu.mutation.ClearRecurrentToken()
	return ppu
}

// AddInvoiceIDs adds the "invoices" edge to the Invoice entity by IDs.
func (ppu *PaymentProfileUpdate) AddInvoiceIDs(ids ...int64) *PaymentProfileUpdate {
	ppu.mutation.AddInvoiceIDs(ids...)
	return ppu
}

// AddInvoices adds the "invoices" edges to the Invoice entity.
func (ppu *PaymentProfileUpdate) AddInvoices(i ...*Invoice) *PaymentProfileUpdate {
	ids := make([]int64, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return ppu.AddInvoiceIDs(ids...)
}

// Mutation returns the PaymentProfileMutation object of the builder.
func (ppu *PaymentProfileUpdate) Mutation() *PaymentProfileMutation {
	return ppu.mutation
}

// ClearInvoices clears all "invoices" edges to the Invoice entity.
func (ppu *PaymentProfileUpdate) ClearInvoices() *PaymentProfileUpdate {
	ppu.mutation.ClearInvoices()
	return ppu
}

// RemoveInvoiceIDs removes the "invoices" edge to Invoice entities by IDs.
func (ppu *PaymentProfileUpdate) RemoveInvoiceIDs(ids ...int64) *PaymentProfileUpdate {
	ppu.mutation.RemoveInvoiceIDs(ids...)
	return ppu
}

// RemoveInvoices removes "invoices" edges to Invoice entities.
func (ppu *PaymentProfileUpdate) RemoveInvoices(i ...*Invoice) *PaymentProfileUpdate {
	ids := make([]int64, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return ppu.RemoveInvoiceIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ppu *PaymentProfileUpdate) Save(ctx context.Context) (int, error) {
	if err := ppu.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, ppu.sqlSave, ppu.mutation, ppu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ppu *PaymentProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := ppu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ppu *PaymentProfileUpdate) Exec(ctx context.Context) error {
	_, err := ppu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ppu *PaymentProfileUpdate) ExecX(ctx context.Context) {
	if err := ppu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ppu *PaymentProfileUpdate) defaults() error {
	if _, ok := ppu.mutation.UpdatedAt(); !ok {
		if paymentprofile.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized paymentprofile.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := paymentprofile.UpdateDefaultUpdatedAt()
		ppu.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ppu *PaymentProfileUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PaymentProfileUpdate {
	ppu.modifiers = append(ppu.modifiers, modifiers...)
	return ppu
}

func (ppu *PaymentProfileUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(paymentprofile.Table, paymentprofile.Columns, sqlgraph.NewFieldSpec(paymentprofile.FieldID, field.TypeInt64))
	if ps := ppu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ppu.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ppu.mutation.DeletedAt(); ok {
		_spec.SetField(paymentprofile.FieldDeletedAt, field.TypeTime, value)
	}
	if ppu.mutation.DeletedAtCleared() {
		_spec.ClearField(paymentprofile.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := ppu.mutation.Email(); ok {
		_spec.SetField(paymentprofile.FieldEmail, field.TypeString, value)
	}
	if ppu.mutation.EmailCleared() {
		_spec.ClearField(paymentprofile.FieldEmail, field.TypeString)
	}
	if value, ok := ppu.mutation.Phone(); ok {
		_spec.SetField(paymentprofile.FieldPhone, field.TypeString, value)
	}
	if ppu.mutation.PhoneCleared() {
		_spec.ClearField(paymentprofile.FieldPhone, field.TypeString)
	}
	if value, ok := ppu.mutation.UserToken(); ok {
		_spec.SetField(paymentprofile.FieldUserToken, field.TypeString, value)
	}
	if ppu.mutation.UserTokenCleared() {
		_spec.ClearField(paymentprofile.FieldUserToken, field.TypeString)
	}
	if value, ok := ppu.mutation.RecurrentToken(); ok {
		_spec.SetField(paymentprofile.FieldRecurrentToken, field.TypeString, value)
	}
	if ppu.mutation.RecurrentTokenCleared() {
		_spec.ClearField(paymentprofile.FieldRecurrentToken, field.TypeString)
	}
	if ppu.mutation.InvoicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentprofile.InvoicesTable,
			Columns: []string{paymentprofile.InvoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ppu.mutation.RemovedInvoicesIDs(); len(nodes) > 0 && !ppu.mutation.InvoicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentprofile.InvoicesTable,
			Columns: []string{paymentprofile.InvoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ppu.mutation.InvoicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentprofile.InvoicesTable,
			Columns: []string{paymentprofile.InvoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(ppu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, ppu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ppu.mutation.done = true
	return n, nil
}

// PaymentProfileUpdateOne is the builder for updating a single PaymentProfile entity.
type PaymentProfileUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *PaymentProfileMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (ppuo *PaymentProfileUpdateOne) SetUpdatedAt(t time.Time) *PaymentProfileUpdateOne {
	ppuo.mutation.SetUpdatedAt(t)
	return ppuo
}

// SetDeletedAt sets the "deleted_at" field.
func (ppuo *PaymentProfileUpdateOne) SetDeletedAt(t time.Time) *PaymentProfileUpdateOne {
	ppuo.mutation.SetDeletedAt(t)
	return ppuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ppuo *PaymentProfileUpdateOne) SetNillableDeletedAt(t *time.Time) *PaymentProfileUpdateOne {
	if t != nil {
		ppuo.SetDeletedAt(*t)
	}
	return ppuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (ppuo *PaymentProfileUpdateOne) ClearDeletedAt() *PaymentProfileUpdateOne {
	ppuo.mutation.ClearDeletedAt()
	return ppuo
}

// SetEmail sets the "email" field.
func (ppuo *PaymentProfileUpdateOne) SetEmail(s string) *PaymentProfileUpdateOne {
	ppuo.mutation.SetEmail(s)
	return ppuo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (ppuo *PaymentProfileUpdateOne) SetNillableEmail(s *string) *PaymentProfileUpdateOne {
	if s != nil {
		ppuo.SetEmail(*s)
	}
	return ppuo
}

// ClearEmail clears the value of the "email" field.
func (ppuo *PaymentProfileUpdateOne) ClearEmail() *PaymentProfileUpdateOne {
	ppuo.mutation.ClearEmail()
	return ppuo
}

// SetPhone sets the "phone" field.
func (ppuo *PaymentProfileUpdateOne) SetPhone(s string) *PaymentProfileUpdateOne {
	ppuo.mutation.SetPhone(s)
	return ppuo
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (ppuo *PaymentProfileUpdateOne) SetNillablePhone(s *string) *PaymentProfileUpdateOne {
	if s != nil {
		ppuo.SetPhone(*s)
	}
	return ppuo
}

// ClearPhone clears the value of the "phone" field.
func (ppuo *PaymentProfileUpdateOne) ClearPhone() *PaymentProfileUpdateOne {
	ppuo.mutation.ClearPhone()
	return ppuo
}

// SetUserToken sets the "user_token" field.
func (ppuo *PaymentProfileUpdateOne) SetUserToken(s string) *PaymentProfileUpdateOne {
	ppuo.mutation.SetUserToken(s)
	return ppuo
}

// SetNillableUserToken sets the "user_token" field if the given value is not nil.
func (ppuo *PaymentProfileUpdateOne) SetNillableUserToken(s *string) *PaymentProfileUpdateOne {
	if s != nil {
		ppuo.SetUserToken(*s)
	}
	return ppuo
}

// ClearUserToken clears the value of the "user_token" field.
func (ppuo *PaymentProfileUpdateOne) ClearUserToken() *PaymentProfileUpdateOne {
	ppuo.mutation.ClearUserToken()
	return ppuo
}

// SetRecurrentToken sets the "recurrent_token" field.
func (ppuo *PaymentProfileUpdateOne) SetRecurrentToken(s string) *PaymentProfileUpdateOne {
	ppuo.mutation.SetRecurrentToken(s)
	return ppuo
}

// SetNillableRecurrentToken sets the "recurrent_token" field if the given value is not nil.
func (ppuo *PaymentProfileUpdateOne) SetNillableRecurrentToken(s *string) *PaymentProfileUpdateOne {
	if s != nil {
		ppuo.SetRecurrentToken(*s)
	}
	return ppuo
}

// ClearRecurrentToken clears the value of the "recurrent_token" field.
func (ppuo *PaymentProfileUpdateOne) ClearRecurrentToken() *PaymentProfileUpdateOne {
	ppuo.mutation.ClearRecurrentToken()
	return ppuo
}

// AddInvoiceIDs adds the "invoices" edge to the Invoice entity by IDs.
func (ppuo *PaymentProfileUpdateOne) AddInvoiceIDs(ids ...int64) *PaymentProfileUpdateOne {
	ppuo.mutation.AddInvoiceIDs(ids...)
	return ppuo
}

// AddInvoices adds the "invoices" edges to the Invoice entity.
func (ppuo *PaymentProfileUpdateOne) AddInvoices(i ...*Invoice) *PaymentProfileUpdateOne {
	ids := make([]int64, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return ppuo.AddInvoiceIDs(ids...)
}

// Mutation returns the PaymentProfileMutation object of the builder.
func (ppuo *PaymentProfileUpdateOne) Mutation() *PaymentProfileMutation {
	return ppuo.mutation
}

// ClearInvoices clears all "invoices" edges to the Invoice entity.
func (ppuo *PaymentProfileUpdateOne) ClearInvoices() *PaymentProfileUpdateOne {
	ppuo.mutation.ClearInvoices()
	return ppuo
}

// RemoveInvoiceIDs removes the "invoices" edge to Invoice entities by IDs.
func (ppuo *PaymentProfileUpdateOne) RemoveInvoiceIDs(ids ...int64) *PaymentProfileUpdateOne {
	ppuo.mutation.RemoveInvoiceIDs(ids...)
	return ppuo
}

// RemoveInvoices removes "invoices" edges to Invoice entities.
func (ppuo *PaymentProfileUpdateOne) RemoveInvoices(i ...*Invoice) *PaymentProfileUpdateOne {
	ids := make([]int64, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return ppuo.RemoveInvoiceIDs(ids...)
}

// Where appends a list predicates to the PaymentProfileUpdate builder.
func (ppuo *PaymentProfileUpdateOne) Where(ps ...predicate.PaymentProfile) *PaymentProfileUpdateOne {
	ppuo.mutation.Where(ps...)
	return ppuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ppuo *PaymentProfileUpdateOne) Select(field string, fields ...string) *PaymentProfileUpdateOne {
	ppuo.fields = append([]string{field}, fields...)
	return ppuo
}

// Save executes the query and returns the updated PaymentProfile entity.
func (ppuo *PaymentProfileUpdateOne) Save(ctx context.Context) (*PaymentProfile, error) {
	if err := ppuo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, ppuo.sqlSave, ppuo.mutation, ppuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ppuo *PaymentProfileUpdateOne) SaveX(ctx context.Context) *PaymentProfile {
	node, err := ppuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ppuo *PaymentProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := ppuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ppuo *PaymentProfileUpdateOne) ExecX(ctx context.Context) {
	if err := ppuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ppuo *PaymentProfileUpdateOne) defaults() error {
	if _, ok := ppuo.mutation.UpdatedAt(); !ok {
		if paymentprofile.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized paymentprofile.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := paymentprofile.UpdateDefaultUpdatedAt()
		ppuo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ppuo *PaymentProfileUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PaymentProfileUpdateOne {
	ppuo.modifiers = append(ppuo.modifiers, modifiers...)
	return ppuo
}

func (ppuo *PaymentProfileUpdateOne) sqlSave(ctx context.Context) (_node *PaymentProfile, err error) {
	_spec := sqlgraph.NewUpdateSpec(paymentprofile.Table, paymentprofile.Columns, sqlgraph.NewFieldSpec(paymentprofile.FieldID, field.TypeInt64))
	id, ok := ppuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentProfile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ppuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentprofile.FieldID)
		for _, f := range fields {
			if !paymentprofile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ppuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ppuo.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ppuo.mutation.DeletedAt(); ok {
		_spec.SetField(paymentprofile.FieldDeletedAt, field.TypeTime, value)
	}
	if ppuo.mutation.DeletedAtCleared() {
		_spec.ClearField(paymentprofile.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := ppuo.mutation.Email(); ok {
		_spec.SetField(paymentprofile.FieldEmail, field.TypeString, value)
	}
	if ppuo.mutation.EmailCleared() {
		_spec.ClearField(paymentprofile.FieldEmail, field.TypeString)
	}
	if value, ok := ppuo.mutation.Phone(); ok {
		_spec.SetField(paymentprofile.FieldPhone, field.TypeString, value)
	}
	if ppuo.mutation.PhoneCleared() {
		_spec.ClearField(paymentprofile.FieldPhone, field.TypeString)
	}
	if value, ok := ppuo.mutation.UserToken(); ok {
		_spec.SetField(paymentprofile.FieldUserToken, field.TypeString, value)
	}
	if ppuo.mutation.UserTokenCleared() {
		_spec.ClearField(paymentprofile.FieldUserToken, field.TypeString)
	}
	if value, ok := ppuo.mutation.RecurrentToken(); ok {
		_spec.SetField(paymentprofile.FieldRecurrentToken, field.TypeString, value)
	}
	if ppuo.mutation.RecurrentTokenCleared() {
		_spec.ClearField(paymentprofile.FieldRecurrentToken, field.TypeString)
	}
	if ppuo.mutation.InvoicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentprofile.InvoicesTable,
			Columns: []string{paymentprofile.InvoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ppuo.mutation.RemovedInvoicesIDs(); len(nodes) > 0 && !ppuo.mutation.InvoicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentprofile.InvoicesTable,
			Columns: []string{paymentprofile.InvoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ppuo.mutation.InvoicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentprofile.InvoicesTable,
			Columns: []string{paymentprofile.InvoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(ppuo.modifiers...)
	_node = &PaymentProfile{config: ppuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ppuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ppuo.mutation.done = true
	return _node, nil
}
