// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"gitlab.calendaria.team/services/finance/billing/ent/paymentprofile"
)

// PaymentProfile is the model entity for the PaymentProfile schema.
type PaymentProfile struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// PanMasked holds the value of the "pan_masked" field.
	PanMasked string `json:"pan_masked,omitempty"`
	// Holder holds the value of the "holder" field.
	Holder string `json:"holder,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Phone holds the value of the "phone" field.
	Phone string `json:"phone,omitempty"`
	// UserToken holds the value of the "user_token" field.
	UserToken string `json:"user_token,omitempty"`
	// RecurrentToken holds the value of the "recurrent_token" field.
	RecurrentToken *string `json:"recurrent_token,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PaymentProfileQuery when eager-loading is set.
	Edges        PaymentProfileEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PaymentProfileEdges holds the relations/edges for other nodes in the graph.
type PaymentProfileEdges struct {
	// Invoices holds the value of the invoices edge.
	Invoices []*Invoice `json:"invoices,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// InvoicesOrErr returns the Invoices value or an error if the edge
// was not loaded in eager-loading.
func (e PaymentProfileEdges) InvoicesOrErr() ([]*Invoice, error) {
	if e.loadedTypes[0] {
		return e.Invoices, nil
	}
	return nil, &NotLoadedError{edge: "invoices"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentProfile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentprofile.FieldID, paymentprofile.FieldUserID:
			values[i] = new(sql.NullInt64)
		case paymentprofile.FieldPanMasked, paymentprofile.FieldHolder, paymentprofile.FieldEmail, paymentprofile.FieldPhone, paymentprofile.FieldUserToken, paymentprofile.FieldRecurrentToken:
			values[i] = new(sql.NullString)
		case paymentprofile.FieldCreatedAt, paymentprofile.FieldUpdatedAt, paymentprofile.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentProfile fields.
func (pp *PaymentProfile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentprofile.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pp.ID = int64(value.Int64)
		case paymentprofile.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				pp.CreatedAt = value.Time
			}
		case paymentprofile.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				pp.UpdatedAt = value.Time
			}
		case paymentprofile.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				pp.DeletedAt = new(time.Time)
				*pp.DeletedAt = value.Time
			}
		case paymentprofile.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				pp.UserID = value.Int64
			}
		case paymentprofile.FieldPanMasked:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pan_masked", values[i])
			} else if value.Valid {
				pp.PanMasked = value.String
			}
		case paymentprofile.FieldHolder:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field holder", values[i])
			} else if value.Valid {
				pp.Holder = value.String
			}
		case paymentprofile.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				pp.Email = value.String
			}
		case paymentprofile.FieldPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phone", values[i])
			} else if value.Valid {
				pp.Phone = value.String
			}
		case paymentprofile.FieldUserToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_token", values[i])
			} else if value.Valid {
				pp.UserToken = value.String
			}
		case paymentprofile.FieldRecurrentToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field recurrent_token", values[i])
			} else if value.Valid {
				pp.RecurrentToken = new(string)
				*pp.RecurrentToken = value.String
			}
		default:
			pp.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentProfile.
// This includes values selected through modifiers, order, etc.
func (pp *PaymentProfile) Value(name string) (ent.Value, error) {
	return pp.selectValues.Get(name)
}

// QueryInvoices queries the "invoices" edge of the PaymentProfile entity.
func (pp *PaymentProfile) QueryInvoices() *InvoiceQuery {
	return NewPaymentProfileClient(pp.config).QueryInvoices(pp)
}

// Update returns a builder for updating this PaymentProfile.
// Note that you need to call PaymentProfile.Unwrap() before calling this method if this PaymentProfile
// was returned from a transaction, and the transaction was committed or rolled back.
func (pp *PaymentProfile) Update() *PaymentProfileUpdateOne {
	return NewPaymentProfileClient(pp.config).UpdateOne(pp)
}

// Unwrap unwraps the PaymentProfile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pp *PaymentProfile) Unwrap() *PaymentProfile {
	_tx, ok := pp.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentProfile is not a transactional entity")
	}
	pp.config.driver = _tx.drv
	return pp
}

// String implements the fmt.Stringer.
func (pp *PaymentProfile) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentProfile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pp.ID))
	builder.WriteString("created_at=")
	builder.WriteString(pp.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(pp.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := pp.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", pp.UserID))
	builder.WriteString(", ")
	builder.WriteString("pan_masked=")
	builder.WriteString(pp.PanMasked)
	builder.WriteString(", ")
	builder.WriteString("holder=")
	builder.WriteString(pp.Holder)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(pp.Email)
	builder.WriteString(", ")
	builder.WriteString("phone=")
	builder.WriteString(pp.Phone)
	builder.WriteString(", ")
	builder.WriteString("user_token=")
	builder.WriteString(pp.UserToken)
	builder.WriteString(", ")
	if v := pp.RecurrentToken; v != nil {
		builder.WriteString("recurrent_token=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// PaymentProfiles is a parsable slice of PaymentProfile.
type PaymentProfiles []*PaymentProfile
