// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/makesalekz/billing/ent/paymentprofile"
	"github.com/makesalekz/billing/ent/predicate"
)

// PaymentProfileDelete is the builder for deleting a PaymentProfile entity.
type PaymentProfileDelete struct {
	config
	hooks    []Hook
	mutation *PaymentProfileMutation
}

// Where appends a list predicates to the PaymentProfileDelete builder.
func (ppd *PaymentProfileDelete) Where(ps ...predicate.PaymentProfile) *PaymentProfileDelete {
	ppd.mutation.Where(ps...)
	return ppd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ppd *PaymentProfileDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ppd.sqlExec, ppd.mutation, ppd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ppd *PaymentProfileDelete) ExecX(ctx context.Context) int {
	n, err := ppd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ppd *PaymentProfileDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(paymentprofile.Table, sqlgraph.NewFieldSpec(paymentprofile.FieldID, field.TypeInt64))
	if ps := ppd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ppd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ppd.mutation.done = true
	return affected, err
}

// PaymentProfileDeleteOne is the builder for deleting a single PaymentProfile entity.
type PaymentProfileDeleteOne struct {
	ppd *PaymentProfileDelete
}

// Where appends a list predicates to the PaymentProfileDelete builder.
func (ppdo *PaymentProfileDeleteOne) Where(ps ...predicate.PaymentProfile) *PaymentProfileDeleteOne {
	ppdo.ppd.mutation.Where(ps...)
	return ppdo
}

// Exec executes the deletion query.
func (ppdo *PaymentProfileDeleteOne) Exec(ctx context.Context) error {
	n, err := ppdo.ppd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{paymentprofile.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ppdo *PaymentProfileDeleteOne) ExecX(ctx context.Context) {
	if err := ppdo.Exec(ctx); err != nil {
		panic(err)
	}
}
