// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/finance/billing/ent/invoice"
	"gitlab.calendaria.team/services/finance/billing/ent/paymentprofile"
)

// PaymentProfileCreate is the builder for creating a PaymentProfile entity.
type PaymentProfileCreate struct {
	config
	mutation *PaymentProfileMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (ppc *PaymentProfileCreate) SetCreatedAt(t time.Time) *PaymentProfileCreate {
	ppc.mutation.SetCreatedAt(t)
	return ppc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ppc *PaymentProfileCreate) SetNillableCreatedAt(t *time.Time) *PaymentProfileCreate {
	if t != nil {
		ppc.SetCreatedAt(*t)
	}
	return ppc
}

// SetUpdatedAt sets the "updated_at" field.
func (ppc *PaymentProfileCreate) SetUpdatedAt(t time.Time) *PaymentProfileCreate {
	ppc.mutation.SetUpdatedAt(t)
	return ppc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ppc *PaymentProfileCreate) SetNillableUpdatedAt(t *time.Time) *PaymentProfileCreate {
	if t != nil {
		ppc.SetUpdatedAt(*t)
	}
	return ppc
}

// SetDeletedAt sets the "deleted_at" field.
func (ppc *PaymentProfileCreate) SetDeletedAt(t time.Time) *PaymentProfileCreate {
	ppc.mutation.SetDeletedAt(t)
	return ppc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ppc *PaymentProfileCreate) SetNillableDeletedAt(t *time.Time) *PaymentProfileCreate {
	if t != nil {
		ppc.SetDeletedAt(*t)
	}
	return ppc
}

// SetUserID sets the "user_id" field.
func (ppc *PaymentProfileCreate) SetUserID(i int64) *PaymentProfileCreate {
	ppc.mutation.SetUserID(i)
	return ppc
}

// SetPanMasked sets the "pan_masked" field.
func (ppc *PaymentProfileCreate) SetPanMasked(s string) *PaymentProfileCreate {
	ppc.mutation.SetPanMasked(s)
	return ppc
}

// SetHolder sets the "holder" field.
func (ppc *PaymentProfileCreate) SetHolder(s string) *PaymentProfileCreate {
	ppc.mutation.SetHolder(s)
	return ppc
}

// SetEmail sets the "email" field.
func (ppc *PaymentProfileCreate) SetEmail(s string) *PaymentProfileCreate {
	ppc.mutation.SetEmail(s)
	return ppc
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (ppc *PaymentProfileCreate) SetNillableEmail(s *string) *PaymentProfileCreate {
	if s != nil {
		ppc.SetEmail(*s)
	}
	return ppc
}

// SetPhone sets the "phone" field.
func (ppc *PaymentProfileCreate) SetPhone(s string) *PaymentProfileCreate {
	ppc.mutation.SetPhone(s)
	return ppc
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (ppc *PaymentProfileCreate) SetNillablePhone(s *string) *PaymentProfileCreate {
	if s != nil {
		ppc.SetPhone(*s)
	}
	return ppc
}

// SetUserToken sets the "user_token" field.
func (ppc *PaymentProfileCreate) SetUserToken(s string) *PaymentProfileCreate {
	ppc.mutation.SetUserToken(s)
	return ppc
}

// SetNillableUserToken sets the "user_token" field if the given value is not nil.
func (ppc *PaymentProfileCreate) SetNillableUserToken(s *string) *PaymentProfileCreate {
	if s != nil {
		ppc.SetUserToken(*s)
	}
	return ppc
}

// SetRecurrentToken sets the "recurrent_token" field.
func (ppc *PaymentProfileCreate) SetRecurrentToken(s string) *PaymentProfileCreate {
	ppc.mutation.SetRecurrentToken(s)
	return ppc
}

// SetNillableRecurrentToken sets the "recurrent_token" field if the given value is not nil.
func (ppc *PaymentProfileCreate) SetNillableRecurrentToken(s *string) *PaymentProfileCreate {
	if s != nil {
		ppc.SetRecurrentToken(*s)
	}
	return ppc
}

// SetID sets the "id" field.
func (ppc *PaymentProfileCreate) SetID(i int64) *PaymentProfileCreate {
	ppc.mutation.SetID(i)
	return ppc
}

// AddInvoiceIDs adds the "invoices" edge to the Invoice entity by IDs.
func (ppc *PaymentProfileCreate) AddInvoiceIDs(ids ...int64) *PaymentProfileCreate {
	ppc.mutation.AddInvoiceIDs(ids...)
	return ppc
}

// AddInvoices adds the "invoices" edges to the Invoice entity.
func (ppc *PaymentProfileCreate) AddInvoices(i ...*Invoice) *PaymentProfileCreate {
	ids := make([]int64, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return ppc.AddInvoiceIDs(ids...)
}

// Mutation returns the PaymentProfileMutation object of the builder.
func (ppc *PaymentProfileCreate) Mutation() *PaymentProfileMutation {
	return ppc.mutation
}

// Save creates the PaymentProfile in the database.
func (ppc *PaymentProfileCreate) Save(ctx context.Context) (*PaymentProfile, error) {
	if err := ppc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, ppc.sqlSave, ppc.mutation, ppc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ppc *PaymentProfileCreate) SaveX(ctx context.Context) *PaymentProfile {
	v, err := ppc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ppc *PaymentProfileCreate) Exec(ctx context.Context) error {
	_, err := ppc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ppc *PaymentProfileCreate) ExecX(ctx context.Context) {
	if err := ppc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ppc *PaymentProfileCreate) defaults() error {
	if _, ok := ppc.mutation.CreatedAt(); !ok {
		if paymentprofile.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized paymentprofile.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := paymentprofile.DefaultCreatedAt()
		ppc.mutation.SetCreatedAt(v)
	}
	if _, ok := ppc.mutation.UpdatedAt(); !ok {
		if paymentprofile.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized paymentprofile.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := paymentprofile.DefaultUpdatedAt()
		ppc.mutation.SetUpdatedAt(v)
	}
	if _, ok := ppc.mutation.Email(); !ok {
		v := paymentprofile.DefaultEmail
		ppc.mutation.SetEmail(v)
	}
	if _, ok := ppc.mutation.Phone(); !ok {
		v := paymentprofile.DefaultPhone
		ppc.mutation.SetPhone(v)
	}
	if _, ok := ppc.mutation.UserToken(); !ok {
		v := paymentprofile.DefaultUserToken
		ppc.mutation.SetUserToken(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (ppc *PaymentProfileCreate) check() error {
	if _, ok := ppc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PaymentProfile.created_at"`)}
	}
	if _, ok := ppc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PaymentProfile.updated_at"`)}
	}
	if _, ok := ppc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "PaymentProfile.user_id"`)}
	}
	if _, ok := ppc.mutation.PanMasked(); !ok {
		return &ValidationError{Name: "pan_masked", err: errors.New(`ent: missing required field "PaymentProfile.pan_masked"`)}
	}
	if _, ok := ppc.mutation.Holder(); !ok {
		return &ValidationError{Name: "holder", err: errors.New(`ent: missing required field "PaymentProfile.holder"`)}
	}
	return nil
}

func (ppc *PaymentProfileCreate) sqlSave(ctx context.Context) (*PaymentProfile, error) {
	if err := ppc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ppc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ppc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	ppc.mutation.id = &_node.ID
	ppc.mutation.done = true
	return _node, nil
}

func (ppc *PaymentProfileCreate) createSpec() (*PaymentProfile, *sqlgraph.CreateSpec) {
	var (
		_node = &PaymentProfile{config: ppc.config}
		_spec = sqlgraph.NewCreateSpec(paymentprofile.Table, sqlgraph.NewFieldSpec(paymentprofile.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = ppc.conflict
	if id, ok := ppc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ppc.mutation.CreatedAt(); ok {
		_spec.SetField(paymentprofile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ppc.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentprofile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := ppc.mutation.DeletedAt(); ok {
		_spec.SetField(paymentprofile.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := ppc.mutation.UserID(); ok {
		_spec.SetField(paymentprofile.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := ppc.mutation.PanMasked(); ok {
		_spec.SetField(paymentprofile.FieldPanMasked, field.TypeString, value)
		_node.PanMasked = value
	}
	if value, ok := ppc.mutation.Holder(); ok {
		_spec.SetField(paymentprofile.FieldHolder, field.TypeString, value)
		_node.Holder = value
	}
	if value, ok := ppc.mutation.Email(); ok {
		_spec.SetField(paymentprofile.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := ppc.mutation.Phone(); ok {
		_spec.SetField(paymentprofile.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := ppc.mutation.UserToken(); ok {
		_spec.SetField(paymentprofile.FieldUserToken, field.TypeString, value)
		_node.UserToken = value
	}
	if value, ok := ppc.mutation.RecurrentToken(); ok {
		_spec.SetField(paymentprofile.FieldRecurrentToken, field.TypeString, value)
		_node.RecurrentToken = &value
	}
	if nodes := ppc.mutation.InvoicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentprofile.InvoicesTable,
			Columns: []string{paymentprofile.InvoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentProfile.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentProfileUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (ppc *PaymentProfileCreate) OnConflict(opts ...sql.ConflictOption) *PaymentProfileUpsertOne {
	ppc.conflict = opts
	return &PaymentProfileUpsertOne{
		create: ppc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentProfile.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ppc *PaymentProfileCreate) OnConflictColumns(columns ...string) *PaymentProfileUpsertOne {
	ppc.conflict = append(ppc.conflict, sql.ConflictColumns(columns...))
	return &PaymentProfileUpsertOne{
		create: ppc,
	}
}

type (
	// PaymentProfileUpsertOne is the builder for "upsert"-ing
	//  one PaymentProfile node.
	PaymentProfileUpsertOne struct {
		create *PaymentProfileCreate
	}

	// PaymentProfileUpsert is the "OnConflict" setter.
	PaymentProfileUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentProfileUpsert) SetUpdatedAt(v time.Time) *PaymentProfileUpsert {
	u.Set(paymentprofile.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentProfileUpsert) UpdateUpdatedAt() *PaymentProfileUpsert {
	u.SetExcluded(paymentprofile.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PaymentProfileUpsert) SetDeletedAt(v time.Time) *PaymentProfileUpsert {
	u.Set(paymentprofile.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PaymentProfileUpsert) UpdateDeletedAt() *PaymentProfileUpsert {
	u.SetExcluded(paymentprofile.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PaymentProfileUpsert) ClearDeletedAt() *PaymentProfileUpsert {
	u.SetNull(paymentprofile.FieldDeletedAt)
	return u
}

// SetEmail sets the "email" field.
func (u *PaymentProfileUpsert) SetEmail(v string) *PaymentProfileUpsert {
	u.Set(paymentprofile.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *PaymentProfileUpsert) UpdateEmail() *PaymentProfileUpsert {
	u.SetExcluded(paymentprofile.FieldEmail)
	return u
}

// ClearEmail clears the value of the "email" field.
func (u *PaymentProfileUpsert) ClearEmail() *PaymentProfileUpsert {
	u.SetNull(paymentprofile.FieldEmail)
	return u
}

// SetPhone sets the "phone" field.
func (u *PaymentProfileUpsert) SetPhone(v string) *PaymentProfileUpsert {
	u.Set(paymentprofile.FieldPhone, v)
	return u
}

// UpdatePhone sets the "phone" field to the value that was provided on create.
func (u *PaymentProfileUpsert) UpdatePhone() *PaymentProfileUpsert {
	u.SetExcluded(paymentprofile.FieldPhone)
	return u
}

// ClearPhone clears the value of the "phone" field.
func (u *PaymentProfileUpsert) ClearPhone() *PaymentProfileUpsert {
	u.SetNull(paymentprofile.FieldPhone)
	return u
}

// SetUserToken sets the "user_token" field.
func (u *PaymentProfileUpsert) SetUserToken(v string) *PaymentProfileUpsert {
	u.Set(paymentprofile.FieldUserToken, v)
	return u
}

// UpdateUserToken sets the "user_token" field to the value that was provided on create.
func (u *PaymentProfileUpsert) UpdateUserToken() *PaymentProfileUpsert {
	u.SetExcluded(paymentprofile.FieldUserToken)
	return u
}

// ClearUserToken clears the value of the "user_token" field.
func (u *PaymentProfileUpsert) ClearUserToken() *PaymentProfileUpsert {
	u.SetNull(paymentprofile.FieldUserToken)
	return u
}

// SetRecurrentToken sets the "recurrent_token" field.
func (u *PaymentProfileUpsert) SetRecurrentToken(v string) *PaymentProfileUpsert {
	u.Set(paymentprofile.FieldRecurrentToken, v)
	return u
}

// UpdateRecurrentToken sets the "recurrent_token" field to the value that was provided on create.
func (u *PaymentProfileUpsert) UpdateRecurrentToken() *PaymentProfileUpsert {
	u.SetExcluded(paymentprofile.FieldRecurrentToken)
	return u
}

// ClearRecurrentToken clears the value of the "recurrent_token" field.
func (u *PaymentProfileUpsert) ClearRecurrentToken() *PaymentProfileUpsert {
	u.SetNull(paymentprofile.FieldRecurrentToken)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PaymentProfile.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(paymentprofile.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PaymentProfileUpsertOne) UpdateNewValues() *PaymentProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(paymentprofile.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(paymentprofile.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(paymentprofile.FieldUserID)
		}
		if _, exists := u.create.mutation.PanMasked(); exists {
			s.SetIgnore(paymentprofile.FieldPanMasked)
		}
		if _, exists := u.create.mutation.Holder(); exists {
			s.SetIgnore(paymentprofile.FieldHolder)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentProfile.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PaymentProfileUpsertOne) Ignore() *PaymentProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentProfileUpsertOne) DoNothing() *PaymentProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentProfileCreate.OnConflict
// documentation for more info.
func (u *PaymentProfileUpsertOne) Update(set func(*PaymentProfileUpsert)) *PaymentProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentProfileUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentProfileUpsertOne) SetUpdatedAt(v time.Time) *PaymentProfileUpsertOne {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentProfileUpsertOne) UpdateUpdatedAt() *PaymentProfileUpsertOne {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PaymentProfileUpsertOne) SetDeletedAt(v time.Time) *PaymentProfileUpsertOne {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PaymentProfileUpsertOne) UpdateDeletedAt() *PaymentProfileUpsertOne {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PaymentProfileUpsertOne) ClearDeletedAt() *PaymentProfileUpsertOne {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.ClearDeletedAt()
	})
}

// SetEmail sets the "email" field.
func (u *PaymentProfileUpsertOne) SetEmail(v string) *PaymentProfileUpsertOne {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *PaymentProfileUpsertOne) UpdateEmail() *PaymentProfileUpsertOne {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.UpdateEmail()
	})
}

// ClearEmail clears the value of the "email" field.
func (u *PaymentProfileUpsertOne) ClearEmail() *PaymentProfileUpsertOne {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.ClearEmail()
	})
}

// SetPhone sets the "phone" field.
func (u *PaymentProfileUpsertOne) SetPhone(v string) *PaymentProfileUpsertOne {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.SetPhone(v)
	})
}

// UpdatePhone sets the "phone" field to the value that was provided on create.
func (u *PaymentProfileUpsertOne) UpdatePhone() *PaymentProfileUpsertOne {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.UpdatePhone()
	})
}

// ClearPhone clears the value of the "phone" field.
func (u *PaymentProfileUpsertOne) ClearPhone() *PaymentProfileUpsertOne {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.ClearPhone()
	})
}

// SetUserToken sets the "user_token" field.
func (u *PaymentProfileUpsertOne) SetUserToken(v string) *PaymentProfileUpsertOne {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.SetUserToken(v)
	})
}

// UpdateUserToken sets the "user_token" field to the value that was provided on create.
func (u *PaymentProfileUpsertOne) UpdateUserToken() *PaymentProfileUpsertOne {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.UpdateUserToken()
	})
}

// ClearUserToken clears the value of the "user_token" field.
func (u *PaymentProfileUpsertOne) ClearUserToken() *PaymentProfileUpsertOne {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.ClearUserToken()
	})
}

// SetRecurrentToken sets the "recurrent_token" field.
func (u *PaymentProfileUpsertOne) SetRecurrentToken(v string) *PaymentProfileUpsertOne {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.SetRecurrentToken(v)
	})
}

// UpdateRecurrentToken sets the "recurrent_token" field to the value that was provided on create.
func (u *PaymentProfileUpsertOne) UpdateRecurrentToken() *PaymentProfileUpsertOne {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.UpdateRecurrentToken()
	})
}

// ClearRecurrentToken clears the value of the "recurrent_token" field.
func (u *PaymentProfileUpsertOne) ClearRecurrentToken() *PaymentProfileUpsertOne {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.ClearRecurrentToken()
	})
}

// Exec executes the query.
func (u *PaymentProfileUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentProfileCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentProfileUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PaymentProfileUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PaymentProfileUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PaymentProfileCreateBulk is the builder for creating many PaymentProfile entities in bulk.
type PaymentProfileCreateBulk struct {
	config
	err      error
	builders []*PaymentProfileCreate
	conflict []sql.ConflictOption
}

// Save creates the PaymentProfile entities in the database.
func (ppcb *PaymentProfileCreateBulk) Save(ctx context.Context) ([]*PaymentProfile, error) {
	if ppcb.err != nil {
		return nil, ppcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ppcb.builders))
	nodes := make([]*PaymentProfile, len(ppcb.builders))
	mutators := make([]Mutator, len(ppcb.builders))
	for i := range ppcb.builders {
		func(i int, root context.Context) {
			builder := ppcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentProfileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ppcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = ppcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ppcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ppcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ppcb *PaymentProfileCreateBulk) SaveX(ctx context.Context) []*PaymentProfile {
	v, err := ppcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ppcb *PaymentProfileCreateBulk) Exec(ctx context.Context) error {
	_, err := ppcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ppcb *PaymentProfileCreateBulk) ExecX(ctx context.Context) {
	if err := ppcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentProfile.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentProfileUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (ppcb *PaymentProfileCreateBulk) OnConflict(opts ...sql.ConflictOption) *PaymentProfileUpsertBulk {
	ppcb.conflict = opts
	return &PaymentProfileUpsertBulk{
		create: ppcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentProfile.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ppcb *PaymentProfileCreateBulk) OnConflictColumns(columns ...string) *PaymentProfileUpsertBulk {
	ppcb.conflict = append(ppcb.conflict, sql.ConflictColumns(columns...))
	return &PaymentProfileUpsertBulk{
		create: ppcb,
	}
}

// PaymentProfileUpsertBulk is the builder for "upsert"-ing
// a bulk of PaymentProfile nodes.
type PaymentProfileUpsertBulk struct {
	create *PaymentProfileCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PaymentProfile.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(paymentprofile.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PaymentProfileUpsertBulk) UpdateNewValues() *PaymentProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(paymentprofile.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(paymentprofile.FieldCreatedAt)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(paymentprofile.FieldUserID)
			}
			if _, exists := b.mutation.PanMasked(); exists {
				s.SetIgnore(paymentprofile.FieldPanMasked)
			}
			if _, exists := b.mutation.Holder(); exists {
				s.SetIgnore(paymentprofile.FieldHolder)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentProfile.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PaymentProfileUpsertBulk) Ignore() *PaymentProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentProfileUpsertBulk) DoNothing() *PaymentProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentProfileCreateBulk.OnConflict
// documentation for more info.
func (u *PaymentProfileUpsertBulk) Update(set func(*PaymentProfileUpsert)) *PaymentProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentProfileUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentProfileUpsertBulk) SetUpdatedAt(v time.Time) *PaymentProfileUpsertBulk {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentProfileUpsertBulk) UpdateUpdatedAt() *PaymentProfileUpsertBulk {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PaymentProfileUpsertBulk) SetDeletedAt(v time.Time) *PaymentProfileUpsertBulk {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PaymentProfileUpsertBulk) UpdateDeletedAt() *PaymentProfileUpsertBulk {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PaymentProfileUpsertBulk) ClearDeletedAt() *PaymentProfileUpsertBulk {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.ClearDeletedAt()
	})
}

// SetEmail sets the "email" field.
func (u *PaymentProfileUpsertBulk) SetEmail(v string) *PaymentProfileUpsertBulk {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *PaymentProfileUpsertBulk) UpdateEmail() *PaymentProfileUpsertBulk {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.UpdateEmail()
	})
}

// ClearEmail clears the value of the "email" field.
func (u *PaymentProfileUpsertBulk) ClearEmail() *PaymentProfileUpsertBulk {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.ClearEmail()
	})
}

// SetPhone sets the "phone" field.
func (u *PaymentProfileUpsertBulk) SetPhone(v string) *PaymentProfileUpsertBulk {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.SetPhone(v)
	})
}

// UpdatePhone sets the "phone" field to the value that was provided on create.
func (u *PaymentProfileUpsertBulk) UpdatePhone() *PaymentProfileUpsertBulk {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.UpdatePhone()
	})
}

// ClearPhone clears the value of the "phone" field.
func (u *PaymentProfileUpsertBulk) ClearPhone() *PaymentProfileUpsertBulk {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.ClearPhone()
	})
}

// SetUserToken sets the "user_token" field.
func (u *PaymentProfileUpsertBulk) SetUserToken(v string) *PaymentProfileUpsertBulk {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.SetUserToken(v)
	})
}

// UpdateUserToken sets the "user_token" field to the value that was provided on create.
func (u *PaymentProfileUpsertBulk) UpdateUserToken() *PaymentProfileUpsertBulk {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.UpdateUserToken()
	})
}

// ClearUserToken clears the value of the "user_token" field.
func (u *PaymentProfileUpsertBulk) ClearUserToken() *PaymentProfileUpsertBulk {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.ClearUserToken()
	})
}

// SetRecurrentToken sets the "recurrent_token" field.
func (u *PaymentProfileUpsertBulk) SetRecurrentToken(v string) *PaymentProfileUpsertBulk {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.SetRecurrentToken(v)
	})
}

// UpdateRecurrentToken sets the "recurrent_token" field to the value that was provided on create.
func (u *PaymentProfileUpsertBulk) UpdateRecurrentToken() *PaymentProfileUpsertBulk {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.UpdateRecurrentToken()
	})
}

// ClearRecurrentToken clears the value of the "recurrent_token" field.
func (u *PaymentProfileUpsertBulk) ClearRecurrentToken() *PaymentProfileUpsertBulk {
	return u.Update(func(s *PaymentProfileUpsert) {
		s.ClearRecurrentToken()
	})
}

// Exec executes the query.
func (u *PaymentProfileUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PaymentProfileCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentProfileCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentProfileUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
