// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/finance/billing/ent/enum"
	"gitlab.calendaria.team/services/finance/billing/ent/predicate"
	"gitlab.calendaria.team/services/finance/billing/ent/productreservation"
)

// ProductReservationUpdate is the builder for updating ProductReservation entities.
type ProductReservationUpdate struct {
	config
	hooks     []Hook
	mutation  *ProductReservationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ProductReservationUpdate builder.
func (pru *ProductReservationUpdate) Where(ps ...predicate.ProductReservation) *ProductReservationUpdate {
	pru.mutation.Where(ps...)
	return pru
}

// SetUpdatedAt sets the "updated_at" field.
func (pru *ProductReservationUpdate) SetUpdatedAt(t time.Time) *ProductReservationUpdate {
	pru.mutation.SetUpdatedAt(t)
	return pru
}

// SetReservedQuantity sets the "reserved_quantity" field.
func (pru *ProductReservationUpdate) SetReservedQuantity(i int64) *ProductReservationUpdate {
	pru.mutation.ResetReservedQuantity()
	pru.mutation.SetReservedQuantity(i)
	return pru
}

// SetNillableReservedQuantity sets the "reserved_quantity" field if the given value is not nil.
func (pru *ProductReservationUpdate) SetNillableReservedQuantity(i *int64) *ProductReservationUpdate {
	if i != nil {
		pru.SetReservedQuantity(*i)
	}
	return pru
}

// AddReservedQuantity adds i to the "reserved_quantity" field.
func (pru *ProductReservationUpdate) AddReservedQuantity(i int64) *ProductReservationUpdate {
	pru.mutation.AddReservedQuantity(i)
	return pru
}

// SetStatus sets the "status" field.
func (pru *ProductReservationUpdate) SetStatus(es enum.ReservationStatus) *ProductReservationUpdate {
	pru.mutation.SetStatus(es)
	return pru
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pru *ProductReservationUpdate) SetNillableStatus(es *enum.ReservationStatus) *ProductReservationUpdate {
	if es != nil {
		pru.SetStatus(*es)
	}
	return pru
}

// SetExpirationTime sets the "expiration_time" field.
func (pru *ProductReservationUpdate) SetExpirationTime(t time.Time) *ProductReservationUpdate {
	pru.mutation.SetExpirationTime(t)
	return pru
}

// SetNillableExpirationTime sets the "expiration_time" field if the given value is not nil.
func (pru *ProductReservationUpdate) SetNillableExpirationTime(t *time.Time) *ProductReservationUpdate {
	if t != nil {
		pru.SetExpirationTime(*t)
	}
	return pru
}

// Mutation returns the ProductReservationMutation object of the builder.
func (pru *ProductReservationUpdate) Mutation() *ProductReservationMutation {
	return pru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pru *ProductReservationUpdate) Save(ctx context.Context) (int, error) {
	pru.defaults()
	return withHooks(ctx, pru.sqlSave, pru.mutation, pru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pru *ProductReservationUpdate) SaveX(ctx context.Context) int {
	affected, err := pru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pru *ProductReservationUpdate) Exec(ctx context.Context) error {
	_, err := pru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pru *ProductReservationUpdate) ExecX(ctx context.Context) {
	if err := pru.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pru *ProductReservationUpdate) defaults() {
	if _, ok := pru.mutation.UpdatedAt(); !ok {
		v := productreservation.UpdateDefaultUpdatedAt()
		pru.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pru *ProductReservationUpdate) check() error {
	if v, ok := pru.mutation.ReservedQuantity(); ok {
		if err := productreservation.ReservedQuantityValidator(v); err != nil {
			return &ValidationError{Name: "reserved_quantity", err: fmt.Errorf(`ent: validator failed for field "ProductReservation.reserved_quantity": %w`, err)}
		}
	}
	if v, ok := pru.mutation.Status(); ok {
		if err := productreservation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProductReservation.status": %w`, err)}
		}
	}
	if pru.mutation.ProductCleared() && len(pru.mutation.ProductIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProductReservation.product"`)
	}
	if pru.mutation.InvoiceCleared() && len(pru.mutation.InvoiceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProductReservation.invoice"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (pru *ProductReservationUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ProductReservationUpdate {
	pru.modifiers = append(pru.modifiers, modifiers...)
	return pru
}

func (pru *ProductReservationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(productreservation.Table, productreservation.Columns, sqlgraph.NewFieldSpec(productreservation.FieldID, field.TypeInt64))
	if ps := pru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pru.mutation.UpdatedAt(); ok {
		_spec.SetField(productreservation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := pru.mutation.ReservedQuantity(); ok {
		_spec.SetField(productreservation.FieldReservedQuantity, field.TypeInt64, value)
	}
	if value, ok := pru.mutation.AddedReservedQuantity(); ok {
		_spec.AddField(productreservation.FieldReservedQuantity, field.TypeInt64, value)
	}
	if value, ok := pru.mutation.Status(); ok {
		_spec.SetField(productreservation.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := pru.mutation.ExpirationTime(); ok {
		_spec.SetField(productreservation.FieldExpirationTime, field.TypeTime, value)
	}
	_spec.AddModifiers(pru.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, pru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{productreservation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pru.mutation.done = true
	return n, nil
}

// ProductReservationUpdateOne is the builder for updating a single ProductReservation entity.
type ProductReservationUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ProductReservationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (pruo *ProductReservationUpdateOne) SetUpdatedAt(t time.Time) *ProductReservationUpdateOne {
	pruo.mutation.SetUpdatedAt(t)
	return pruo
}

// SetReservedQuantity sets the "reserved_quantity" field.
func (pruo *ProductReservationUpdateOne) SetReservedQuantity(i int64) *ProductReservationUpdateOne {
	pruo.mutation.ResetReservedQuantity()
	pruo.mutation.SetReservedQuantity(i)
	return pruo
}

// SetNillableReservedQuantity sets the "reserved_quantity" field if the given value is not nil.
func (pruo *ProductReservationUpdateOne) SetNillableReservedQuantity(i *int64) *ProductReservationUpdateOne {
	if i != nil {
		pruo.SetReservedQuantity(*i)
	}
	return pruo
}

// AddReservedQuantity adds i to the "reserved_quantity" field.
func (pruo *ProductReservationUpdateOne) AddReservedQuantity(i int64) *ProductReservationUpdateOne {
	pruo.mutation.AddReservedQuantity(i)
	return pruo
}

// SetStatus sets the "status" field.
func (pruo *ProductReservationUpdateOne) SetStatus(es enum.ReservationStatus) *ProductReservationUpdateOne {
	pruo.mutation.SetStatus(es)
	return pruo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pruo *ProductReservationUpdateOne) SetNillableStatus(es *enum.ReservationStatus) *ProductReservationUpdateOne {
	if es != nil {
		pruo.SetStatus(*es)
	}
	return pruo
}

// SetExpirationTime sets the "expiration_time" field.
func (pruo *ProductReservationUpdateOne) SetExpirationTime(t time.Time) *ProductReservationUpdateOne {
	pruo.mutation.SetExpirationTime(t)
	return pruo
}

// SetNillableExpirationTime sets the "expiration_time" field if the given value is not nil.
func (pruo *ProductReservationUpdateOne) SetNillableExpirationTime(t *time.Time) *ProductReservationUpdateOne {
	if t != nil {
		pruo.SetExpirationTime(*t)
	}
	return pruo
}

// Mutation returns the ProductReservationMutation object of the builder.
func (pruo *ProductReservationUpdateOne) Mutation() *ProductReservationMutation {
	return pruo.mutation
}

// Where appends a list predicates to the ProductReservationUpdate builder.
func (pruo *ProductReservationUpdateOne) Where(ps ...predicate.ProductReservation) *ProductReservationUpdateOne {
	pruo.mutation.Where(ps...)
	return pruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pruo *ProductReservationUpdateOne) Select(field string, fields ...string) *ProductReservationUpdateOne {
	pruo.fields = append([]string{field}, fields...)
	return pruo
}

// Save executes the query and returns the updated ProductReservation entity.
func (pruo *ProductReservationUpdateOne) Save(ctx context.Context) (*ProductReservation, error) {
	pruo.defaults()
	return withHooks(ctx, pruo.sqlSave, pruo.mutation, pruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pruo *ProductReservationUpdateOne) SaveX(ctx context.Context) *ProductReservation {
	node, err := pruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pruo *ProductReservationUpdateOne) Exec(ctx context.Context) error {
	_, err := pruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pruo *ProductReservationUpdateOne) ExecX(ctx context.Context) {
	if err := pruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pruo *ProductReservationUpdateOne) defaults() {
	if _, ok := pruo.mutation.UpdatedAt(); !ok {
		v := productreservation.UpdateDefaultUpdatedAt()
		pruo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pruo *ProductReservationUpdateOne) check() error {
	if v, ok := pruo.mutation.ReservedQuantity(); ok {
		if err := productreservation.ReservedQuantityValidator(v); err != nil {
			return &ValidationError{Name: "reserved_quantity", err: fmt.Errorf(`ent: validator failed for field "ProductReservation.reserved_quantity": %w`, err)}
		}
	}
	if v, ok := pruo.mutation.Status(); ok {
		if err := productreservation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProductReservation.status": %w`, err)}
		}
	}
	if pruo.mutation.ProductCleared() && len(pruo.mutation.ProductIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProductReservation.product"`)
	}
	if pruo.mutation.InvoiceCleared() && len(pruo.mutation.InvoiceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProductReservation.invoice"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (pruo *ProductReservationUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ProductReservationUpdateOne {
	pruo.modifiers = append(pruo.modifiers, modifiers...)
	return pruo
}

func (pruo *ProductReservationUpdateOne) sqlSave(ctx context.Context) (_node *ProductReservation, err error) {
	if err := pruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(productreservation.Table, productreservation.Columns, sqlgraph.NewFieldSpec(productreservation.FieldID, field.TypeInt64))
	id, ok := pruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProductReservation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := pruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, productreservation.FieldID)
		for _, f := range fields {
			if !productreservation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != productreservation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := pruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pruo.mutation.UpdatedAt(); ok {
		_spec.SetField(productreservation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := pruo.mutation.ReservedQuantity(); ok {
		_spec.SetField(productreservation.FieldReservedQuantity, field.TypeInt64, value)
	}
	if value, ok := pruo.mutation.AddedReservedQuantity(); ok {
		_spec.AddField(productreservation.FieldReservedQuantity, field.TypeInt64, value)
	}
	if value, ok := pruo.mutation.Status(); ok {
		_spec.SetField(productreservation.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := pruo.mutation.ExpirationTime(); ok {
		_spec.SetField(productreservation.FieldExpirationTime, field.TypeTime, value)
	}
	_spec.AddModifiers(pruo.modifiers...)
	_node = &ProductReservation{config: pruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{productreservation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	pruo.mutation.done = true
	return _node, nil
}
