// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/makesalekz/billing/ent/predicate"
	"github.com/makesalekz/billing/ent/productreservation"
)

// ProductReservationDelete is the builder for deleting a ProductReservation entity.
type ProductReservationDelete struct {
	config
	hooks    []Hook
	mutation *ProductReservationMutation
}

// Where appends a list predicates to the ProductReservationDelete builder.
func (prd *ProductReservationDelete) Where(ps ...predicate.ProductReservation) *ProductReservationDelete {
	prd.mutation.Where(ps...)
	return prd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (prd *ProductReservationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, prd.sqlExec, prd.mutation, prd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (prd *ProductReservationDelete) ExecX(ctx context.Context) int {
	n, err := prd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (prd *ProductReservationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(productreservation.Table, sqlgraph.NewFieldSpec(productreservation.FieldID, field.TypeInt64))
	if ps := prd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, prd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	prd.mutation.done = true
	return affected, err
}

// ProductReservationDeleteOne is the builder for deleting a single ProductReservation entity.
type ProductReservationDeleteOne struct {
	prd *ProductReservationDelete
}

// Where appends a list predicates to the ProductReservationDelete builder.
func (prdo *ProductReservationDeleteOne) Where(ps ...predicate.ProductReservation) *ProductReservationDeleteOne {
	prdo.prd.mutation.Where(ps...)
	return prdo
}

// Exec executes the deletion query.
func (prdo *ProductReservationDeleteOne) Exec(ctx context.Context) error {
	n, err := prdo.prd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{productreservation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (prdo *ProductReservationDeleteOne) ExecX(ctx context.Context) {
	if err := prdo.Exec(ctx); err != nil {
		panic(err)
	}
}
