// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"gitlab.calendaria.team/services/finance/invoices/ent/invoice"
	"gitlab.calendaria.team/services/finance/invoices/ent/item"
	"gitlab.calendaria.team/services/finance/invoices/ent/subscriptionstatus"
)

// SubscriptionStatus is the model entity for the SubscriptionStatus schema.
type SubscriptionStatus struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// InvoiceID holds the value of the "invoice_id" field.
	InvoiceID int64 `json:"invoice_id,omitempty"`
	// ItemID holds the value of the "item_id" field.
	ItemID int64 `json:"item_id,omitempty"`
	// ActiveTill holds the value of the "active_till" field.
	ActiveTill time.Time `json:"active_till,omitempty"`
	// StartFrom holds the value of the "start_from" field.
	StartFrom time.Time `json:"start_from,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubscriptionStatusQuery when eager-loading is set.
	Edges        SubscriptionStatusEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SubscriptionStatusEdges holds the relations/edges for other nodes in the graph.
type SubscriptionStatusEdges struct {
	// Invoice holds the value of the invoice edge.
	Invoice *Invoice `json:"invoice,omitempty"`
	// Item holds the value of the item edge.
	Item *Item `json:"item,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// InvoiceOrErr returns the Invoice value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionStatusEdges) InvoiceOrErr() (*Invoice, error) {
	if e.Invoice != nil {
		return e.Invoice, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: invoice.Label}
	}
	return nil, &NotLoadedError{edge: "invoice"}
}

// ItemOrErr returns the Item value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionStatusEdges) ItemOrErr() (*Item, error) {
	if e.Item != nil {
		return e.Item, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: item.Label}
	}
	return nil, &NotLoadedError{edge: "item"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubscriptionStatus) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscriptionstatus.FieldID, subscriptionstatus.FieldInvoiceID, subscriptionstatus.FieldItemID:
			values[i] = new(sql.NullInt64)
		case subscriptionstatus.FieldActiveTill, subscriptionstatus.FieldStartFrom:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubscriptionStatus fields.
func (ss *SubscriptionStatus) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscriptionstatus.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ss.ID = int64(value.Int64)
		case subscriptionstatus.FieldInvoiceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_id", values[i])
			} else if value.Valid {
				ss.InvoiceID = value.Int64
			}
		case subscriptionstatus.FieldItemID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field item_id", values[i])
			} else if value.Valid {
				ss.ItemID = value.Int64
			}
		case subscriptionstatus.FieldActiveTill:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field active_till", values[i])
			} else if value.Valid {
				ss.ActiveTill = value.Time
			}
		case subscriptionstatus.FieldStartFrom:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_from", values[i])
			} else if value.Valid {
				ss.StartFrom = value.Time
			}
		default:
			ss.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubscriptionStatus.
// This includes values selected through modifiers, order, etc.
func (ss *SubscriptionStatus) Value(name string) (ent.Value, error) {
	return ss.selectValues.Get(name)
}

// QueryInvoice queries the "invoice" edge of the SubscriptionStatus entity.
func (ss *SubscriptionStatus) QueryInvoice() *InvoiceQuery {
	return NewSubscriptionStatusClient(ss.config).QueryInvoice(ss)
}

// QueryItem queries the "item" edge of the SubscriptionStatus entity.
func (ss *SubscriptionStatus) QueryItem() *ItemQuery {
	return NewSubscriptionStatusClient(ss.config).QueryItem(ss)
}

// Update returns a builder for updating this SubscriptionStatus.
// Note that you need to call SubscriptionStatus.Unwrap() before calling this method if this SubscriptionStatus
// was returned from a transaction, and the transaction was committed or rolled back.
func (ss *SubscriptionStatus) Update() *SubscriptionStatusUpdateOne {
	return NewSubscriptionStatusClient(ss.config).UpdateOne(ss)
}

// Unwrap unwraps the SubscriptionStatus entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ss *SubscriptionStatus) Unwrap() *SubscriptionStatus {
	_tx, ok := ss.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubscriptionStatus is not a transactional entity")
	}
	ss.config.driver = _tx.drv
	return ss
}

// String implements the fmt.Stringer.
func (ss *SubscriptionStatus) String() string {
	var builder strings.Builder
	builder.WriteString("SubscriptionStatus(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ss.ID))
	builder.WriteString("invoice_id=")
	builder.WriteString(fmt.Sprintf("%v", ss.InvoiceID))
	builder.WriteString(", ")
	builder.WriteString("item_id=")
	builder.WriteString(fmt.Sprintf("%v", ss.ItemID))
	builder.WriteString(", ")
	builder.WriteString("active_till=")
	builder.WriteString(ss.ActiveTill.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("start_from=")
	builder.WriteString(ss.StartFrom.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SubscriptionStatusSlice is a parsable slice of SubscriptionStatus.
type SubscriptionStatusSlice []*SubscriptionStatus
