// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/finance/invoices/ent/predicate"
	"gitlab.calendaria.team/services/finance/invoices/ent/subscriptionstatus"
)

// SubscriptionStatusDelete is the builder for deleting a SubscriptionStatus entity.
type SubscriptionStatusDelete struct {
	config
	hooks    []Hook
	mutation *SubscriptionStatusMutation
}

// Where appends a list predicates to the SubscriptionStatusDelete builder.
func (ssd *SubscriptionStatusDelete) Where(ps ...predicate.SubscriptionStatus) *SubscriptionStatusDelete {
	ssd.mutation.Where(ps...)
	return ssd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ssd *SubscriptionStatusDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ssd.sqlExec, ssd.mutation, ssd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ssd *SubscriptionStatusDelete) ExecX(ctx context.Context) int {
	n, err := ssd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ssd *SubscriptionStatusDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(subscriptionstatus.Table, sqlgraph.NewFieldSpec(subscriptionstatus.FieldID, field.TypeInt64))
	if ps := ssd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ssd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ssd.mutation.done = true
	return affected, err
}

// SubscriptionStatusDeleteOne is the builder for deleting a single SubscriptionStatus entity.
type SubscriptionStatusDeleteOne struct {
	ssd *SubscriptionStatusDelete
}

// Where appends a list predicates to the SubscriptionStatusDelete builder.
func (ssdo *SubscriptionStatusDeleteOne) Where(ps ...predicate.SubscriptionStatus) *SubscriptionStatusDeleteOne {
	ssdo.ssd.mutation.Where(ps...)
	return ssdo
}

// Exec executes the deletion query.
func (ssdo *SubscriptionStatusDeleteOne) Exec(ctx context.Context) error {
	n, err := ssdo.ssd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{subscriptionstatus.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ssdo *SubscriptionStatusDeleteOne) ExecX(ctx context.Context) {
	if err := ssdo.Exec(ctx); err != nil {
		panic(err)
	}
}
