// Code generated by ent, DO NOT EDIT.

package intercept

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"gitlab.calendaria.team/services/finance/billing/ent"
	"gitlab.calendaria.team/services/finance/billing/ent/bundle"
	"gitlab.calendaria.team/services/finance/billing/ent/invoice"
	"gitlab.calendaria.team/services/finance/billing/ent/item"
	"gitlab.calendaria.team/services/finance/billing/ent/predicate"
	"gitlab.calendaria.team/services/finance/billing/ent/product"
	"gitlab.calendaria.team/services/finance/billing/ent/subscriptions"
)

// The Query interface represents an operation that queries a graph.
// By using this interface, users can write generic code that manipulates
// query builders of different types.
type Query interface {
	// Type returns the string representation of the query type.
	Type() string
	// Limit the number of records to be returned by this query.
	Limit(int)
	// Offset to start from.
	Offset(int)
	// Unique configures the query builder to filter duplicate records.
	Unique(bool)
	// Order specifies how the records should be ordered.
	Order(...func(*sql.Selector))
	// WhereP appends storage-level predicates to the query builder. Using this method, users
	// can use type-assertion to append predicates that do not depend on any generated package.
	WhereP(...func(*sql.Selector))
}

// The Func type is an adapter that allows ordinary functions to be used as interceptors.
// Unlike traversal functions, interceptors are skipped during graph traversals. Note that the
// implementation of Func is different from the one defined in entgo.io/ent.InterceptFunc.
type Func func(context.Context, Query) error

// Intercept calls f(ctx, q) and then applied the next Querier.
func (f Func) Intercept(next ent.Querier) ent.Querier {
	return ent.QuerierFunc(func(ctx context.Context, q ent.Query) (ent.Value, error) {
		query, err := NewQuery(q)
		if err != nil {
			return nil, err
		}
		if err := f(ctx, query); err != nil {
			return nil, err
		}
		return next.Query(ctx, q)
	})
}

// The TraverseFunc type is an adapter to allow the use of ordinary function as Traverser.
// If f is a function with the appropriate signature, TraverseFunc(f) is a Traverser that calls f.
type TraverseFunc func(context.Context, Query) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseFunc) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseFunc) Traverse(ctx context.Context, q ent.Query) error {
	query, err := NewQuery(q)
	if err != nil {
		return err
	}
	return f(ctx, query)
}

// The BundleFunc type is an adapter to allow the use of ordinary function as a Querier.
type BundleFunc func(context.Context, *ent.BundleQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f BundleFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.BundleQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.BundleQuery", q)
}

// The TraverseBundle type is an adapter to allow the use of ordinary function as Traverser.
type TraverseBundle func(context.Context, *ent.BundleQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseBundle) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseBundle) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.BundleQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.BundleQuery", q)
}

// The InvoiceFunc type is an adapter to allow the use of ordinary function as a Querier.
type InvoiceFunc func(context.Context, *ent.InvoiceQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f InvoiceFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.InvoiceQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.InvoiceQuery", q)
}

// The TraverseInvoice type is an adapter to allow the use of ordinary function as Traverser.
type TraverseInvoice func(context.Context, *ent.InvoiceQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseInvoice) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseInvoice) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.InvoiceQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.InvoiceQuery", q)
}

// The ItemFunc type is an adapter to allow the use of ordinary function as a Querier.
type ItemFunc func(context.Context, *ent.ItemQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ItemFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ItemQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ItemQuery", q)
}

// The TraverseItem type is an adapter to allow the use of ordinary function as Traverser.
type TraverseItem func(context.Context, *ent.ItemQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseItem) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseItem) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ItemQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ItemQuery", q)
}

// The ProductFunc type is an adapter to allow the use of ordinary function as a Querier.
type ProductFunc func(context.Context, *ent.ProductQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ProductFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ProductQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ProductQuery", q)
}

// The TraverseProduct type is an adapter to allow the use of ordinary function as Traverser.
type TraverseProduct func(context.Context, *ent.ProductQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseProduct) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseProduct) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ProductQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ProductQuery", q)
}

// The SubscriptionsFunc type is an adapter to allow the use of ordinary function as a Querier.
type SubscriptionsFunc func(context.Context, *ent.SubscriptionsQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SubscriptionsFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SubscriptionsQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SubscriptionsQuery", q)
}

// The TraverseSubscriptions type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSubscriptions func(context.Context, *ent.SubscriptionsQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSubscriptions) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSubscriptions) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SubscriptionsQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SubscriptionsQuery", q)
}

// NewQuery returns the generic Query interface for the given typed query.
func NewQuery(q ent.Query) (Query, error) {
	switch q := q.(type) {
	case *ent.BundleQuery:
		return &query[*ent.BundleQuery, predicate.Bundle, bundle.OrderOption]{typ: ent.TypeBundle, tq: q}, nil
	case *ent.InvoiceQuery:
		return &query[*ent.InvoiceQuery, predicate.Invoice, invoice.OrderOption]{typ: ent.TypeInvoice, tq: q}, nil
	case *ent.ItemQuery:
		return &query[*ent.ItemQuery, predicate.Item, item.OrderOption]{typ: ent.TypeItem, tq: q}, nil
	case *ent.ProductQuery:
		return &query[*ent.ProductQuery, predicate.Product, product.OrderOption]{typ: ent.TypeProduct, tq: q}, nil
	case *ent.SubscriptionsQuery:
		return &query[*ent.SubscriptionsQuery, predicate.Subscriptions, subscriptions.OrderOption]{typ: ent.TypeSubscriptions, tq: q}, nil
	default:
		return nil, fmt.Errorf("unknown query type %T", q)
	}
}

type query[T any, P ~func(*sql.Selector), R ~func(*sql.Selector)] struct {
	typ string
	tq  interface {
		Limit(int) T
		Offset(int) T
		Unique(bool) T
		Order(...R) T
		Where(...P) T
	}
}

func (q query[T, P, R]) Type() string {
	return q.typ
}

func (q query[T, P, R]) Limit(limit int) {
	q.tq.Limit(limit)
}

func (q query[T, P, R]) Offset(offset int) {
	q.tq.Offset(offset)
}

func (q query[T, P, R]) Unique(unique bool) {
	q.tq.Unique(unique)
}

func (q query[T, P, R]) Order(orders ...func(*sql.Selector)) {
	rs := make([]R, len(orders))
	for i := range orders {
		rs[i] = orders[i]
	}
	q.tq.Order(rs...)
}

func (q query[T, P, R]) WhereP(ps ...func(*sql.Selector)) {
	p := make([]P, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	q.tq.Where(p...)
}
