-- Create "payment_profiles" table
CREATE TABLE "payment_profiles" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "user_id" bigint NOT NULL, "pan_masked" character varying NOT NULL, "holder" character varying NOT NULL, "email" character varying NOT NULL, "phone" character varying NOT NULL, "user_token" character varying NOT NULL, "recurrent_token" character varying NULL, PRIMARY KEY ("id"));
-- Create index "payment_profiles_recurrent_token_key" to table: "payment_profiles"
CREATE UNIQUE INDEX "payment_profiles_recurrent_token_key" ON "payment_profiles" ("recurrent_token");
-- Modify "invoices" table
ALTER TABLE "invoices" ADD COLUMN "one_vision_transaction_id" character varying NULL, ADD COLUMN "payment_profile_id" bigint NULL, ADD CONSTRAINT "invoices_payment_profiles_invoices" FOREIGN KEY ("payment_profile_id") REFERENCES "payment_profiles" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
