// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Bundle is the predicate function for bundle builders.
type Bundle func(*sql.Selector)

// ConsumedStatus is the predicate function for consumedstatus builders.
type ConsumedStatus func(*sql.Selector)

// Invoice is the predicate function for invoice builders.
type Invoice func(*sql.Selector)

// Item is the predicate function for item builders.
type Item func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// SubscriptionStatus is the predicate function for subscriptionstatus builders.
type SubscriptionStatus func(*sql.Selector)
